### ISSUE TITLE
ping.py could not run with python3.9 version,TypeError comes out.

### ISSUE THREAD

**Issue by leechaowen** [SecureAuthCorp/impacket#1021]
run ping.py with python3.9 , erros comes out.

$ sudo python39 ping.py 192.168.254.8 192.168.254.1
Traceback (most recent call last):
  File "/home/lichaowen/Downloads/Timestamprequest/impacket-0.9.22/examples/ping.py", line 52, in <module>
    icmp.contains(ImpactPacket.Data("A"*156))
  File "/usr/local/python3.9/lib/python3.9/site-packages/impacket/ImpactPacket.py", line 485, in __init__
    self.set_data(aBuffer)
  File "/usr/local/python3.9/lib/python3.9/site-packages/impacket/ImpactPacket.py", line 488, in set_data
    self.set_bytes_from_string(data)
  File "/usr/local/python3.9/lib/python3.9/site-packages/impacket/ImpactPacket.py", line 59, in set_bytes_from_string
    self.__bytes = array.array('B', data)
TypeError: cannot use a str to initialize an array with typecode 'B'

**Comment by Uniqu3Ch1** [comment]
In line 52 of ping.py, change "A" to b"A" to solve this problem.
