### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by m4darax** [SecureAuthCorp/impacket#1051]
command:> python3 psexec.py m4dara.com/test:Discord123$@192.168.1.12 cmd.exe -debug

Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket
[+] StringBinding ncacn_np:m4dara.com/test:Discord123192.168.1.12[\pipe\svcctl]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/nmb.py", line 897, in _setup_connection
    af, socktype, proto, canonname, sa = socket.getaddrinfo(peer[0], peer[1], 0, socket.SOCK_STREAM)[0]
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/impacket/examples/psexec.py", line 119, in doStuff
    dce.connect()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/dcerpc/v5/rpcrt.py", line 801, in connect
    return self._transport.connect()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/dcerpc/v5/transport.py", line 504, in connect
    self.setup_smb_connection()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/dcerpc/v5/transport.py", line 496, in setup_smb_connection
    self.__smb_connection = SMBConnection(self.getRemoteName(), self.getRemoteHost(), sess_port=self.get_dport(),
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/smbconnection.py", line 78, in __init__
    self.negotiateSession(preferredDialect)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/smbconnection.py", line 117, in negotiateSession
    packet = self.negotiateSessionWildcard(self._myName, self._remoteName, self._remoteHost, self._sess_port,
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/smbconnection.py", line 166, in negotiateSessionWildcard
    self._nmbSession = nmb.NetBIOSTCPSession(myName, remoteName, remoteHost, nmb.TYPE_SERVER, sess_port,
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/nmb.py", line 892, in __init__
    NetBIOSSession.__init__(self, myname, remote_name, remote_host, remote_type=remote_type, sess_port=sess_port,
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/nmb.py", line 752, in __init__
    self._sock = self._setup_connection((remote_host, sess_port), timeout)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.23.dev1+20210315.121412.a16198c3-py3.9.egg/impacket/nmb.py", line 904, in _setup_connection
    raise socket.error("Connection error (%s:%s)" % (peer[0], peer[1]), e)
OSError: [Errno Connection error (m4dara.com/test:Discord123192.168.1.12:445)] [Errno -2] Name or service not known
[-] [Errno Connection error (m4dara.com/test:Discord123192.168.1.12:445)] [Errno -2] Name or service not known

**Comment by Lz1y** [comment]
+1

**Comment by martingalloar** [comment]
Hey @m4darax! Looks like this is an escaping issue. Can you please try again with quoting the password or the entire string?

Either
`python3 psexec.py m4dara.com/test:'Discord123$'@192.168.1.12 cmd.exe -debug`
or
`python3 psexec.py 'm4dara.com/test:Discord123$@192.168.1.12' cmd.exe -debug`
should work.

**Comment by martingalloar** [comment]
Closing, please reopen if you still have issues with this!
