### ISSUE TITLE
"TypeError: a bytes-like object is required, not 'str'" when calling prettyPrint() on an object created with CCache.loadKirbiFile()

### ISSUE THREAD

**Issue by DidierA** [SecureAuthCorp/impacket#1056]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20201015.130615.81eec85a
Python version:  3.8.5
Target OS:  linux 5.4.0 (ubuntu)

### Debug Output With Command String  

```shell
# Create a  ticket to kirbi format to trigger the problem:
./ticketer.py -nthash 4031b5ae4b9defa1f411f26610493e0c -domain-sid S-1-5-21-126282473-2140987555-3925513934 -domain Win2016.local baduser
./ticketConverter.py ./baduser.ccache ./baduser.kirbi
#  Actual problem here vv
./ticketDumper.py ~/Tools/impacket/examples/baduser.kirbi 
Impacket v0.9.22.dev1+20201015.130615.81eec85a - Copyright 2020 SecureAuth Corporation

[*] loading kirbi file /home/didier/Tools/impacket/examples/baduser.kirbi
Primary Principal: b'baduser@WIN2016.LOCAL'
Credentials: 
[0]
	Client: b'baduser@WIN2016.LOCAL'
	Server: b'krbtgt/WIN2016.LOCAL@WIN2016.LOCAL'
Traceback (most recent call last):
  File "./ticketDumper.py", line 70, in <module>
    main()
  File "./ticketDumper.py", line 55, in main
    ccache.prettyPrint()
  File "/home/didier/Tools/impacket/impacket/krb5/ccache.py", line 535, in prettyPrint
    credential.prettyPrint('\t') 
  File "/home/didier/Tools/impacket/impacket/krb5/ccache.py", line 247, in prettyPrint
    print(("%s%s" % (indent, self.header['key'].prettyPrint())))
  File "/home/didier/Tools/impacket/impacket/krb5/ccache.py", line 69, in prettyPrint
    return "Key: (0x%x)%s" % (self['keytype'], hexlify(self['keyvalue']))
TypeError: a bytes-like object is required, not 'str'
```
### Additional context  
When calling `prettyPrint()` from a `CCache` object created with `CCache.loadKirbiFile()` (so when importing a ticket comming from mimikatz) , I get the _TypeError_ above.
on a `CCache` objet created with `CCache.loadFile()`, no issue.
#### Workaround
```python 
ccache= CCache.loadKirbiFile(filename)
ccache=CCache(ccache.getData())
```
When reconstructing the object fhis way, the issue is avoided, `prettPprint()` won't throw an error.
I guess there is something in `CCache.fromKRBCRED()` (which is called by `loadKirbiFile`) that fills incorrect types into the object properties.

I have attached `ticketDumper.py` which is based on `ticketConverter`, but simply dumps the ticket properties.
[ticketDumper.py.txt](https://github.com/SecureAuthCorp/impacket/files/6318061/ticketDumper.py.txt)

**Comment by DidierA** [comment]
Also, it seems that converting from ccache to kirbi loses the Auth Time: (note the Jan 1, 1970 in the output for the kirbi file)
```
./ticketDumper.py ./baduser.ccache
Impacket v0.9.22.dev1+20201015.130615.81eec85a - Copyright 2020 SecureAuth Corporation

[*] loading ccache file ./baduser.ccache
Primary Principal: b'baduser@WIN2016.LOCAL'
Credentials: 
[0]
	Client: b'baduser@WIN2016.LOCAL'
	Server: b'krbtgt/WIN2016.LOCAL@WIN2016.LOCAL'
	Key: (0x17)b'5a59586d48676967436653615a677966'
	Times: 
		Auth : 2021-04-15T14:37:56
		Start: 2021-04-15T14:37:56
		End  : 2031-04-13T14:37:56
		Renew: 2031-04-13T14:37:56
	SubKey: 0
	Flags: 0x50e00000
	Addresses: 0
	Auth Data: 0
	Ticket: b'6182031d30820319a003020105a10f1b0d57494e323031362e4c4f43414ca2223020a003020102a11930171b066b72627467741b0d57494e323031362e4c4f43414ca38202db308202d7a003020117a103020102a28202c9048202c573b89d1a2f273ef51284ede00bc38450c158359f76f542daf8f8e1d76d26f3fab4c3acf60f7fe445fa649ec1ea75c01d4d446c386b70f986c02834a6e35a9ed9f806ad84caa490593a899f3ccdcbd2be603ffe5959b5b90d7c2b7a0a3b0c3509b33f8233286e5e27e5611405345b5c0e6909f9584d2a4a5bba8c16325ec671234c2ed4ef9e7f89b8c494c8f9a21d20ef7ccb0d07cd9c76317460599da7f637f39bc8d665c3137755ca9af07281619ccc3ce868302fff49fa536e044a860bb49bf98c458b77821994053d3818b3bbd932fef21e3cca79f770d696b36d5954f7080ff44e6636a76c2099956dd3d5dfc04afceeee77e07806c65d5df8b26d5b5f89fdbb4005317a01a663850e81220766bf2d5cfb6119154b43b39ea81a6dd8f8980a0bc63bcdf206f3c66761c1d0467b7147ce3f987b43ad753a1663c7083ce8624b255b567316daad157fc023b997e070f2e9819b8d464ed3e4ff146d1ec33ef89eeb2de882c4fd0b2380b73bc29f3cd702a82ca3c39388a9160b6f9f98c1b89049e2f6aa789f2c39c95ac7378dd923dcef09a722b8e03a2daa12ab22e8e8367a279121982b345c2a4c44def282b2eab44dcbf59451674d2527ea87bef6b6b65b17e16e12090adfc5f6301485b774a835f8ecf96dc9a111322f42b25d099c67bd960a41515b7792315de3bd398f77ae77a8d5a06bb0b49c883ef7b78a8b99bbd5491d1edbef5ba7dcd89869f96a7ba6f4ac8c077cc0f868286cd0940cf73cde66d7f651f9b3ae1d51b998e413de4a6b4c87e7db200d0c267a761149459071c005b77b17196bce6e03270f08bbb96ba2bf2d88644e91c7c96241e6ebf3225a8680b45cfca0847c00470898cf1a2d7c34295f41af1e9207d36d757a98bb42971b2ef08b5de2db1a5cbf88f67823ee7d86e0005a16e6b28bc93d95f62a40bb3751a3c7c064717f1f2fae848dd202d869713ed54830a056ef1acc0d70f13e10adf90b0abb1f4b13'
	Second Ticket: b''
[+] done
(impacket)didier@lv426: ~/Tools/impacket/examples[fix-prettyprint…] $ ./ticketDumper.py ./baduser.kirbi
Impacket v0.9.22.dev1+20201015.130615.81eec85a - Copyright 2020 SecureAuth Corporation

[*] loading kirbi file ./baduser.kirbi
Primary Principal: b'baduser@WIN2016.LOCAL'
Credentials: 
[0]
	Client: b'baduser@WIN2016.LOCAL'
	Server: b'krbtgt/WIN2016.LOCAL@WIN2016.LOCAL'
	Key: (0x17)b'5a59586d48676967436653615a677966'
	Times: 
		Auth : 1970-01-01T01:00:00
		Start: 2021-04-15T14:37:56
		End  : 2031-04-13T14:37:56
		Renew: 2031-04-13T14:37:56
	SubKey: 0
	Flags: 0x50e00000
	Addresses: 0
	Auth Data: 0
	Ticket: b'6182031d30820319a003020105a10f1b0d57494e323031362e4c4f43414ca2223020a003020102a11930171b066b72627467741b0d57494e323031362e4c4f43414ca38202db308202d7a003020117a103020102a28202c9048202c573b89d1a2f273ef51284ede00bc38450c158359f76f542daf8f8e1d76d26f3fab4c3acf60f7fe445fa649ec1ea75c01d4d446c386b70f986c02834a6e35a9ed9f806ad84caa490593a899f3ccdcbd2be603ffe5959b5b90d7c2b7a0a3b0c3509b33f8233286e5e27e5611405345b5c0e6909f9584d2a4a5bba8c16325ec671234c2ed4ef9e7f89b8c494c8f9a21d20ef7ccb0d07cd9c76317460599da7f637f39bc8d665c3137755ca9af07281619ccc3ce868302fff49fa536e044a860bb49bf98c458b77821994053d3818b3bbd932fef21e3cca79f770d696b36d5954f7080ff44e6636a76c2099956dd3d5dfc04afceeee77e07806c65d5df8b26d5b5f89fdbb4005317a01a663850e81220766bf2d5cfb6119154b43b39ea81a6dd8f8980a0bc63bcdf206f3c66761c1d0467b7147ce3f987b43ad753a1663c7083ce8624b255b567316daad157fc023b997e070f2e9819b8d464ed3e4ff146d1ec33ef89eeb2de882c4fd0b2380b73bc29f3cd702a82ca3c39388a9160b6f9f98c1b89049e2f6aa789f2c39c95ac7378dd923dcef09a722b8e03a2daa12ab22e8e8367a279121982b345c2a4c44def282b2eab44dcbf59451674d2527ea87bef6b6b65b17e16e12090adfc5f6301485b774a835f8ecf96dc9a111322f42b25d099c67bd960a41515b7792315de3bd398f77ae77a8d5a06bb0b49c883ef7b78a8b99bbd5491d1edbef5ba7dcd89869f96a7ba6f4ac8c077cc0f868286cd0940cf73cde66d7f651f9b3ae1d51b998e413de4a6b4c87e7db200d0c267a761149459071c005b77b17196bce6e03270f08bbb96ba2bf2d88644e91c7c96241e6ebf3225a8680b45cfca0847c00470898cf1a2d7c34295f41af1e9207d36d757a98bb42971b2ef08b5de2db1a5cbf88f67823ee7d86e0005a16e6b28bc93d95f62a40bb3751a3c7c064717f1f2fae848dd202d869713ed54830a056ef1acc0d70f13e10adf90b0abb1f4b13'
	Second Ticket: b''
[+] done
```

**Comment by DidierA** [comment]
Thanks! I can confirm it solves this use case.
