### ISSUE TITLE
Issue with NTLMRelayx not starting up properly

### ISSUE THREAD

**Issue by somerandomdudeonetheinternet** [SecureAuthCorp/impacket#1098]
Ntlmrelayx is not starting properly for some reason. Driving me mad, unable to fix this myself. Anyone have any ideas ? 

ntlmrelayx.py
Impacket v0.9.24.dev1+20210611.72516.1a5ed9dc - Copyright 2021 SecureAuth Corporation

[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client DCSYNC loaded..
Traceback (most recent call last):
  File "/usr/local/bin/ntlmrelayx.py", line 345, in <module>
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
  File "/usr/local/lib/python3.9/dist-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 57, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "/usr/local/lib/python3.9/dist-packages/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 24, in <module>
    from impacket.examples.smbclient import MiniImpacketShell
  File "/usr/local/lib/python3.9/dist-packages/impacket/examples/smbclient.py", line 38, in <module>
    import pyreadline as readline
  File "/usr/local/lib/python3.9/dist-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/usr/local/lib/python3.9/dist-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/usr/local/lib/python3.9/dist-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
    from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
  File "/usr/local/lib/python3.9/dist-packages/pyreadline/keysyms/__init__.py", line 23, in <module>
    raise ImportError("Could not import keysym for local pythonversion", x)
NameError: name 'x' is not defined

![image](https://user-images.githubusercontent.com/13917476/122687651-7ab5a880-d20f-11eb-8af2-3b3e6e282d28.png)

**Comment by somerandomdudeonetheinternet** [comment]
So looks like this can be fixed by allocating some random value to "X". Looks like this issue has come up in other software, and the developers have just remove the exception. Not sure why it is needed and if it has been added recently. 

![image](https://user-images.githubusercontent.com/13917476/122939539-9e8e0100-d36b-11eb-9fd3-c48586a5787a.png)
![image](https://user-images.githubusercontent.com/13917476/122939593-ab125980-d36b-11eb-860d-1cb2b0320904.png)
