### ISSUE TITLE
Struct error unpack requires a buffer of 1 bytes _ New

### ISSUE THREAD

**Issue by Aixic-Love** [SecureAuthCorp/impacket#1103]
### Configuration  
impacket version:  Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporatio
Python version:  Python3.6
Target OS:  Darwin Administrator 20.3.0 Darwin Kernel Version 20.3.0

### Debug Output With Command String  
i.e.  
python3.6 wmiexec.py -hashes xxx domain/user:password@127.0.0.1  -debug 
```
python3.6 wmiexec.py -hashes xxx domain/user:password@127.0.0.1  -debug 
Traceback (most recent call last):
  File "wmiexec.py", line 92, in run
    win32Process,_ = iWbemServices.GetObject('Win32_Process')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 2976, in GetObject
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1312, in request
    self.connect(iid)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1230, in connect
    newDce = dce.alter_ctx(iid)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1429, in alter_ctx
    answer.bind(newUID, alter = 1, bogus_binds = bogus_binds, transfer_syntax = bin_to_uuidtup(self.transfer_syntax))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1034, in bind
    resp = MSRPCHeader(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 635, in __init__
    Structure.__init__(self,data, alignment)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 323, in unpack
    return self.unpack(two[0],data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")
[-] ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")
Traceback (most recent call last):
  File "wmiexec.py", line 92, in run
    win32Process,_ = iWbemServices.GetObject('Win32_Process')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 2976, in GetObject
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1312, in request
    self.connect(iid)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1230, in connect
    newDce = dce.alter_ctx(iid)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1429, in alter_ctx
    answer.bind(newUID, alter = 1, bogus_binds = bogus_binds, transfer_syntax = bin_to_uuidtup(self.transfer_syntax))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1034, in bind
    resp = MSRPCHeader(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/rpcrt.py", line 635, in __init__
    Structure.__init__(self,data, alignment)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 323, in unpack
    return self.unpack(two[0],data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wmiexec.py", line 442, in <module>
    executer.run(address)
  File "wmiexec.py", line 105, in run
    smbConnection.logoff()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/smbconnection.py", line 374, in logoff
    return self._SMBConnection.logoff()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/smb3.py", line 1528, in logoff
    ans = self.recvSMB(packetID)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/smb3.py", line 434, in recvSMB
    data = self._NetBIOSSession.recv_packet(self._timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/nmb.py", line 1001, in __read
    data = self.read_function(4, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/nmb.py", line 993, in non_polling_read
    raise NetBIOSError('Error while reading from remote', ERRCLASS_OS, None)
impacket.nmb.NetBIOSError: Error while reading from remote
[-] Error while reading from remote
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by Aixic-Love** [comment]
Impacket v0.9.24.dev1 - Copyright 2021 SecureAuth Corporation 
NO!....

**Comment by 0xdeaddood** [comment]
Hi @Aixic-Love. What is the version of Windows you are targeting? A PCAP capture it would be helpful.

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.
