### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by muxueo** [SecureAuthCorp/impacket#1143]
### Configuration  
impacket version:  0.9.24
Python version:  3.9
Target OS:  Kali Linux
### Debug Output With Command String  
i.e.  
python3 ntlmrelayx.py -t smb://10.10.0.129 -smb2support
```
python3 ntlmrelayx.py -t smb://10.10.0.129 -smb2support
Impacket v0.9.24.dev1 - Copyright 2021 SecureAuth Corporation

[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client DCSYNC loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server
[*] Setting up WCF Server

[*] Servers started, waiting for connections
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1-py3.9.egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 430, in run
    self.server = self.HTTPServer((self.config.interfaceIp, httpport), self.HTTPHandler, self.config)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1-py3.9.egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 45, in __init__
    socketserver.TCPServer.__init__(self,server_address, RequestHandlerClass)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
I checked port 445, nothing

![image](https://user-images.githubusercontent.com/50110633/129738903-2f030249-ddc4-4ba6-a8f0-86ff4e184200.png)

**Comment by martingalloar** [comment]
Hey @muxueo! I think that based on the traceback the port in question is HTTP's one, not 445.

Closing, reopen if there's any issue that might be associated with the code itself.
