### ISSUE TITLE
Problem with smbclient: KDC_ERR_PREAUTH_FAILED

### ISSUE THREAD

**Issue by TrashBox4null0** [SecureAuthCorp/impacket#1150]
[CommunicationError.zip](https://github.com/SecureAuthCorp/impacket/files/7075639/CommunicationError.zip)
### Configuration  
impacket version:  last one
Python version:  python 3.9.2
Target OS:  kali linux 2021.2

### Debug Output With Command String  
└─$ smbclient.py -debug -k intelligence.htb/Administrator@dc.intelligence.htb -no-pass
Impacket v0.9.24.dev1+20210814.5640.358fc7c6 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket
[+] Trying to connect to KDC at INTELLIGENCE.HTB
[+] Trying to connect to KDC at INTELLIGENCE.HTB
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/EGG-INFO/scripts/smbclient.py", line 100, in main
    smbClient.kerberosLogin(username, password, domain, lmhash, nthash, options.aesKey, options.dc_ip )
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket/smbconnection.py", line 366, in kerberosLogin
    raise e
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket/smbconnection.py", line 350, in kerberosLogin
    return self._SMBConnection.kerberosLogin(user, password, domain, lmhash, nthash, aesKey, kdcHost, TGT,
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket/smb3.py", line 658, in kerberosLogin
    tgt, cipher, oldSessionKey, sessionKey = getKerberosTGT(userName, password, domain, lmhash, nthash, aesKey, kdcHost)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket/krb5/kerberosv5.py", line 301, in getKerberosTGT
    tgt = sendReceive(encoder.encode(asReq), domain, kdcHost)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210814.5640.358fc7c6-py3.9.egg/impacket/krb5/kerberosv5.py", line 80, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)
[-] Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)

NOTE: The Administrator.ccache is in the same folder that the smbclient.py

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.
[CommunicationError.zip](https://github.com/SecureAuthCorp/impacket/files/7075661/CommunicationError.zip)

**Comment by 0xdeaddood** [comment]
Hi @TrashBox4null0!

I have a couple of questions to understand your issue: How did you generate the ccache file? Have you exported it before run smbclient? What does the `klist` command show?

**Comment by TrashBox4null0** [comment]
Hi

After read your comments, i reviewed the help of smbclient.py and saw my error.

The problem was that I didn't set up the KRB5CCNAME. After setting up it, the connect through smbclient.py worked

Thank you very much for all
Regards 
TrashBox4null0
