### ISSUE TITLE
ldapattack validatePrivileges index out of range

### ISSUE THREAD

**Issue by ad0nis** [SecureAuthCorp/impacket#1162]
### Configuration  
impacket version:  0.9.24.dev1+20210922.102044.c7bc76f8
Python version:  3.9
Target OS:  kali

### Output With Command String  
# Apologies that this isn't with debugging enabled.
output is from sudo ntlmrelayx.py -ts -6 -smb2support -socks --dump-laps --dump-gmsa -w -tf ~/relay_targets.txt -l ~/impacket_loot -of ~/impacket-hashes | sudo tee -a /home/kali/ntlmrelayx.log
```
Exception in thread Thread-3908:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210922.102044.c7bc76f8-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 562, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.9.24.dev1+20210922.102044.c7bc76f8-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 372, in validatePrivileges
    user = self.client.entries[0]
IndexError: list index out of range

```

### Additional context  
This error is repeating pretty often. I see indications of users with privileges to create users, but then a user is never created, so this looks like perhaps something broken in a recent update if I had to guess?

**Comment by ad0nis** [comment]
This bug is also present in the 0.9.23 stable release

**Comment by ad0nis** [comment]
Doing a bit of debugging on this, I added in a `print(self.client.entries)` just before that `user = self.client.entries[0]` line, and it appears that the variable is empty, which is triggering this condition. Does that mean that `self.client.search` on line 371 is failing to return any privs for some reason?

**Comment by ad0nis** [comment]
I was also able to re-produce this on 0.9.22 and 0.9.21, so I don't think this is a new code issue anymore, I'm more wondering if there's some possible security setting they might have enabled that is causing this. Would it be good to add a check around here to confirm that a valid response was received to silence the traceback?

**Comment by ad0nis** [comment]
Can also see this in streamer's videos showing off ntlmrelayx.py, including the following:

https://youtu.be/axPkf_kLpMA?t=2439

So this is not just an issue I am experiencing. :)

**Comment by 0xJs** [comment]
Also having this problem:

```
udo python3 ntlmrelayx.py -t ldap://192.168.1.7 --http-port 8080 --delegate-access --escalate-user 'FAKE01$' -debug -ts
Impacket v0.10.1.dev1+20220708.213759.8b1a99f7 - Copyright 2022 SecureAuth Corporation

---snip---

[2022-07-27 13:36:29] [*] HTTPD(8080): Connection from 192.168.1.13 controlled, attacking target ldap://192.168.1.7
[2022-07-27 13:36:30] [*] HTTPD(8080): Authenticating against ldap://192.168.1.7 as / SUCCEED
[2022-07-27 13:36:30] [*] Enumerating relayed user's privileges. This may take a while on large domains
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.10.1.dev1+20220708.213759.8b1a99f7-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 802, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.9/dist-packages/impacket-0.10.1.dev1+20220708.213759.8b1a99f7-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 485, in validatePrivileges
    user = self.client.entries[0]
IndexError: list index out of range
[2022-07-27 13:36:30] [+] No more targets
[2022-07-27 13:36:30] [*] HTTPD(8080): Connection from 192.168.1.13 controlled, but there are no more targets left!
```

**Comment by spookey0188** [comment]
> Also having this problem. Can't seem to print more info for the error. Hope this helps a bit:
> 
> ```
> sudo python3 ntlmrelayx.py -t ldap://192.168.1.7 --http-port 8080 --delegate-access --escalate-user 'FAKE01$' -debug -ts
> Impacket v0.10.1.dev1+20220708.213759.8b1a99f7 - Copyright 2022 SecureAuth Corporation
> 
> ---snip---
> 
> [2022-07-27 13:36:29] [*] HTTPD(8080): Connection from 192.168.1.13 controlled, attacking target ldap://192.168.1.7
> [2022-07-27 13:36:30] [*] HTTPD(8080): Authenticating against ldap://192.168.1.7 as / SUCCEED
> [2022-07-27 13:36:30] [*] Enumerating relayed user's privileges. This may take a while on large domains
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.9/dist-packages/impacket-0.10.1.dev1+20220708.213759.8b1a99f7-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 802, in run
>     userSid, privs = self.validatePrivileges(self.username, domainDumper)
>   File "/usr/local/lib/python3.9/dist-packages/impacket-0.10.1.dev1+20220708.213759.8b1a99f7-py3.9.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 485, in validatePrivileges
>     user = self.client.entries[0]
> IndexError: list index out of range
> [2022-07-27 13:36:30] [+] No more targets
> [2022-07-27 13:36:30] [*] HTTPD(8080): Connection from 192.168.1.13 controlled, but there are no more targets left!
> ```

Hello. I am also experiencing this. Using the latest git clone. Have you found a solution?
