### ISSUE TITLE
smbclient.py fails download large file

### ISSUE THREAD

**Issue by fuzztester** [SecureAuthCorp/impacket#1212]
### Configuration  
impacket version: 0.9.24  
Python version: 3.9.7  
Target OS:  Kali

### Debug Output With Command String  
  
python3 -debug /opt/impacket/examples/smbclient.py <redacted>  
```
[-] ("'L' format requires 0 <= number <= 4294967295", "When packing field 'Offset | <L | 4295005000' in <class 'impacket.smb.SMBReadAndX_Parameters'>", "When 
packing field 'WordCount | B=len(Parameters)//2' in <class 'impacket.smb.SMBCommand'>", "When packing field 'Data | *: | [<impacket.smb.SMBCommand object at 0
x7f677edca7c0>]' in <class 'impacket.smb.NewSMBPacket'>")
[+] Exception info
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 202, in pack
    return self.pack(two[0], data)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 266, in pack
    raise Exception("Trying to pack None")
Exception: Trying to pack None
  
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/impacket/examples/smbclient.py", line 83, in onecmd
    retVal = cmd.Cmd.onecmd(self,s)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.9/dist-packages/impacket/examples/smbclient.py", line 489, in do_get
    self.smb.getFile(self.share, pathname, fh.write)
  File "/usr/local/lib/python3.9/dist-packages/impacket/smbconnection.py", line 803, in getFile
    return self._SMBConnection.retr_file(shareName, pathName, callback)
  File "/usr/local/lib/python3.9/dist-packages/impacket/smb.py", line 4014, in retr_file
    self.__nonraw_retr_file(tid, fid, offset, datasize, callback)
  File "/usr/local/lib/python3.9/dist-packages/impacket/smb.py", line 3066, in __nonraw_retr_file
    data = self.read_andx(tid, fid, read_offset, max_buf_size)
  File "/usr/local/lib/python3.9/dist-packages/impacket/smb.py", line 3683, in read_andx
    self.sendSMB(smb)
  File "/usr/local/lib/python3.9/dist-packages/impacket/smb.py", line 2662, in sendSMB
    self._sess.send_packet(smb.getData())
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 126, in getData
    data += self.packField(field[0], field[1])
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 111, in packField
    ans = self.pack(format, self.fields[fieldName], field = fieldName)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 232, in pack
    answer += self.pack(two[1], each)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 271, in pack
    return data.getData()
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 126, in getData
    data += self.packField(field[0], field[1])
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 113, in packField
    ans = self.pack(format, None, field = fieldName)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 206, in pack
    return self.pack(two[0], eval(two[1], {}, fields))
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 179, in __len__
    return len(self.getData())
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 126, in getData
    data += self.packField(field[0], field[1])
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 111, in packField
    ans = self.pack(format, self.fields[fieldName], field = fieldName)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 232, in pack
    answer += self.pack(two[1], each)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 271, in pack
    return data.getData()
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 126, in getData
    data += self.packField(field[0], field[1])
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 113, in packField
    ans = self.pack(format, None, field = fieldName)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 206, in pack
    return self.pack(two[0], eval(two[1], {}, fields))
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 179, in __len__
    return len(self.getData())
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 126, in getData
    data += self.packField(field[0], field[1])
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 111, in packField
    ans = self.pack(format, self.fields[fieldName], field = fieldName)
  File "/usr/local/lib/python3.9/dist-packages/impacket/structure.py", line 290, in pack
    return pack(format, data)
struct.error: ("'L' format requires 0 <= number <= 4294967295", "When packing field 'Offset | <L | 4295005000' in <class 'impacket.smb.SMBReadAndX_Parameters'>", "When packing field 'WordCount | B=len(Parameters)//2' in <class 'impacket.smb.SMBCommand'>", "When packing field 'Data | *: | [<impacket.smb.SMBCommand object at 0x7f677edca7c0>]' in <class 'impacket.smb.NewSMBPacket'>")
```

### Additional context  
File being downloaded is ~40g VMWare disk image. It appears the download is failing around the 4g mark.

**Comment by fuzztester** [comment]
server only supports smb1, file size is too big
