### ISSUE TITLE
[Errno 113] No route to host - tried debug mode - didnt work unless im doing it wrong

### ISSUE THREAD

**Issue by mitsukiyouko555** [SecureAuthCorp/impacket#1252]
### Configuration  
impacket version:  Impacket v0.9.19
Python version:  3.9.9
Target OS:  microsoft windows version 10.0.17763.2061 (hackthebox archetype)

Experience: n00b
--------------------

After reinstalling impacket since i was having issues with it, it wouldnt let me run it with python 3 (i removed all instances of impacket that i know of..... and ): 

python3 mssqlclient.py ARCHETYPE/sql_svc@10.129.161.59 -windows-auth      
  File "/opt/impacket-0.9.19/examples/mssqlclient.py", line 38
    print """
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(""")?

-------------------------

Tried running it with python and got the error below

-------------------------
### Debug Output With Command String  
──(mitsukiyouko555㉿mitsukiyouko555)-[/opt/impacket-0.9.19/examples]
└─$ python mssqlclient.py -debug ARCHETYPE/sql_svc@10.129.161.59 -windows-auth
/usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

Password:
Traceback (most recent call last):
  File "mssqlclient.py", line 171, in <module>
    ms_sql.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/tds.py", line 531, in connect
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host

Traceback (most recent call last):
  File "/usr/lib64/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'RemoteShell' object has no attribute 'do_net'
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  

Same issue as https://github.com/SecureAuthCorp/impacket/issues/1078#issuecomment-840709679 
would reopen but did not see a button for it, probably because Im not the OP.

**Comment by 0xdeaddood** [comment]
Hi @mitsukiyouko555!

`[Errno 113] No route to host` denotes a network problem. Basically your computer can't reach the target server. There could be several reasons, you can start by answering these questions: Are you sure that the server is online? Have you checked the IP address? Can you reach the server with ping? Is the SQL service running there? Have you checked the firewall?

Another important thing, you're using a very old version of Impacket. That's the reason why you can't use python 3. Try to install the latest version.

**Comment by mitsukiyouko555** [comment]
Hi @0xdeaddood  thanks for replying!

> Are you sure that the server is online? Have you checked the IP address? Can you reach the server with ping? Is the SQL service running there?
Yes to all of these

> Have you checked the firewall? Not sure how to do that but this is a hackthebox machine so its made to be vulnerable..  its one of the introductory machines too XD

> Another important thing, you're using a very old version of Impacket. That's the reason why you can't use python 3. Try to install the latest version.

could you please send me instructions on how to get the latest version? 
i've followed the hackthebox guide to installing impacket, that didnt work - removed what came out of that. 
found a way to do it on the kali linux website - followed that.. 
tried downloading directly from this github.. none of these are the latest ver it seems.. 

or it could just be i dont know where and/or how to go about installing the latest version... could you please advise on that?

Thank you very much :D

**Comment by 0xdeaddood** [comment]
> ^ im thinking this is probably the issue could you please send me instructions on how to get the latest version?
> 
> i've followed the hackthebox guide to installing impacket, that didnt work - removed what came out of that. found a way to do it on the kali linux website - followed that.. tried downloading directly from this github.. none of these are the latest ver it seems..
> 
> or it could just be i dont know where and/or how to go about installing the latest version... could you please advise on that?
> 
> Thank you very much :D

You can grab the latest stable release from [here](https://github.com/SecureAuthCorp/impacket/releases/download/impacket_0_9_24/impacket-0.9.24.tar.gz), unpack it and run: `python3 -m pip install .` from the directory where you placed it. This version will be fine.

_If you want use the latest dev version, you have to copy the repo with  `git clone https://github.com/SecureAuthCorp/impacket.git`  and install it running `python3 -m pip install .`_

**Comment by mitsukiyouko555** [comment]
![2022-02-10_18-04](https://user-images.githubusercontent.com/25854884/153527584-7c455424-5231-488f-a61d-7b0e2c1de139.png)
