### ISSUE TITLE
Please, tell me what wrong.

### ISSUE THREAD

**Issue by webgtx** [SecureAuthCorp/impacket#1279]
### Configuration  
impacket version: impacket_0_9_24
Python version:  3.10.2
Target OS: Fedora Linux 35

### Debug Output With Command String  
i.e.  
python3 ~/.local/bin/mssqlclient.py ARCHETYPE/sql_svc:M3g4c0rp123@{10.129.62.48} -windows-auth 
```

Impacket v0.9.25.dev1+20220311.121550.1271d369 - Copyright 2021 SecureAuth Corporation

Traceback (most recent call last):
  File "/home/dxv1d/.local/bin/mssqlclient.py", line 169, in <module>
    ms_sql.connect()
  File "/home/dxv1d/.local/lib/python3.10/site-packages/impacket/tds.py", line 531, in connect
    af, socktype, proto, canonname, sa = socket.getaddrinfo(self.server, self.port, 0, socket.SOCK_STREAM)[0]
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by 0xdeaddood** [comment]
Hi @webgtx!

You have to define the target IP address without  `{}`. Closing...

**Comment by webgtx** [comment]
> Damn... Im sorry
