### ISSUE TITLE
rdp_check.py doesn't handle Windows 7 x64 when RDP is disabled in the windows registry

### ISSUE THREAD

**Issue by quahac** [SecureAuthCorp/impacket#1333]
```
root@device:/usr/share/doc/python3-impacket/examples# python3 rdp_check.py test-PC/Administrator:password@192.168.0.76
 or
root@device:~# impacket-rdp_check Administrator:password@192.168.0.76

Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation
 Traceback (most recent call last):
    File "/usr/share/doc/python3-impacket/examples/rdp_check.py", line 574, in <module>
      check_rdp(address, username, password, domain, options.hashes)
    File "/usr/share/doc/python3-impacket/examples/rdp_check.py", line 387, in check_rdp
      pkt = s.recv(8192)
  ConnectionResetError: [Errno 104] Connection reset by peer

```

Suggestion is to put this code line 387 handling this error (works for me well)  https://github.com/SecureAuthCorp/impacket/blob/a98b7b97416650cd2a23e480a69be61b65ec2f0a/examples/rdp_check.py#L387
```
try:
  pkt = s.recv(8192)
except:
 print("[-] Access Denied or RPD disabled!")
 exit(1)
```

**Comment by w0shlzheNdecaI** [comment]
if windows7 x64 RDP is enabled, can you success?

**Comment by quahac** [comment]
if RDP is enabled, there is no problem.

**Comment by quahac** [comment]
> > if RDP is enabled, there is no problem.
> 
> use TLS1.2 or TLS1.0?

I found it. It wasn't rdp_check,py afterall. After windows updating Win7 it was fixed :)

**Comment by quahac** [comment]
Thx
