### ISSUE TITLE
Error while parsing NTDS in local : Unpacked data doesn't match constant value 'b'\\x00\\x00\\x00\\x00'' should be ''regf''

### ISSUE THREAD

**Issue by skidrow88** [SecureAuthCorp/impacket#1345]
### Configuration  
impacket version:  0.10.0
Python version:  python3.9

### Debug Output With Command String  
secretsdump.py -system SYSTEM -ntds NTDS.dit LOCAL
```
➜  Active Directory secretsdump.py -debug -system SYSTEM -ntds NTDS.dit LOCAL
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.9/site-packages/impacket
Traceback (most recent call last):
  File "/usr/local/bin/secretsdump.py", line 130, in dump
    bootKey = localOperations.getBootKey()
  File "/usr/local/lib/python3.9/site-packages/impacket/examples/secretsdump.py", line 2698, in getBootKey
    winreg = winregistry.Registry(self.__systemHive, False)
  File "/usr/local/lib/python3.9/site-packages/impacket/winregistry.py", line 170, in __init__
    self.__regf = REG_REGF(data)
  File "/usr/local/lib/python3.9/site-packages/impacket/structure.py", line 87, in __init__
    self.fromString(data)
  File "/usr/local/lib/python3.9/site-packages/impacket/structure.py", line 152, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python3.9/site-packages/impacket/structure.py", line 315, in unpack
    raise Exception("Unpacked data doesn't match constant value '%r' should be '%r'" % (data, answer))
Exception: ("Unpacked data doesn't match constant value 'b'\\x00\\x00\\x00\\x00'' should be ''regf''", 'When unpacking field \'Magic | "regf | b\'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\x00\\x00\\x00\\x00\\x00\\x00\\...........................x00\\x00\\x00\\x00\\x00\'[:4]\'')
[*] Cleaning up...
```

### Additional context  
- NTDS was grab with ntdsutil.exe
- The domaine name is `customer-paris.fr`
- The NetBIOS name is DOMAINE
- The functional level is Windows2016domaine

**Comment by skidrow88** [comment]
Problem resolved. The files were corrupted
