### ISSUE TITLE
 from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS wrong

### ISSUE THREAD

**Issue by z0edff0x3d** [SecureAuthCorp/impacket#1347]
### Configuration  
impacket version:  0.10.0
Python version:  3.9
Target OS:  macos bigsur

### Debug Output With Command String  
 
when i use python3 ntlmrelayx.py --remove-mic --escalate-user saul -t ldap://10.x.x.x -smb2support,i got something wrong
```
python3 ntlmrelayx.py --remove-mic --escalate-user saul -t ldap://10.x.x.x -smb2support
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client DCSYNC loaded..
Traceback (most recent call last):
  File "/Users/Cfe/impacket/impacket-0.10.0/examples/ntlmrelayx.py", line 384, in <module>
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
  File "/Users/Cfe/Library/Python/3.9/lib/python/site-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 56, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "/Users/Cfe/Library/Python/3.9/lib/python/site-packages/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 23, in <module>
    from impacket.examples.smbclient import MiniImpacketShell
  File "/Users/Cfe/Library/Python/3.9/lib/python/site-packages/impacket/examples/smbclient.py", line 40, in <module>
    import pyreadline as readline
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/pyreadline-2.1-py3.9.egg/pyreadline/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/pyreadline-2.1-py3.9.egg/pyreadline/clipboard/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/pyreadline-2.1-py3.9.egg/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/pyreadline-2.1-py3.9.egg/pyreadline/keysyms/__init__.py", line 23, in <module>
NameError: name 'x' is not defined
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by z0edff0x3d** [comment]
NameError: name 'x' is not defined

**Comment by 0xdeaddood** [comment]
Hi @z0edff0x3d!

The `pyreadline` module is only required on Windows. When it's imported into other systems it throws that error. Unless you need it for a particular reason, you could remove it and the script will work.

I'm closing this issue now. Feel free to reopen it if problem persists
