### ISSUE TITLE
Access Denied with LogonNetworkTransitive on AD 2022

### ISSUE THREAD

**Issue by extrafu** [SecureAuthCorp/impacket#1354]
Hello,

Using impacket v0.10 with AD 202. When trying to do an LogonNetworkTransitive using the code below, I get the following error: `impacket.dcerpc.v5.nrpc.DCERPCSessionError: NRPC SessionError: code: 0xc0000022 - STATUS_ACCESS_DENIED - {Access Denied} A process has requested access to an object but has not been granted those access rights.` From AD's GPO editor, if I add the machine_user (cluster1 in my case) to "Domain controller: Allow vulnerable Netlogon secure channel connections", everything works as expected. So my question is what can be changed in the code below so that it works without adding the machine_user to that exception list? A secure channel is supposedly already established.

```python
#!/usr/bin/env python
import argparse
import binascii
from binascii import unhexlify, hexlify

import sys
import time

from impacket.dcerpc.v5 import nrpc, epm
from impacket.dcerpc.v5 import transport

ad_ip = '172.20.20.232'
serverName = 'WIN-HOTO5OA823F.nachos.local'
machine_user = 'cluster1$'
lmhash = 'thelmhash'
nthash = 'thenthash'

domain = 'nachos'
username= 'administrator'
challenge = dbb7dacb353c11bc
nt_response = a2568637cae095a457278c6ceb4de3961a06b772b85a0985
request_nt_key = 1

stringBinding = epm.hept_map(ad_ip, nrpc.MSRPC_UUID_NRPC, protocol='ncacn_ip_tcp')
rpctransport = transport.DCERPCTransportFactory(stringBinding)
rpctransport.set_credentials(machine_user, '', domain, lmhash, nthash)
dce = rpctransport.get_dce_rpc()
dce.connect()
dce.bind(nrpc.MSRPC_UUID_NRPC)

resp = nrpc.hNetrServerReqChallenge(dce, serverName, machine_user, b'12345678')
serverChallenge = resp['ServerChallenge']

bnthash = unhexlify(nthash)
sessionKey = nrpc.ComputeSessionKeyStrongKey('', b'12345678', serverChallenge, bnthash)

clientStoredCredential = nrpc.ComputeNetlogonCredential(b'12345678',sessionKey)

flags = 0x600FFFFF
resp = nrpc.hNetrServerAuthenticate3(dce, serverName, machine_user + '\x00',
                                     nrpc.NETLOGON_SECURE_CHANNEL_TYPE.WorkstationSecureChannel,
                                     machine_user, clientStoredCredential, flags)
timestamp = 0

request = nrpc.NetrLogonSamLogon()
request['LogonServer'] = serverName + '\x00'
request['ComputerName'] = machine_user + '\x00'
request['LogonLevel'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonNetworkTransitiveInformation
request['LogonInformation']['tag'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonNetworkTransitiveInformation
request['LogonInformation']['LogonNetworkTransitive']['Identity']['LogonDomainName'] = domain
request['LogonInformation']['LogonNetworkTransitive']['Identity']['ParameterControl'] = 2 + 2 ** 14 + 2 ** 7 + 2 ** 9 + 2 ** 5 + 2 ** 11
request['LogonInformation']['LogonNetworkTransitive']['Identity']['UserName'] = username
request['LogonInformation']['LogonNetworkTransitive']['Identity']['Workstation'] = ''
request['LogonInformation']['LogonNetworkTransitive']['LmChallenge'] = binascii.unhexlify(challenge)
request['LogonInformation']['LogonNetworkTransitive']['NtChallengeResponse'] = binascii.unhexlify(nt_response)
request['ValidationLevel'] = nrpc.NETLOGON_VALIDATION_INFO_CLASS.NetlogonValidationSamInfo4
request['Authenticator'] = nrpc.ComputeNetlogonAuthenticator(clientStoredCredential, sessionKey)
request['ReturnAuthenticator']['Credential'] = b'\x00' * 8
request['ReturnAuthenticator']['Timestamp'] = timestamp

resp = dce.request(request)

if request_nt_key:
        sessionKey = resp['ValidationInformation']['ValidationSam4']['UserSessionKey']
        print('NT_KEY: ' + binascii.hexlify(sessionKey).decode("ascii").upper())

sys.exit(0)
```

**Comment by extrafu** [comment]
Quick update, I've added:

```python
dce.set_auth_level(RPC_C_AUTHN_LEVEL_PKT_PRIVACY)
dce.set_auth_type(RPC_C_AUTHN_NETLOGON)
```
but it bails out with this error:

```
Traceback (most recent call last):
  File "ntlm_win_2022.py", line 68, in <module>
    resp = nrpc.hNetrServerReqChallenge(dce, serverName, machine_user, b'12345678')
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/nrpc.py", line 2716, in hNetrServerReqChallenge
    return dce.request(request)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 858, in request
    self.call(request.opnum, request, uuid)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 847, in call
    return self.send(DCERPC_RawCall(function, body.getData(), uuid))
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1300, in send
    self._transport_send(data)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1201, in _transport_send
    sealedMessage, signature = nrpc.SEAL(plain_data, self.__confounder, self.__sequence, self.__sessionKey, False)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/nrpc.py", line 1781, in SEAL
    signature = SIGN(data, confounder, sequenceNum, key, aes)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/nrpc.py", line 1766, in SIGN
    signature['Checksum'] = ComputeNetlogonSignatureMD5(signature, data, confounder, key)
  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/nrpc.py", line 1710, in ComputeNetlogonSignatureMD5
    hm = hmac.new(sessionKey, digestmod=hashlib.md5)
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
```

**Comment by ly4k** [comment]
Any updates on this? Getting the same error even after adding the machine to the GPO.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,
After a long debugging session, I think it is because `ComputeNetlogonCredential` within `ComputeNetlogonAuthenticator` returns 16 bytes instead of 8. The Impacket implementation lacks the "key transformation" introduced in the first paragraph [here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nrpc/04f184c7-d31b-44d0-9647-970d07b536c2). The 16 bytes sessionkey must be "converted" to a 8 bytes one.
I need to do more tests, but imo, if you put a 16 bytes (wrong) data in a 8 bytes field, then the next field (timestamp) is also wrong, thus `access denied` returned.

:sunflower:

**Comment by rtpt-romankarwacik** [comment]
I tried adapting the example from @ThePirateWhoSmellsOfSunflowers  from https://github.com/fortra/impacket/pull/1848 (See [here](https://gist.github.com/rtpt-romankarwacik/3a0941463f0e479943c42f8028916a32)) but I get `STATUS_ACCESS_DENIED`:

```
$ python3 NetrLogonSamLogon.py
[+] Calling hept_map: ('12345678-1234-ABCD-EF00-01234567CFFB', '1.0')
[x] Binding string: ncacn_ip_tcp:dc.lab.redteam[49695]
[-] client chall: 9c9cdf1e6c4897e3
[x] Calling NetrServerReqChallenge
[x] NetrServerReqChallenge ok!
[-] server chall: 3a649bbec343893f
[-] session Key: 229e42d31b40c0fd52009aa5e109c96a
[-] client credential: 8fb52af89a7fddf3
[+] Calling NetrServerAuthenticate3
[x] NetrServerAuthenticate3 ok!
[-] server credential: 29e86c7884789696
[-] Netlogon authenticator: 024e8a32af62e647
[+] Calling NetrLogonGetCapabilities
[x] NetrLogonGetCapabilities ok!
[+] Calling NetrLogonSamLogon
Traceback (most recent call last):
  File "/vagrant/netlogon/NetrLogonSamLogon.py", line 136, in <module>
    raise e
  File "/vagrant/netlogon/NetrLogonSamLogon.py", line 132, in <module>
    resp = dce.request(request)
           ^^^^^^^^^^^^^^^^^^^^
  File "/vagrant/python-lib/impacket/dcerpc/v5/rpcrt.py", line 882, in request
    raise exception
impacket.dcerpc.v5.nrpc.DCERPCSessionError: NRPC SessionError: code: 0xc0000022 - STATUS_ACCESS_DENIED - {Access Denied} A process has requested access to an object but has not been granted those access rights.
```

Anyone getting this to work?

**Comment by NeffIsBack** [comment]
For anyone looking into this, you need to properly upgrade the rpc connection and set the session key after authentication. Here my working script, adapted from https://gist.github.com/ThePirateWhoSmellsOfSunflowers/f41c334f912ec033d9bbfc7e96308ec6 (other variables, but you will get the hang of it):
```python
self.rpc_con.set_credentials(self.AccountName, "", self.domain)
self.rpc_con.set_auth_type(RPC_C_AUTHN_NETLOGON)
self.rpc_con.set_auth_level(RPC_C_AUTHN_LEVEL_PKT_PRIVACY)

# dce.alter_ctx does not keep confounder settings and increments ctx_id, so we use bind() with alter=1
self.rpc_con.bind(nrpc.MSRPC_UUID_NRPC, alter=1)

self.rpc_con.set_session_key(self.session_key)
self.rpc_con.set_aes(self.AES)    # False in this case as we use Strong Keys for authentication
```
