### ISSUE TITLE
AttributeError: type object 'CCache' has no attribute 'parseFile' when using GetUserSPNs.py

### ISSUE THREAD

**Issue by inky9329** [SecureAuthCorp/impacket#1368]
### Configuration  
impacket version:  v0.9.24
Python version:  3.10.4
Target OS:  Microsoft SQL Server 2019

### Debug Output With Command String  
```
python3 GetUserSPNs.py  -dc-ip dc.test.local scrm.local/ksimpson:ksimpson -request -k -no-pass -debuga
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/lib/python3/dist-packages/impacket
[+] Connecting to dc.test.local, port 389, SSL False
[+] Using Kerberos Cache: ksimpson.ccache
[+] SPN LDAP/DC.TEST.LOCAL@SCRM.LOCAL not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/SCRM.LOCAL@SCRM.LOCAL
[+] Using TGT from cache
[+] Trying to connect to KDC at dc.test.local
[+] Connecting to dc.test.local, port 636, SSL True
[+] Using Kerberos Cache: ksimpson.ccache
[+] SPN LDAP/DC.TEST.LOCAL@SCRM.LOCAL not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/SCRM.LOCAL@SCRM.LOCAL
[+] Using TGT from cache
[+] Trying to connect to KDC at dc.test.local
[+] Total of records returned 4
ServicePrincipalName          Name    MemberOf  PasswordLastSet             LastLogon                   Delegation 
----------------------------  ------  --------  --------------------------  --------------------------  ----------
MSSQLSvc/dc.test.local:1433  sqlsvc            2021-11-03 10:32:02.351452  2022-07-07 07:38:58.550450             
MSSQLSvc/dc.test.local       sqlsvc            2021-11-03 10:32:02.351452  2022-07-07 07:38:58.550450             



Traceback (most recent call last):
  File "/home/kali/Downloads/impacket-0.10.0/examples/GetUserSPNs.py", line 492, in <module>
    executer.run()
  File "/home/kali/Downloads/impacket-0.10.0/examples/GetUserSPNs.py", line 353, in run
    TGT = self.getTGT()
  File "/home/kali/Downloads/impacket-0.10.0/examples/GetUserSPNs.py", line 132, in getTGT
    domain, _, TGT, _ = CCache.parseFile(self.__domain)
AttributeError: type object 'CCache' has no attribute 'parseFile'
[-] type object 'CCache' has no attribute 'parseFile'

```

### Additional context  
Impacket returns the SPNs, but throws an error and exits before dumping the ticket.

**Comment by inky9329** [comment]
Sorry for the duplicate issue, has been fixed.
