### ISSUE TITLE
tds.py --> encryptPassword() --> TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by Evanavevan** [SecureAuthCorp/impacket#1371]
### Configuration  
impacket version:  0.9.20
Python version:  3.6.8
Target OS:  centos7

### Debug Output With Command String  
```shell
mssqlclient.py 'sa:YE%TJC%&HYbe5Nw@10.10.10.59' -debug
/usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

[*] Encryption required, switching to TLS
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/bin/mssqlclient.py", line 177, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
  File "/usr/local/lib/python3.6/site-packages/impacket/tds.py", line 952, in login
    login['Password'] = self.encryptPassword(password.encode('utf-16le'))
  File "/usr/local/lib/python3.6/site-packages/impacket/tds.py", line 526, in encryptPassword
    return ''.join([chr(((ord(x) & 0x0f) << 4) + ((ord(x) & 0xf0) >> 4) ^ 0xa5) for x in password])
  File "/usr/local/lib/python3.6/site-packages/impacket/tds.py", line 526, in <listcomp>
    return ''.join([chr(((ord(x) & 0x0f) << 4) + ((ord(x) & 0xf0) >> 4) ^ 0xa5) for x in password])
TypeError: ord() expected string of length 1, but int found
[-] ord() expected string of length 1, but int found
```

### Additional context  

change variable password type to string, and then success

```python
# tds.py
 def encryptPassword(self, password ):

        return ''.join([chr(((ord(x) & 0x0f) << 4) + ((ord(x) & 0xf0) >> 4) ^ 0xa5) for x in str(password)])
```

```shell
mssqlclient.py 'sa:YE%TJC%&HYbe5Nw@10.10.10.59'
/usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

[*] Encryption required, switching to TLS
[-] ERROR(TALLY): Line 1: Login failed for user 'sa'.
```

**Comment by 0xdeaddood** [comment]
Hi @Evanavevan,

You are using an older version of impacket. This was changed in v0.9.21: https://github.com/SecureAuthCorp/impacket/commit/2aa01011dc875a15aaec6e535a87e1c8a1d6032b

Closing.

**Comment by Evanavevan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你发的邮件我已经收到，我会尽快阅读你的邮件的
