### ISSUE TITLE
SOLVED - [('SSL routines', '', 'internal error')]

### ISSUE THREAD

**Issue by Scaum** [SecureAuthCorp/impacket#1400]
### Configuration  
impacket version:  0.10.0
Python version:  3.10.6
Target OS:  Kali

### Debug Output With Command String  
i.e.  
impacket-mssqlclient ***:*****@*****
```
impacket-mssqlclient -debug ***:*****@***** 
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[+] Impacket Library Installation Path: /home/kali/.local/lib/python3.10/site-packages/impacket
[*] Encryption required, switching to TLS
[+] Exception:
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/mssqlclient.py", line 175, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
  File "/home/kali/.local/lib/python3.10/site-packages/impacket/tds.py", line 881, in login
    tls.do_handshake()
  File "/home/kali/.local/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1991, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/kali/.local/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1700, in _raise_ssl_error
    _raise_current_error()
  File "/home/kali/.local/lib/python3.10/site-packages/OpenSSL/_util.py", line 55, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'internal error')]
[-] [('SSL routines', '', 'internal error')]
```

### Additional context  
Suddently stopped working. Was able to connect fine a week ago, now I'm running into this error.
I've tried uninstalling impacket completely and reinstalling, but that did not help

```
pip install impacket 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: impacket in /home/kali/.local/lib/python3.10/site-packages (0.10.0)
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from impacket) (4.0.0)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket) (0.9.3)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket) (2.0.3)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket) (3.11.0)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /home/kali/.local/lib/python3.10/site-packages (from impacket) (2.9.1)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from impacket) (0.18.2)
Requirement already satisfied: pyOpenSSL>=0.16.2 in /home/kali/.local/lib/python3.10/site-packages (from impacket) (22.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /home/kali/.local/lib/python3.10/site-packages (from impacket) (0.4.8)
Requirement already satisfied: six in /home/kali/.local/lib/python3.10/site-packages (from impacket) (1.16.0)
Requirement already satisfied: cryptography>=35.0 in /home/kali/.local/lib/python3.10/site-packages (from pyOpenSSL>=0.16.2->impacket) (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography>=35.0->pyOpenSSL>=0.16.2->impacket) (1.15.1)
```

**Comment by Scaum** [comment]
So it seems this comes from tds.py. The pip module still has the old version of that file, which is causing the problem.
The easiest way to fix this is to remove tds.py from your impacket install folder and download the new version from this repo.

Hope this helps someone else.
