### ISSUE TITLE
Can't get Name property from MSCluster_Node, the output gets garbled

### ISSUE THREAD

**Issue by Mysteoa** [SecureAuthCorp/impacket#1447]
### Configuration  
impacket version:   v0.10.0 
Python version:  Python 3.6.8
Target OS:  WMI 6.3.9600 | 2012R2

### Debug Output With Command String  

/opt/python-virtualenv/impacket/bin/wmiquery.py -debug 'AD/USER:PASS@IP' -namespace root/mscluster -rpc-auth-level privacy -f <( echo 'SELECT Name FROM MSCluster_Node' )
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[+] Impacket Library Installation Path: /opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket
[+] Target system is SERVERIP and isFQDN is False
[+] StringBinding: SERVERNAME[24158]
[+] StringBinding: SERVERIP[24158]
[+] StringBinding chosen: ncacn_ip_tcp:SERVERIP[24158]
WQL> SELECT Name FROM MSCluster_Node
Traceback (most recent call last):
  File "/usr/lib64/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'WMIQUERY' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-virtualenv/impacket/bin/wmiquery.py", line 84, in printReply
    pEnum = iEnum.Next(0xffffffff,1)[0]
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 2951, in Next
    oxid=self.get_oxid(), target=self.get_target()), self.__iWbemServices))
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 2328, in __init__
    self.encodingUnit = ENCODING_UNIT(objRef['pObjectData'])
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 87, in __init__
    self.fromString(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 152, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return dataClassOrCode(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 895, in __init__
    self.fromString(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 152, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return dataClassOrCode(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 795, in __init__
    Structure.__init__(self, data, alignment)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 87, in __init__
    self.fromString(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 152, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return dataClassOrCode(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 87, in __init__
    self.fromString(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 152, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/structure.py", line 382, in unpack
    return dataClassOrCode(data)
  File "/opt/python-virtualenv/impacket/lib/python3.6/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 765, in __init__
    raise Exception("self['InstPropQualSetFlag'] == 2")
Exception: ("self['InstPropQualSetFlag'] == 2", "When unpacking field 'InstancePropQualifierSet | : | b'\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:5904]'", "When unpacking field 'InstanceQualifierSet | : | b'\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:5908]'", "When unpacking field 'InstanceType | : | b'\\xef\\x05\\x046\\x07\\x80\\x01\\x0b\\xff\\xff\\x10\\x03\\t\\x04\\x06\\x80\\x08\\x18-\\x083\\x01[a\\x03\\x93\\x80MSCluster_NodeLocaleMS_CLUSTER_PROVIDERUUID{C306EBED-0654-4360-AA70-DE912C5FC364}Name\\x08@\\x1c\\n\\x80#\\x08\\x8b\\x01\\x803\\x0b\\xff\\xffstringz\\x10\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:6161]'", "When unpacking field 'ObjectBlock | : | b'\\x12\\xef\\x05\\x046\\x07\\x80\\x01\\x0b\\xff\\xff\\x10\\x03\\t\\x04\\x06\\x80\\x08\\x18-\\x083\\x01[a\\x03\\x93\\x80MSCluster_NodeLocaleMS_CLUSTER_PROVIDERUUID{C306EBED-0654-4360-AA70-DE912C5FC364}Name\\x08@\\x1c\\n\\x80#\\x08\\x8b\\x01\\x803\\x0b\\xff\\xffstringz\\x10\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:6162]'")
 [-] ("self['InstPropQualSetFlag'] == 2", "When unpacking field 'InstancePropQualifierSet | : | b'\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:5904]'", "When unpacking field 'InstanceQualifierSet | : | b'\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:5908]'", "When unpacking field 'InstanceType | : | b'\\xef\\x05\\x046\\x07\\x80\\x01\\x0b\\xff\\xff\\x10\\x03\\t\\x04\\x06\\x80\\x08\\x18-\\x083\\x01[a\\x03\\x93\\x80MSCluster_NodeLocaleMS_CLUSTER_PROVIDERUUID{C306EBED-0654-4360-AA70-DE912C5FC364}Name\\x08@\\x1c\\n\\x80#\\x08\\x8b\\x01\\x803\\x0b\\xff\\xffstringz\\x10\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:6161]'", "When unpacking field 'ObjectBlock | : | b'\\x12\\xef\\x05\\x046\\x07\\x80\\x01\\x0b\\xff\\xff\\x10\\x03\\t\\x04\\x06\\x80\\x08\\x18-\\x083\\x01[a\\x03\\x93\\x80MSCluster_NodeLocaleMS_CLUSTER_PROVIDERUUID{C306EBED-0654-4360-AA70-DE912C5FC364}Name\\x08@\\x1c\\n\\x80#\\x08\\x8b\\x01\\x803\\x0b\\xff\\xffstringz\\x10\\x04\\x02\\x1e\\x1f\\x11\\x08-7\\x11\\x03\\x03E\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType\\x1c\\x02\\x80MSCluster_NodeNODESERVER01PropertyNameNodeNamePropertyType'[:6162]'")

### Additional context  
It seem, when you try to get the Names of the nodes from MSCluster_Node class it breaks. It is only for the "Name" property.
Thise where repalce to sanitize the output AD/USER:PASS@IP, SERVERIP, SERVERNAME, NODESERVERNAME, NODESERVER01. There was alot of "\\x00" in the output that I removed to reduce it.

**Comment by badaszszsz** [comment]
do your homework mate as you did with ender3v2s1
