### ISSUE TITLE
LDAP 'not' search filter not working with pyasn1-0.2.3

### ISSUE THREAD

**Issue by asolino** [SecureAuthCorp/impacket#264]
As reported by @mubix:

Executing 'GetUserSPNs.py' against a DC will trigger this issue. Traceback outputs:
```
Traceback (most recent call last):
  File "./GetUserSPNs.py", line 393, in <module>
    executer.run()
  File "./GetUserSPNs.py", line 231, in run
    sizeLimit=0, searchControls = [sc])
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 359, in search
    searchRequest['filter'] = self._parseFilter(searchFilter)
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 460, in _parseFilter
    searchFilter = self._consumeCompositeFilter(filterList)
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 485, in _consumeCompositeFilter
    filters.append(self._consumeCompositeFilter(filterList))
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 497, in _consumeCompositeFilter
    return self._compileCompositeFilter(operator, filters)
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 537, in _compileCompositeFilter
    searchFilter['not'].setComponents(*filters)
  File "build/bdist.macosx-10.12-intel/egg/pyasn1/type/base.py", line 540, in setComponents
    self[idx] = value
  File "build/bdist.macosx-10.12-intel/egg/pyasn1/type/univ.py", line 1947, in __setitem__
    base.AbstractConstructedAsn1Item.__setitem__(self, idx, value)
  File "build/bdist.macosx-10.12-intel/egg/pyasn1/type/base.py", line 555, in __setitem__
    self.setComponentByPosition(idx, value)
  File "build/bdist.macosx-10.12-intel/egg/pyasn1/type/univ.py", line 2472, in setComponentByPosition
    componentType = self._componentType.getTypeByPosition(idx)
  File "build/bdist.macosx-10.12-intel/egg/pyasn1/type/namedtype.py", line 139, in getTypeByPosition
    raise error.PyAsn1Error('Type position out of range')
PyAsn1Error: Type position out of range 
```
Running the same script with `pyasn1-0.2.2` doesn't trigger this problem. Until we figure out this issue stick to that version of pyasn1.

Any take on this @kacpern?

**Comment by kacpern** [comment]
I'm still in NZ, I'll take a look when I'm back next week if it's not too late. There's been a lot of changes in pyasn recently, will need to revisit the implementation.

**Comment by mubix** [comment]
Confirmed, and unfortunately homebrew on OSX is shipping 0.2.3 ;-)

**Comment by asolino** [comment]
> I'm still in NZ, I'll take a look when I'm back next week if it's not too late. There's been a lot of changes in pyasn recently, will need to revisit the implementation.

Thanks @kacpern. I just made a quick (and dirty) change that makes it work. Don't know exactly why (since it doesn't follow the RPC) but seems to be working until you can take a deeper look at it.

**Comment by asolino** [comment]
No answer, closing
