### ISSUE TITLE
psexec timeout will leave orphan binaries/services

### ISSUE THREAD

**Issue by symeonp** [SecureAuthCorp/impacket#322]
Hey Alberto!

Here's another issue that I've encountered, imagine we have the following psexec:
```
/usr/local/Cellar/python/2.7.13/bin/python psexec.py Administrator@10.4.10.221
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[*] Requesting shares on 10.4.10.221.....
[*] Found writable share ADMIN$
[*] Uploading file aXMBIlGV.exe
[*] Opening SVCManager on 10.4.10.221.....
[*] Creating service ISuY on 10.4.10.221.....
[*] Starting service ISuY.....
[!] Press help for extra shell commands
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd ..
```

So we are ready to execute commands, however I noticed the same behaviour from Sysinternals PsExec, what happens when somehow the connection gets lost/interrupted/AV picks up the binary?

I restarted the VM on purpose until eventually I got this error:
``` C:\Windows>dir ```
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "psexec.py", line 407, in run
    self.shell.cmdloop()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "psexec.py", line 389, in default
    self.send_data(line.decode(sys.stdin.encoding).encode('cp437')+'\r\n')
  File "psexec.py", line 397, in send_data
    self.server.writeFile(self.tid, self.fid, data)
  File "/usr/local/lib/python2.7/site-packages/impacket/smbconnection.py", line 532, in writeFile
    return self._SMBConnection.writeFile(treeId, fileId, data, offset)
  File "/usr/local/lib/python2.7/site-packages/impacket/smb3.py", line 1415, in writeFile
    written = self.write(treeId, fileId, writeData, writeOffset, len(writeData))
  File "/usr/local/lib/python2.7/site-packages/impacket/smb3.py", line 1119, in write
    ans = self.recvSMB(packetID)
  File "/usr/local/lib/python2.7/site-packages/impacket/smb3.py", line 382, in recvSMB
    data = self._NetBIOSSession.recv_packet(self._timeout)
  File "/usr/local/lib/python2.7/site-packages/impacket/nmb.py", line 854, in recv_packet
    data = self.__read(timeout)
  File "/usr/local/lib/python2.7/site-packages/impacket/nmb.py", line 932, in __read
    data = self.read_function(4, timeout)
  File "/usr/local/lib/python2.7/site-packages/impacket/nmb.py", line 919, in non_polling_read
    received = self._sock.recv(bytes_left)
error: [Errno 54] Connection reset by peer
```
So the issue here is now that I don't have access anymore this leaves both the service and the binary deployed on the system without being able to communicate back to me.
My question would be is there a way to clean up itself after X amount of failed tries back to the attacker?
Would that require to modify the RemCom project?
Could I help you somehow?
Thank you so much!

**Comment by asolino** [comment]
This is a known issue when dropping a binary at the target. There are other approaches that do not require such thing. Changing the RemCom Project is beyond the scope of impacket. Closing as won't fix.
