### ISSUE TITLE
dcom failure

### ISSUE THREAD

**Issue by Mikkgn** [SecureAuthCorp/impacket#444]
When wmiquery example is executed,  this error occurs:

```
[-] string index out of range
Traceback (most recent call last):
  File "wmiquery.py", line 187, in <module>
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "C:\Python27\lib\site-packages\impacket\dcerpc\v5\dcomrt.py", line 1056, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "C:\Python27\lib\site-packages\impacket\dcerpc\v5\dcomrt.py", line 1876, in RemoteCreateInstance
    if strBindings[0] == '\x00' and strBindings[1] == '\x00':
IndexError: string index out of range
```
Target OS Windows 2000 Server SP4,

**Comment by asolino** [comment]
Hey @Mikkgn 

Please run it again with `-debug` and send me the output.

**Comment by Mikkgn** [comment]
debug option don't add info about problem. But I updated package version, and get a slightly different error
```
py -2.7 wmiquery.py -debug administrator:P@ssw0rd@192.168.243.19
Impacket v0.9.17 - Copyright 2002-2018 Core Security Technologies

[-] string indices must be integers, not str
```

**Comment by asolino** [comment]
Can't determine the issue given the data provided

**Comment by goDeni** [comment]
in _20 version fixed?
@Mikkgn
