### ISSUE TITLE
Struct error unpack requires a buffer of 1 bytes

### ISSUE THREAD

**Issue by ofmendi** [SecureAuthCorp/impacket#535]
Hi, 

I am getting an error while collecting Sysmon Log with WMI from the remote computer.

Error;

```

File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 380, in unpack
     return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")
```

How can I fix this problem?

Thanks.

**Comment by asolino** [comment]
Hey @ofmendi 

What script are you running? Is it `wmiquery.py`, please send me the full request or something that will help me reproduce the problem on my side.

**Comment by ofmendi** [comment]
Actually when I try same things on wimquery.py I get different an error. 

> $ python wmiquery.py domain/username:password@host

```
WQL> SELECT * FROM Win32_NTLogEvent WHERE LogFile = 'Microsoft-Windows-Sysmon/Operational'
[-] 'ascii' codec can't decode byte 0xae in position 255: ordinal not in range(128)
```

I think a relationship between errors.

**Comment by asolino** [comment]
Hey @ofmendi 

What impacket version are you using? (That will be shown in the banner when you execute the script). 
Also, please execute `wmiquery.py` with the `-debug` flag to check if there's extra data that is relevant to pinpoint this issue (e.g. tracebacks)

**Comment by ofmendi** [comment]
My Impacket version "v0.9.18-dev" and I am using Python 3.6.5.

> $ python wmiquery.py domain/username:password@ip -debug

```
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[+] Target system is ********* and isFDQN is False
[+] StringBinding: hostname[49764]
[+] StringBinding: *********[49764]
[+] StringBinding: *********[49764]
[+] StringBinding: *********[49764]
[+] StringBinding chosen: ncacn_ip_tcp:*********[49764]
[!] Press help for extra shell commands
WQL> SELECT * FROM WIn32_NTLogEvent WHERE LogFIle = 'MIcrosoft-WIndows-Sysmon/OperatIonal'
| RecordNumber | Logfile | EventIdentifier | EventCode | SourceName | Type | Category | CategoryString | TimeGenerated | TimeWritten | ComputerName | User | Message | InsertionStrings | Data | EventType |
| 4740 | Microsoft-Windows-Sysmon/Operational | 1 | 1 | Microsoft-Windows-Sysmon | Information | 1 | Process Create (rule: ProcessCreate) | 20181206163201.202391-000 | 20181206163201.202391-000 | hostname | NT AUTHORITY\SYSTEM | Process Create:
RuleName:
UtcTime: 2018-12-06 16:32:01.195
ProcessGuid: {BFA10301-4F01-5C09-0000-001016BC3307}
ProcessId: 15196
Image: C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\Updater.exe
FileVersion: 1.8.0.0
Description: Updater Module
Product: Updater Module
Company: ?
CommandLine: "C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\Updater.exe" -runmode=checkupdate
CurrentDirectory: C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\
User: NT AUTHORITY\SYSTEM
LogonGuid: {BFA10301-3400-5C06-0000-0020E7030000}
LogonId: 0x3E7
TerminalSessionId: 0
IntegrityLevel: System
Hashes: MD5=FBE0664E1C333E36E3CE73D8BD5CC8A1,SHA256=C4CE15B1BC8ADECBF20A655256AAB267C1D72E7A33947598AF48EA287CCA5670
ParentProcessGuid: {BFA10301-4F01-5C09-0000-001053B83307}
ParentProcessId: 12632
ParentImage: C:\Program Files (x86)\Skillbrains\Updater\Updater.exe
ParentCommandLine: "C:\Program Files (x86)\Skillbrains\Updater\Updater.exe" -runmode=checkupdate |  2018-12-06 16:32:01.195 {bfa10301-4f01-5c09-0000-001016bc3307} 15196 C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\Updater.exe 1.8.0.0 Updater Module Updater Module ? "C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\Updater.exe" -runmode=checkupdate C:\Program Files (x86)\Skillbrains\Updater\1.8.0.0\ NT AUTHORITY\SYSTEM {bfa10301-3400-5c06-0000-0020e7030000} 0x3e7 0 System MD5=FBE0664E1C333E36E3CE73D8BD5CC8A1,SHA256=C4CE15B1BC8ADECBF20A655256AAB267C1D72E7A33947598AF48EA287CCA5670 {bfa10301-4f01-5c09-0000-001053b83307} 12632 C:\Program Files (x86)\Skillbrains\Updater\Updater.exe "C:\Program Files (x86)\Skillbrains\Updater\Updater.exe" -runmode=checkupdate  | 0 | 3 |
| 4739 | Microsoft-Windows-Sysmon/Operational | 1 | 1 | Microsoft-Windows-Sysmon | Information | 1 | Process Create (rule: ProcessCreate) | 20181206163201.184834-000 | 20181206163201.184834-000 | hostname | NT AUTHORITY\SYSTEM | Process Create:
RuleName:
UtcTime: 2018-12-06 16:32:01.175
ProcessGuid: {BFA10301-4F01-5C09-0000-001053B83307}
ProcessId: 12632
Image: C:\Program Files (x86)\Skillbrains\Updater\Updater.exe
FileVersion: 1.0.0.1
Description: TODO: <File description>
Product: TODO: <Product name>
Company: TODO: <Company name>
CommandLine: "C:\Program Files (x86)\Skillbrains\Updater\Updater.exe" -runmode=checkupdate
CurrentDirectory: C:\WINDOWS\system32\
User: NT AUTHORITY\SYSTEM
LogonGuid: {BFA10301-3400-5C06-0000-0020E7030000}
LogonId: 0x3E7
TerminalSessionId: 0
IntegrityLevel: System
Hashes: MD5=3EC8F4BD54EF439A8FAB6467122DA0C4,SHA256=A5E3BDC3B0B0BD6455892E23008161B5478B24F4FE1801F43A8A01CFFF1BCBA7
ParentProcessGuid: {BFA10301-3405-5C06-0000-0010E00C0200}
ParentProcessId: 1512
ParentImage: C:\Windows\System32\svchost.exe
ParentCommandLine: c:\windows\system32\svchost.exe -k netsvcs -p -s Schedule |  2018-12-06 16:32:01.175 {bfa10301-4f01-5c09-0000-001053b83307} 12632 C:\Program Files (x86)\Skillbrains\Updater\Updater.exe 1.0.0.1 TODO: <File description> TODO: <Product name> TODO: <Company name> "C:\Program Files (x86)\Skillbrains\Updater\Updater.exe" -runmode=checkupdate C:\WINDOWS\system32\ NT AUTHORITY\SYSTEM {bfa10301-3400-5c06-0000-0020e7030000} 0x3e7 0 System MD5=3EC8F4BD54EF439A8FAB6467122DA0C4,SHA256=A5E3BDC3B0B0BD6455892E23008161B5478B24F4FE1801F43A8A01CFFF1BCBA7 {bfa10301-3405-5c06-0000-0010e00c0200} 1512 C:\Windows\System32\svchost.exe c:\windows\system32\svchost.exe -k netsvcs -p -s Schedule  | 0 | 3 |
Traceback (most recent call last):
  File "c:\program files\python36\Lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'WMIQUERY' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wmiquery.py", line 79, in printReply
    pEnum = iEnum.Next(0xffffffff,1)[0]
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2851, in Next
    oxid=self.get_oxid(), target=self.get_target()), self.__iWbemServices))
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2294, in __init__
    self.parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2333, in parseObject
    self.encodingUnit['ObjectBlock'].parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 954, in parseObject
    self.ctCurrent = self.parseClass(ctCurrent, self['InstanceType'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 942, in parseClass
    classDict['values'] = cInstance.getValues(classDict['properties'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 808, in getValues
    value = ENCODED_VALUE.getValue( properties[key]['type'], itemValue, heap)
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 360, in getValue
    value = ENCODED_STRING(heapData)['Character']
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 153, in __init__
    self.fromString(data)
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 358, in unpack
    return data[:-1].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 289: ordinal not in range(128)
[-] 'ascii' codec can't decode byte 0xae in position 289: ordinal not in range(128)
```

**Comment by asolino** [comment]
> My Impacket version "v0.9.18-dev" and I am using Python 3.6.5.

Are you using the `python36` branch?

**Comment by ofmendi** [comment]
Yes I'm using python36 branch.

I pulled new updates. I did same test and result is below.
 
```
λ python wmiquery.py domain/username:password@ip -debug
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[+] Target system is <ip_addr> and isFDQN is False
[+] StringBinding: <hostname>[49732]
[+] StringBinding: <ip_addr>[49732]
[+] StringBinding: <ip_addr>[49732]
[+] StringBinding: <ip_addr>[49732]
[+] StringBinding chosen: ncacn_ip_tcp:<ip_addr>[49732]
[!] Press help for extra shell commands
WQL> SELECT * FROM WIn32_NTLogEvent WHERE LogFIle = 'MIcrosoft-WIndows-Sysmon/OperatIonal'
| RecordNumber | Logfile | EventIdentifier | EventCode | SourceName | Type | Category | CategoryString | TimeGenerated | TimeWritten | ComputerName | User | Message | InsertionStrings | Data | EventType |
| 20821 | Microsoft-Windows-Sysmon/Operational | 1 | 1 | Microsoft-Windows-Sysmon | Information | 1 | Process Create (rule: ProcessCreate) | 20181217073157.058128-000 | 20181217073157.058128-000 | <hostname> | NT AUTHORITY\SYSTEM | Process Create:
RuleName:
UtcTime: 2018-12-17 07:31:57.048
ProcessGuid: {BFA10301-50ED-5C17-0000-00101D964400}
ProcessId: 10248
Image: C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesCommonX86\Microsoft Shared\OFFICE16\SDXHelper.exe
FileVersion: 16.0.11029.20079
Description: Microsoft Office SDX Helper
Product: Microsoft Office
Company: Microsoft Corporation
CommandLine: "C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesCommonX86\Microsoft Shared\Office16\sdxhelper.exe" /onlogon
CurrentDirectory: C:\WINDOWS\system32\
User: <hostname>\Administrator
LogonGuid: {BFA10301-4D67-5C17-0000-002008DA1000}
LogonId: 0x10DA08
TerminalSessionId: 1
IntegrityLevel: High
Hashes: MD5=049933B432D86A4313D712692B1BACC3,SHA256=2DBC707F7A0BDA76F6593323201B167D05F929F1E104247734BAC8568667D744
ParentProcessGuid: {BFA10301-4D3A-5C17-0000-0010F4E80100}
ParentProcessId: 1520
ParentImage: C:\Windows\System32\svchost.exe
ParentCommandLine: c:\windows\system32\svchost.exe -k netsvcs -p -s Schedule |  2018-12-17 07:31:57.048 {bfa10301-50ed-5c17-0000-00101d964400} 10248 C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesCommonX86\Microsoft Shared\OFFICE16\SDXHelper.exe 16.0.11029.20079 Microsoft Office SDX Helper Microsoft Office Microsoft Corporation "C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesCommonX86\Microsoft Shared\Office16\sdxhelper.exe" /onlogon C:\WINDOWS\system32\ <hostname>\Administrator {bfa10301-4d67-5c17-0000-002008da1000} 0x10da08 1 High MD5=049933B432D86A4313D712692B1BACC3,SHA256=2DBC707F7A0BDA76F6593323201B167D05F929F1E104247734BAC8568667D744 {bfa10301-4d3a-5c17-0000-0010f4e80100} 1520 C:\Windows\System32\svchost.exe c:\windows\system32\svchost.exe -k netsvcs -p -s Schedule  | 0 | 3 |
Traceback (most recent call last):
  File "c:\program files\python36\Lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'WMIQUERY' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./examples/wmiquery.py", line 79, in printReply
    pEnum = iEnum.Next(0xffffffff,1)[0]
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2851, in Next
    oxid=self.get_oxid(), target=self.get_target()), self.__iWbemServices))
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2294, in __init__
    self.parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2333, in parseObject
    self.encodingUnit['ObjectBlock'].parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 954, in parseObject
    self.ctCurrent = self.parseClass(ctCurrent, self['InstanceType'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 942, in parseClass
    classDict['values'] = cInstance.getValues(classDict['properties'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 808, in getValues
    value = ENCODED_VALUE.getValue( properties[key]['type'], itemValue, heap)
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 360, in getValue
    value = ENCODED_STRING(heapData)['Character']
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 153, in __init__
    self.fromString(data)
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 358, in unpack
    return data[:-1].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 288: ordinal not in range(128)
[-] 'ascii' codec can't decode byte 0xae in position 288: ordinal not in range(128)
```

**Comment by asolino** [comment]
Thanks for the @ofmendi 

Apologies, I need you to `git pull` and run the same command again.

**Comment by ofmendi** [comment]
Hi @asolino 

I did and result is below.

Thanks for your help.

```
Impacket v0.9.18-dev - Copyright 2018 SecureAuth Corporation

[+] Target system is ip and isFDQN is False
[+] StringBinding: hostname[59296]
[+] StringBinding: ip[59296]
[+] StringBinding: ip[59296]
[+] StringBinding: ip[59296]
[+] StringBinding chosen: ncacn_ip_tcp:ip[59296]
[!] Press help for extra shell commands
WQL> SELECT * FROM Win32_NTLogEvent WHERE LogFile = 'Microsoft-Windows-Sysmon/Operational'
Traceback (most recent call last):
  File "c:\program files\python36\Lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'WMIQUERY' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wmiquery.py", line 79, in printReply
    pEnum = iEnum.Next(0xffffffff,1)[0]
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2851, in Next
    oxid=self.get_oxid(), target=self.get_target()), self.__iWbemServices))
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2294, in __init__
    self.parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2333, in parseObject
    self.encodingUnit['ObjectBlock'].parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 954, in parseObject
    self.ctCurrent = self.parseClass(ctCurrent, self['InstanceType'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 942, in parseClass
    classDict['values'] = cInstance.getValues(classDict['properties'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 808, in getValues
    value = ENCODED_VALUE.getValue( properties[key]['type'], itemValue, heap)
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 360, in getValue
    value = ENCODED_STRING(heapData)['Character']
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 153, in __init__
    self.fromString(data)
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 358, in unpack
    return data[:-1].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 277: ordinal not in range(128)
[-] 'ascii' codec can't decode byte 0xae in position 277: ordinal not in range(128)
```

**Comment by asolino** [comment]
Hey @ofmendi 

I don't think you have your code updated. Based on your output:
```
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 360, in getValue
    value = ENCODED_STRING(heapData)['Character']
```
With the latest code, that line should be different, check [here](https://github.com/SecureAuthCorp/impacket/blob/python36/impacket/dcerpc/v5/dcom/wmi.py#L360).
Bottom line, I want to dump the data that is triggering the UnicodeError exception.

**Comment by ofmendi** [comment]
I'm sorry it's my fault. I'm taking the new update, but I forgot to upload it again.

The new result is below.

```
λ python examples/wmiquery.py domain/username:password@ip_addr -debug
Impacket v0.9.19-dev - Copyright 2018 SecureAuth Corporation

[+] Target system is ip_addr and isFDQN is False
[+] StringBinding: hostname[59296]
[+] StringBinding: ip_addr[59296]
[+] StringBinding chosen: ncacn_ip_tcp:ip_addr[59296]
[!] Press help for extra shell commands
WQL> SELECT * FROM WIn32_NTLogEvent WHERE LogFIle = 'MIcrosoft-WIndows-Sysmon/OperatIonal'
[+] Unicode Error: dumping heapData
 0000   00 50 72 6F 63 65 73 73  20 43 72 65 61 74 65 3A   .Process Create:
 0010   0D 0A 52 75 6C 65 4E 61  6D 65 3A 20 0D 0A 55 74   ..RuleName: ..Ut
 0020   63 54 69 6D 65 3A 20 32  30 31 38 2D 31 32 2D 31   cTime: 2018-12-1
 0030   39 20 30 36 3A 34 33 3A  32 30 2E 38 36 39 0D 0A   9 06:43:20.869..
 0040   50 72 6F 63 65 73 73 47  75 69 64 3A 20 7B 42 46   ProcessGuid: {BF
 0050   41 31 30 33 30 31 2D 45  38 38 38 2D 35 43 31 39   A10301-E888-5C19
 0060   2D 30 30 30 30 2D 30 30  31 30 45 34 31 43 36 34   -0000-0010E41C64
 0070   30 31 7D 0D 0A 50 72 6F  63 65 73 73 49 64 3A 20   01}..ProcessId:
 0080   31 30 36 30 38 0D 0A 49  6D 61 67 65 3A 20 43 3A   10608..Image: C:
 0090   5C 57 69 6E 64 6F 77 73  5C 53 79 73 74 65 6D 33   \Windows\System3
 00a0   32 5C 73 76 63 68 6F 73  74 2E 65 78 65 0D 0A 46   2\svchost.exe..F
 00b0   69 6C 65 56 65 72 73 69  6F 6E 3A 20 31 30 2E 30   ileVersion: 10.0
 00c0   2E 31 37 31 33 34 2E 31  20 28 57 69 6E 42 75 69   .17134.1 (WinBui
 00d0   6C 64 2E 31 36 30 31 30  31 2E 30 38 30 30 29 0D   ld.160101.0800).
 00e0   0A 44 65 73 63 72 69 70  74 69 6F 6E 3A 20 48 6F   .Description: Ho
 00f0   73 74 20 50 72 6F 63 65  73 73 20 66 6F 72 20 57   st Process for W
 0100   69 6E 64 6F 77 73 20 53  65 72 76 69 63 65 73 0D   indows Services.
 0110   0A 50 72 6F 64 75 63 74  3A 20 4D 69 63 72 6F 73   .Product: Micros
 0120   6F 66 74 AE 20 57 69 6E  64 6F 77 73 AE 20 4F 70   oft. Windows. Op
 0130   65 72 61 74 69 6E 67 20  53 79 73 74 65 6D 0D 0A   erating System..
 0140   43 6F 6D 70 61 6E 79 3A  20 4D 69 63 72 6F 73 6F   Company: Microso
 0150   66 74 20 43 6F 72 70 6F  72 61 74 69 6F 6E 0D 0A   ft Corporation..
 0160   43 6F 6D 6D 61 6E 64 4C  69 6E 65 3A 20 43 3A 5C   CommandLine: C:\
 0170   57 49 4E 44 4F 57 53 5C  73 79 73 74 65 6D 33 32   WINDOWS\system32
 0180   5C 73 76 63 68 6F 73 74  2E 65 78 65 20 2D 6B 20   \svchost.exe -k
 0190   4C 6F 63 61 6C 53 79 73  74 65 6D 4E 65 74 77 6F   LocalSystemNetwo
 01a0   72 6B 52 65 73 74 72 69  63 74 65 64 20 2D 70 20   rkRestricted -p
 01b0   2D 73 20 4E 67 63 53 76  63 0D 0A 43 75 72 72 65   -s NgcSvc..Curre
 01c0   6E 74 44 69 72 65 63 74  6F 72 79 3A 20 43 3A 5C   ntDirectory: C:\
 01d0   57 49 4E 44 4F 57 53 5C  73 79 73 74 65 6D 33 32   WINDOWS\system32
 01e0   5C 0D 0A 55 73 65 72 3A  20 4E 54 20 41 55 54 48   \..User: NT AUTH
 01f0   4F 52 49 54 59 5C 53 59  53 54 45 4D 0D 0A 4C 6F   ORITY\SYSTEM..Lo
 0200   67 6F 6E 47 75 69 64 3A  20 7B 42 46 41 31 30 33   gonGuid: {BFA103
 0210   30 31 2D 43 31 43 44 2D  35 43 31 37 2D 30 30 30   01-C1CD-5C17-000
 0220   30 2D 30 30 32 30 45 37  30 33 30 30 30 30 7D 0D   0-0020E7030000}.
 0230   0A 4C 6F 67 6F 6E 49 64  3A 20 30 78 33 45 37 0D   .LogonId: 0x3E7.
 0240   0A 54 65 72 6D 69 6E 61  6C 53 65 73 73 69 6F 6E   .TerminalSession
 0250   49 64 3A 20 30 0D 0A 49  6E 74 65 67 72 69 74 79   Id: 0..Integrity
 0260   4C 65 76 65 6C 3A 20 53  79 73 74 65 6D 0D 0A 48   Level: System..H
 0270   61 73 68 65 73 3A 20 4D  44 35 3D 33 32 35 36 39   ashes: MD5=32569
 0280   45 34 30 33 32 37 39 42  33 46 44 32 45 44 42 37   E403279B3FD2EDB7
 0290   45 42 44 30 33 36 32 37  33 46 41 2C 53 48 41 32   EBD036273FA,SHA2
 02a0   35 36 3D 43 39 41 32 38  44 43 38 30 30 34 43 33   56=C9A28DC8004C3
 02b0   45 30 34 33 43 42 46 38  45 33 41 31 39 34 46 44   E043CBF8E3A194FD
 02c0   41 32 42 37 35 36 43 45  39 30 37 34 30 44 46 32   A2B756CE90740DF2
 02d0   31 37 35 34 38 38 33 33  37 32 38 31 42 34 38 35   175488337281B485
 02e0   46 36 39 0D 0A 50 61 72  65 6E 74 50 72 6F 63 65   F69..ParentProce
 02f0   73 73 47 75 69 64 3A 20  7B 42 46 41 31 30 33 30   ssGuid: {BFA1030
 0300   31 2D 43 31 43 44 2D 35  43 31 37 2D 30 30 30 30   1-C1CD-5C17-0000
 0310   2D 30 30 31 30 45 36 33  45 30 31 30 30 7D 0D 0A   -0010E63E0100}..
 0320   50 61 72 65 6E 74 50 72  6F 63 65 73 73 49 64 3A   ParentProcessId:
 0330   20 38 32 34 0D 0A 50 61  72 65 6E 74 49 6D 61 67    824..ParentImag
 0340   65 3A 20 43 3A 5C 57 69  6E 64 6F 77 73 5C 53 79   e: C:\Windows\Sy
 0350   73 74 65 6D 33 32 5C 73  65 72 76 69 63 65 73 2E   stem32\services.
 0360   65 78 65 0D 0A 50 61 72  65 6E 74 43 6F 6D 6D 61   exe..ParentComma
 0370   6E 64 4C 69 6E 65 3A 20  43 3A 5C 57 49 4E 44 4F   ndLine: C:\WINDO
 0380   57 53 5C 73 79 73 74 65  6D 33 32 5C 73 65 72 76   WS\system32\serv
 0390   69 63 65 73 2E 65 78 65  00 00 50 72 6F 63 65 73   ices.exe..Proces
 03a0   73 20 43 72 65 61 74 65  20 28 72 75 6C 65 3A 20   s Create (rule:
 03b0   50 72 6F 63 65 73 73 43  72 65 61 74 65 29 00 15   ProcessCreate)..
 03c0   00 00 00 C6 04 00 00 C8  04 00 00 E1 04 00 00 09   ................
 03d0   05 00 00 10 05 00 00 31  05 00 00 56 05 00 00 79   .......1...V...y
 03e0   05 00 00 9F 05 00 00 B6  05 00 00 04 06 00 00 1A   ................
 03f0   06 00 00 2F 06 00 00 57  06 00 00 5E 06 00 00 61   .../...W...^...a
 0400   06 00 00 69 06 00 00 D7  06 00 00 FF 06 00 00 04   ...i............
 0410   07 00 00 26 07 00 00 00  00 00 32 30 31 38 2D 31   ...&......2018-1
 0420   32 2D 31 39 20 30 36 3A  34 33 3A 32 30 2E 38 36   2-19 06:43:20.86
 0430   39 00 00 7B 62 66 61 31  30 33 30 31 2D 65 38 38   9..{bfa10301-e88
 0440   38 2D 35 63 31 39 2D 30  30 30 30 2D 30 30 31 30   8-5c19-0000-0010
 0450   65 34 31 63 36 34 30 31  7D 00 00 31 30 36 30 38   e41c6401}..10608
 0460   00 00 43 3A 5C 57 69 6E  64 6F 77 73 5C 53 79 73   ..C:\Windows\Sys
 0470   74 65 6D 33 32 5C 73 76  63 68 6F 73 74 2E 65 78   tem32\svchost.ex
 0480   65 00 00 31 30 2E 30 2E  31 37 31 33 34 2E 31 20   e..10.0.17134.1
 0490   28 57 69 6E 42 75 69 6C  64 2E 31 36 30 31 30 31   (WinBuild.160101
 04a0   2E 30 38 30 30 29 00 00  48 6F 73 74 20 50 72 6F   .0800)..Host Pro
 04b0   63 65 73 73 20 66 6F 72  20 57 69 6E 64 6F 77 73   cess for Windows
 04c0   20 53 65 72 76 69 63 65  73 00 00 4D 69 63 72 6F    Services..Micro
 04d0   73 6F 66 74 AE 20 57 69  6E 64 6F 77 73 AE 20 4F   soft. Windows. O
 04e0   70 65 72 61 74 69 6E 67  20 53 79 73 74 65 6D 00   perating System.
 04f0   00 4D 69 63 72 6F 73 6F  66 74 20 43 6F 72 70 6F   .Microsoft Corpo
 0500   72 61 74 69 6F 6E 00 00  43 3A 5C 57 49 4E 44 4F   ration..C:\WINDO
 0510   57 53 5C 73 79 73 74 65  6D 33 32 5C 73 76 63 68   WS\system32\svch
 0520   6F 73 74 2E 65 78 65 20  2D 6B 20 4C 6F 63 61 6C   ost.exe -k Local
 0530   53 79 73 74 65 6D 4E 65  74 77 6F 72 6B 52 65 73   SystemNetworkRes
 0540   74 72 69 63 74 65 64 20  2D 70 20 2D 73 20 4E 67   tricted -p -s Ng
 0550   63 53 76 63 00 00 43 3A  5C 57 49 4E 44 4F 57 53   cSvc..C:\WINDOWS
 0560   5C 73 79 73 74 65 6D 33  32 5C 00 00 4E 54 20 41   \system32\..NT A
 0570   55 54 48 4F 52 49 54 59  5C 53 59 53 54 45 4D 00   UTHORITY\SYSTEM.
 0580   00 7B 62 66 61 31 30 33  30 31 2D 63 31 63 64 2D   .{bfa10301-c1cd-
 0590   35 63 31 37 2D 30 30 30  30 2D 30 30 32 30 65 37   5c17-0000-0020e7
 05a0   30 33 30 30 30 30 7D 00  00 30 78 33 65 37 00 00   030000}..0x3e7..
 05b0   30 00 00 53 79 73 74 65  6D 00 00 4D 44 35 3D 33   0..System..MD5=3
 05c0   32 35 36 39 45 34 30 33  32 37 39 42 33 46 44 32   2569E403279B3FD2
 05d0   45 44 42 37 45 42 44 30  33 36 32 37 33 46 41 2C   EDB7EBD036273FA,
 05e0   53 48 41 32 35 36 3D 43  39 41 32 38 44 43 38 30   SHA256=C9A28DC80
 05f0   30 34 43 33 45 30 34 33  43 42 46 38 45 33 41 31   04C3E043CBF8E3A1
 0600   39 34 46 44 41 32 42 37  35 36 43 45 39 30 37 34   94FDA2B756CE9074
 0610   30 44 46 32 31 37 35 34  38 38 33 33 37 32 38 31   0DF2175488337281
 0620   42 34 38 35 46 36 39 00  00 7B 62 66 61 31 30 33   B485F69..{bfa103
 0630   30 31 2D 63 31 63 64 2D  35 63 31 37 2D 30 30 30   01-c1cd-5c17-000
 0640   30 2D 30 30 31 30 65 36  33 65 30 31 30 30 7D 00   0-0010e63e0100}.
 0650   00 38 32 34 00 00 43 3A  5C 57 69 6E 64 6F 77 73   .824..C:\Windows
 0660   5C 53 79 73 74 65 6D 33  32 5C 73 65 72 76 69 63   \System32\servic
 0670   65 73 2E 65 78 65 00 00  43 3A 5C 57 49 4E 44 4F   es.exe..C:\WINDO
 0680   57 53 5C 73 79 73 74 65  6D 33 32 5C 73 65 72 76   WS\system32\serv
 0690   69 63 65 73 2E 65 78 65  00                        ices.exe.
Traceback (most recent call last):
  File "c:\program files\python36\Lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'WMIQUERY' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/wmiquery.py", line 79, in printReply
    pEnum = iEnum.Next(0xffffffff,1)[0]
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2857, in Next
    oxid=self.get_oxid(), target=self.get_target()), self.__iWbemServices))
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2300, in __init__
    self.parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 2339, in parseObject
    self.encodingUnit['ObjectBlock'].parseObject()
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 960, in parseObject
    self.ctCurrent = self.parseClass(ctCurrent, self['InstanceType'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 948, in parseClass
    classDict['values'] = cInstance.getValues(classDict['properties'])
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 814, in getValues
    value = ENCODED_VALUE.getValue( properties[key]['type'], itemValue, heap)
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 361, in getValue
    value = ENCODED_STRING(heapData)['Character']
  File "C:\collector\venv\lib\site-packages\impacket\dcerpc\v5\dcom\wmi.py", line 153, in __init__
    self.fromString(data)
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "C:\collector\venv\lib\site-packages\impacket\structure.py", line 358, in unpack
    return data[:-1].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 290: ordinal not in range(128)
[-] 'ascii' codec can't decode byte 0xae in position 290: ordinal not in range(128)
```

**Comment by asolino** [comment]
Thanks for the info @ofmendi 

Please give it another try after `git pull`ing the latest commit.

**Comment by ofmendi** [comment]
Thank you. Problem has solved.
