### ISSUE TITLE
runall.sh does not detect failures in lower-level runalltestcases.sh

### ISSUE THREAD

**Issue by infinnovation-dev** [SecureAuthCorp/impacket#539]
I ran runall.sh on a codebase where a unit test in a subdirectory was known to fail.  The failure was not detected, giving the false impression that all tests has succeeded.
```sh
$ NO_REMOTE=y ./runall.sh
...
F
 ======================================================================
 FAIL: test_str (__main__.DNSTests)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
 File "test_dns.py", line 28, in test_str
 "DNS RESPONSEn"
 File "test_dns.py", line 8, in chk
 self.assertEqual(str(DNS(b)),t)
 AssertionError: ...
...
 Ran 1 test in 0.001s
 
 FAILED (failures=1)
 ...
NO ERRORS found, congrats!
```

runall.sh tests for overall failure by grepping for ERROR in $OUTPUTFILE, but runalltestcases.sh scripts do not output this string.

**Comment by asolino** [comment]
Great catch here @infinnovation-dev
