### ISSUE TITLE
running wmiexec.py in celery

### ISSUE THREAD

**Issue by Kazatel** [SecureAuthCorp/impacket#574]
Hi I have created my own class where I imported class wmiexec to get wmi call based my needs

        command = 'powershell.exe  e:\CORE\copy_7mtt_projects.ps1 '
        command = command + encrypted
        execute = wmiexec.WMIEXEC(command=str(command),
                                  username=self.username,
                                  password=self.password,
                                  share='wmiexe_share',
                                  noOutput=False)
        win_server_domain = self.winServers[winServer]
        execute.run(win_server_domain)

I am able to run script from shell, however when I import my class and run as celery task, my worker die on wmiexec execute_remote function

[2019-02-06 14:06:09,797: WARNING/ForkPoolWorker-8] powershell.exe  e:\CORE\copy_7mtt_projects.ps1 xxxxxx
[2019-02-06 14:06:09,797: WARNING/ForkPoolWorker-8] server.domain.xxx.xxx
[2019-02-06 14:06:10,158: INFO/ForkPoolWorker-8] SMBv3.0 dialect used
[2019-02-06 14:06:11,619: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2019-02-06 14:06:11,619: WARNING/ForkPoolWorker-8] File "/opt/app/data/myname/project/bin/wmiexec.py", line 90, in run
[2019-02-06 14:06:11,619: WARNING/ForkPoolWorker-8] self.shell = RemoteShell(self.__share, win32Process, smbConnection)
[2019-02-06 14:06:11,619: WARNING/ForkPoolWorker-8] File "/opt/app/data/myname/project/bin/wmiexec.py", line 126, in __init__
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] self.do_cd('\\')
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] File "/opt/app/data/myname/project/bin/wmiexec.py", line 201, in do_cd
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] self.execute_remote('cd ' + s)
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] File "/opt/app/data/myname/project/bin/wmiexec.py", line 266, in execute_remote
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] self.__win32Process.Create(command.decode(sys.stdin.encoding), self.__pwd, None)
[2019-02-06 14:06:11,620: WARNING/ForkPoolWorker-8] TypeError: decode() argument 1 must be string, not None
[2019-02-06 14:06:11,620: ERROR/ForkPoolWorker-8] decode() argument 1 must be string, not None
[2019-02-06 14:06:11,715: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:94486 exited with 'exitcode 1'
[2019-02-06 14:06:11,752: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 1.',)
Traceback (most recent call last):
  File "/opt/app/data/myname/project/lib/python2.7/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 1.

**Comment by Kazatel** [comment]
We found that Impacked module wmiexec can't get output from sys.stdin.encoding insice celery task.
we hard-coded and replaced every line with string

Example:
        # self.__win32Process.Create(command.decode(sys.stdin.encoding), self.__pwd, None)
        self.__win32Process.Create(command.decode('UTF-8'), self.__pwd, None)

Good luck guys :)
