### ISSUE TITLE
python3 + smbserver

### ISSUE THREAD

**Issue by mubix** [SecureAuthCorp/impacket#617]
```
python3 ./smbserver.py -smb2support TMP /tmp
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
Traceback (most recent call last):
  File "./smbserver.py", line 66, in <module>
    server.addShare(options.shareName.upper(), options.sharePath, comment)
  File "/usr/local/lib/python3.6/dist-packages/impacket-0.9.20.dev0-py3.6.egg/impacket/smbserver.py", line 4654, in addShare
  File "/usr/lib/python3.6/configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

**Comment by asolino** [comment]
Hey @mubix thanks for the report.

Please `git pull` and test again.

**Comment by asolino** [comment]
No answer.. closing. Should be fixed.
