### ISSUE TITLE
SMB + Python 3.6: str vs bytes error

### ISSUE THREAD

**Issue by HashFail** [SecureAuthCorp/impacket#631]
On the current head (eaca9beeae8c882209115e00408ba65b3861fd51), SMB login requests with "word count" other than 12 fail:

```python
import os
from threading import Thread
from impacket import smbserver
from impacket.smbconnection import SMBConnection

# declare shares        
share = None

#### start Samba Share
testPort = 8080         
server = smbserver.SimpleSMBServer(listenAddress="0.0.0.0", listenPort=testPort)
server.addShare(sharePath=os.getcwd(), shareName='Test', shareComment='Test')

server_thread = Thread(target=server.start)
server_thread.start()

#### start Samba client 
remoteName = "localhost"
remoteIP = "localhost"
remotePort = testPort
   
# start smb client connection
smbClient = SMBConnection(remoteName, remoteIP, sess_port=testPort)
raw = b'\xffSMBs\x00\x00\x00\x00\x18\x01H\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
      b'\xff\xff\x06\x18\x00\x00\x00\x00\r\xff\x00\x00\x00X@\x01\x00\x00\x00\x00\x00\x00'\
      b'\x00\x18\x00\x18\x00\x00\x00\x00\x00\xd8\xc0\x00\x00p\x00\xee\xfa\xbct&!\xa8\x83'\
      b'\xae\xc4\xb2N\x0f\x7f\xbf\x05\xe1}\xc2\x88\n\xbe\x07\xcc\xee\xfa\xbct&!\xa8\x83'\
      b'\xae\xc4\xb2N\x0f\x7f\xbf\x05\xe1}\xc2\x88\n\xbe\x07\xccadministrator\x00\x00Lin'\
      b'ux version 2.6.28.9\x00CIFS VFS Client for Linux\x00'
ret = smbClient._SMBConnection._sess.send_packet(raw)
```

This isn't a super elegant example. I'm sending a raw command because I don't really know the SMB protocol and couldn't easily figure out how to hit this case using the client's API. The command is one sent by a SuperMicro motherboard when attempting to use a samba share as a virtual image. 

When you run the above, you will see

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/impacket/smbserver.py", line 145, in outputToJohnFormat
    username.decode('utf-16le'), domain.decode('utf-16le'), hexlify(lmresponse).decode('latin-1'),
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/impacket/smbserver.py", line 160, in outputToJohnFormat
    username.decode('utf-16le'), domain.decode('utf-16le'), hexlify(lmresponse).decode('latin-1'), hexlify(ntresponse).decode('latin-1'),
AttributeError: 'str' object has no attribute 'decode'
```

The fix is

```diff
diff --git a/impacket/smbserver.py b/impacket/smbserver.py
index 8083e82f..d15e562b 100644
--- a/impacket/smbserver.py
+++ b/impacket/smbserver.py
@@ -2496,7 +2496,10 @@ class SMBCommands:
             smbServer.log('User %s\\%s authenticated successfully (basic)' % (sessionSetupData['Prim
aryDomain'], sessionSetupData['Account']))
             try:
                 jtr_dump_path = smbServer.getJTRdumpPath()
-                ntlm_hash_data = outputToJohnFormat( b'', sessionSetupData['Account'], sessionSetupD
ata['PrimaryDomain'], sessionSetupData['AnsiPwd'], sessionSetupData['UnicodePwd'] )
+                ntlm_hash_data = outputToJohnFormat( b'', sessionSetupData['Account'].encode('utf-16
le'),
+                                                          sessionSetupData['PrimaryDomain'].encode('
utf-16le'),
+                                                          sessionSetupData['AnsiPwd'].encode('utf-16
le'),
+                                                          sessionSetupData['UnicodePwd'].encode('utf
-16le') )
                 smbServer.log(ntlm_hash_data['hash_string'])
                 if jtr_dump_path is not '':
                     writeJohnOutputToFile(ntlm_hash_data['hash_string'], ntlm_hash_data['hash_version'], jtr_dump_path)
```

**Comment by asolino** [comment]
Hey @HashFail 

Give a try at the last commit and let me know. Thanks for the report.
