### ISSUE TITLE
TypeError: decoding unicode is not supported

### ISSUE THREAD

**Issue by 5h1v3ndra** [SecureAuthCorp/impacket#632]
GetADUsers.py -all -dc-ip **** domain/user -debug

output:
Name                  Email                           PasswordLastSet      LastLogon           
--------------------  ------------------------------  -------------------  -------------------
[+] Search Filter=(&(sAMAccountName=*)(objectCategory=user)(sAMAccountName:=test))
Traceback (most recent call last):
  File "/usr/local/bin/GetADUsers.py", line 242, in <module>
    executer.run()
  File "/usr/local/bin/GetADUsers.py", line 172, in run
    sizeLimit=0, searchControls = [sc], perRecordCallback=self.processRecord)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 367, in search
    searchRequest['filter'] = self._parseFilter(searchFilter)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 471, in _parseFilter
    filterList = list(reversed(u(filterStr)))
  File "/usr/lib/python2.7/dist-packages/six.py", line 653, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
decoding Unicode is not supported

**Comment by asolino** [comment]
Hey @5h1v3ndra  What OS are you running this from?

**Comment by 5h1v3ndra** [comment]
Kali linux latest version, I’m not at desk to check revision but I did have the env setup on Monday.

**Comment by DameDrewby** [comment]
I had the same issue - as a workaround I removed 
`"unicode_escape"`
File "/usr/lib/python2.7/dist-packages/six.py", line 653
To get it working.
