### ISSUE TITLE
KeyError exception in smb.py

### ISSUE THREAD

**Issue by idangur** [SecureAuthCorp/impacket#658]
Hey I have found a bug that crashed my code with an unexpected error code in the smb.py file of the project exception catching.

here is the traceback of the error - 

> ERROR:SMB critical failure - 385875968
Traceback (most recent call last):
  File "/_/asyncScripts2.0/Smb.py", line 158, in smb2_request
    smb_conn = smb_connection.SMBConnection(host, host, sess_port=PORT, myName=LOCAL_MACHINE, preferredDialect=None, timeout=TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/impacket/smbconnection.py", line 77, in __init__
    self.negotiateSession(preferredDialect)
  File "/usr/local/lib/python3.7/site-packages/impacket/smbconnection.py", line 124, in negotiateSession
    negPacket=packet)
  File "/usr/local/lib/python3.7/site-packages/impacket/smb.py", line 2436, in __init__
    self.neg_session(negPacket = negPacket)
  File "/usr/local/lib/python3.7/site-packages/impacket/smb.py", line 2646, in neg_session
    return parsePacket( NewSMBPacket( data = negPacket))
  File "/usr/local/lib/python3.7/site-packages/impacket/smb.py", line 2597, in parsePacket
    if smb.isValidAnswer(SMB.SMB_COM_NEGOTIATE):
  File "/usr/local/lib/python3.7/site-packages/impacket/smb.py", line 718, in isValidAnswer
    raise SessionError("SMB Library Error", self['ErrorClass'] + (self['_reserved'] << 8), self['ErrorCode'], self['Flags2'] & SMB.FLAGS2_NT_STATUS, self)
impacket.smb.SessionError: <unprintable SessionError object>

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/_/asyncScripts2.0/Smb.py", line 259, in get_os
    smb2_name, smb2_domain, smb2_os, smb2_device = smb2_request(host, smb_logger)
  File "/_/asyncScripts2.0/Smb.py", line 206, in smb2_request
    smb_logger.debug(f'SMB-2::{host}::Unable to identify:{e}')
  File "/usr/local/lib/python3.7/site-packages/impacket/smb.py", line 521, in __str__
    return 'SMB SessionError: %s(%s)' % nt_errors.ERROR_MESSAGES[self.error_code]
KeyError: 385875968

Would be glad to know if it is an issue with my code or the project's.

**Comment by asolino** [comment]
Hey @idangur 

You're mixing SMBv2 code with SMBv1 use inside the library. Can't help you much w/o watching your code. 
Closing.
