### ISSUE TITLE
ntlmrelayx.py missing python module 'readline' on windows

### ISSUE THREAD

**Issue by antonioCoco** [SecureAuthCorp/impacket#688]
Just tried to install and use ntlmrelayx on windows.
I have Python 2.7.16 on my win10 and after running "pip install ." everything installed correctly.
But when i run ntlmrelayx.py i have the following error:

```
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
Traceback (most recent call last):
  File "ntlmrelayx.py", line 309, in <module>
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
  File "C:\Python27\lib\site-packages\impacket\examples\ntlmrelayx\attacks\__init__.py", line 57, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "C:\Python27\lib\site-packages\impacket\examples\ntlmrelayx\attacks\smbattack.py", line 24, in <module>
    from impacket.examples.smbclient import MiniImpacketShell
  File "C:\Python27\lib\site-packages\impacket\examples\smbclient.py", line 37, in <module>
    import readline
ImportError: No module named readline
```

Anyway i managed to solve this issue by running:

```
pip install pyreadline
```

**Comment by asolino** [comment]
Thanks for the note @antonioCoco. Closing.
