### ISSUE TITLE
Decoding error when using an LDAP filter with non-ASCII characters

### ISSUE THREAD

**Issue by the-useless-one** [SecureAuthCorp/impacket#692]
Hi all,

I get a Python error when I try to create an LDAP filter which contains non-ASCII characters. For example, with an LDAP filter of `(&(objectCategory=organizationalUnit)(name=Service Réseaux*))`, I get :

```
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/yme/tools/pywerview/pywerview/cli/main.py", line 458, in main
    results = args.func(**parsed_args)
  File "/home/yme/tools/pywerview/pywerview/cli/helpers.py", line 99, in get_netou
    full_data=full_data)
  File "/home/yme/tools/pywerview/pywerview/requester.py", line 142, in wrapper
    return f(*args, **kwargs)
  File "/home/yme/tools/pywerview/pywerview/functions/net.py", line 282, in get_netou
    return self._ldap_search(ou_search_filter, adobj.OU, attributes=attributes)
  File "/home/yme/tools/pywerview/pywerview/requester.py", line 108, in _ldap_search
    attributes=attributes)
  File "/home/yme/.local/lib/python2.7/site-packages/impacket/ldap/ldap.py", line 366, in search
    searchRequest['filter'] = self._parseFilter(searchFilter)
  File "/home/yme/.local/lib/python2.7/site-packages/impacket/ldap/ldap.py", line 471, in _parseFilter
    filterStr = filterStr.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)
```

The error seems to be coming from [this line](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/ldap/ldap.py#L470), which tries to decode the LDAP filter, and fails. If i dirty-patch the line so that it stops decoding, I don't get an error anymore:

```python
def _parseFilter(self, filterStr):
    try:
        filterStr = filterStr # we stop the decoding process for now
    except AttributeError:
        pass
    filterList = list(reversed(filterStr))
    searchFilter = self._consumeCompositeFilter(filterList)
    if filterList:  # we have not consumed the whole filter string
        raise LDAPFilterSyntaxError("unexpected token: '%s'" % filterList[-1])
    return searchFilter
```

Now, with the same LDAP filter as before, I get the correct result:

```
distinguishedname: LDAP://OU=Service Réseaux d' Entreprise,DC=domain,DC=com
```

Is there any reason why the filter parsing function needs to decode the filter string? I'd be happy to issue a PR correcting the problem, something like:

```python
    try:
        filterStr = filterStr.decode()
    except AttributeError:
        pass
    except UnicodeDecodeError:
        pass
```

Let me know if you need more information.

Cheers,

Y

**Comment by the-useless-one** [comment]
Up @asolino :)

Any info on this problem?

**Comment by asolino** [comment]
Hey @the-useless-one 

Sorry for the delay. I'm not sure why that line is that way. Please issue a PR so I run the tests cases I have and go from there.

**Comment by gabrielg5** [comment]
Closing due to #1980. Reopen if needed.
Thanks!
