### ISSUE TITLE
--add-computer flag needed with --delegate-access

### ISSUE THREAD

**Issue by fsacer** [SecureAuthCorp/impacket#757]
### Configuration  
impacket version:  Impacket v0.9.21-dev
Python version:  python2/3
Target OS:  kali

### Debug Output With Command String  
Following the guide https://dirkjanm.io/worst-of-both-worlds-ntlm-relaying-and-kerberos-delegation/ and command `ntlmrelayx.py -t ldaps://icorp-dc.internal.corp -wh attacker-wpad --delegate-access` I got an error:

[*] Enumerating relayed user's privileges. This may take a while on large domains
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/impacket-0.9.21.dev0-py3.7.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 583, in run
    self.delegateAttack(self.config.escalateuser, self.username, domainDumper, self.config.sid)
  File "/usr/local/lib/python3.7/dist-packages/impacket-0.9.21.dev0-py3.7.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 197, in delegateAttack
    usersam = self.addComputer('CN=Computers,%s' % domainDumper.root, domainDumper)
  File "/usr/local/lib/python3.7/dist-packages/impacket-0.9.21.dev0-py3.7.egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 95, in addComputer
    newComputer = computerName if computerName.endswith('$') else computerName + '$'
AttributeError: 'NoneType' object has no attribute 'endswith'

By adding --add-computer flag the command worked `ntlmrelayx.py -t ldaps://icorp-dc.internal.corp  --delegate-access -wh attacker-wpad --add-computer`.

**Comment by asolino** [comment]
Fixed in https://github.com/SecureAuthCorp/impacket/pull/766
