### ISSUE TITLE
LDAPSearchError: Error in searchRequest -> referral: 0000202B

### ISSUE THREAD

**Issue by FuckAllWorld** [SecureAuthCorp/impacket#788]
python GetUserSPNs.py testlab/administrator -dc-ip 100.100.100.1 -debug

```
Traceback (most recent call last):
  File "GetUserSPNs.py", line 466, in <module>
    executer.run()
  File "GetUserSPNs.py", line 290, in run
    sizeLimit=999)
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.21.dev1+20200309.134159.0b46f19-py2.7.egg/impacket/ldap/ldap.py", line 384, in search
    answers=answers
LDAPSearchError: Error in searchRequest -> referral: 0000202B: RefErr: DSID-031007F3, data 0, 1 access points
	ref 1: 'testlab'

[-] Error in searchRequest -> referral: 0000202B: RefErr: DSID-031007F3, data 0, 1 access points
	ref 1: 'testlab'

```

**Comment by braimee** [comment]
Did you find a fix for this?

**Comment by 0xNoport** [comment]
Just change the syntax and try something different like ```GetUserSPNs.py -dc-ip IP -request domain.tld/user``` and then set the password interactively... this should work
