### ISSUE TITLE
smb3.1.1 does not seem to be supported

### ISSUE THREAD

**Issue by Lcys** [SecureAuthCorp/impacket#791]
### Configuration  
impacket version:  0.9.20
Python version:  3.7
Target OS:  Windows10 Build 18363

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/nmb.py", line 983, in non_polling_read
    received = self._sock.recv(bytes_left)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Lcy/PycharmProjects/quake_vscan/quake_vscan/protocols/smb2.py", line 64, in list_smb_dialects
    timeout=5, preferredDialect=dialect)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/smbconnection.py", line 77, in __init__
    self.negotiateSession(preferredDialect)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/smbconnection.py", line 128, in negotiateSession
    self._sess_port, self._timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/smb.py", line 2427, in __init__
    self.neg_session()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/smb.py", line 2642, in neg_session
    smb = self.recvSMB()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/smb.py", line 2506, in recvSMB
    r = self._sess.recv_packet(self.__timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/nmb.py", line 996, in __read
    data = self.read_function(4, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/impacket/nmb.py", line 990, in non_polling_read
    if ex[0] != errno.EINTR and ex[0] != errno.EAGAIN:
TypeError: 'ConnectionResetError' object is not subscriptable

Possible solution: https://github.com/nmap/nmap/blob/cd4da05e380367ffff204e919fdad51f26a899af/nselib/smb2.lua#L261

**Comment by asolino** [comment]
impacket `0.9.20` does not support `SMB 3.1.1`. Support for this protocol version was added in [this commit](https://github.com/SecureAuthCorp/impacket/commit/8afe4fe1044dc47faae25d2f3ad6e61217cc5898) and only available programatically.
