### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by kaizen-dry** [SecureAuthCorp/impacket#812]
**COMMAND:**impacket-smbserver Pleasework $(pwd) -smb2support -user root -password root
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/smbserver.py", line 64, in <module>
    server = smbserver.SimpleSMBServer(listenAddress=options.interface_address, listenPort=int(options.port))
  File "/usr/lib/python3/dist-packages/impacket/smbserver.py", line 4621, in __init__
    self.__server = SMBSERVER((listenAddress,listenPort), config_parser = self.__smbConfig)
  File "/usr/lib/python3/dist-packages/impacket/smbserver.py", line 3747, in __init__
    socketserver.TCPServer.__init__(self, server_address, handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by exploide** [comment]
Probably something is already listening on port 445. Check with `netstat -tlpen`.

**Comment by kaizen-dry** [comment]
> Probably something is already listening on port 445. Check with `netstat -tlpen`.

Thank you very much ! It worked !

**Comment by exploide** [comment]
Great. Please do the package maintainer a favour and close this issue.
