### ISSUE TITLE
finddelegations.py cannot connect to DC

### ISSUE THREAD

**Issue by basketas** [SecureAuthCorp/impacket#815]
### Configuration  
impacket version:  0.9.21-dev
Python version:  3.7.7
Target OS:  Windows Server 2016

### Debug Output With Command String  
i.e.  
```
finddelegation.py -debug lab/sale:sale@192.168.23.10
Impacket v0.9.21.dev1 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\impacket
[+] Connecting to lab, port 389, SSL False
Traceback (most recent call last):
  File "C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\impacket\ldap\ldap.py", line 107, in __init__
    af, socktype, proto, _, sa = socket.getaddrinfo(targetHost, self._dstPort, 0, socket.SOCK_STREAM)[0]
  File "C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sale\appdata\local\programs\python\python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\EGG-INFO\scripts\findDelegation.py", line 297, in <module>
    executer.run()
  File "c:\users\sale\appdata\local\programs\python\python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\EGG-INFO\scripts\findDelegation.py", line 110, in run
    ldapConnection = ldap.LDAPConnection('ldap://%s' % target, self.baseDN, self.__kdcHost)
  File "C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\impacket\ldap\ldap.py", line 110, in __init__
    raise socket.error('Connection error (%s:%d)' % (targetHost, 88), e)
OSError: [Errno Connection error (lab:88)] [Errno 11001] getaddrinfo failed
[-] [Errno Connection error (lab:88)] [Errno 11001] getaddrinfo failed
```

```
finddelegation.py -debug lab.local/sale:sale@192.168.23.10
Impacket v0.9.21.dev1 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\impacket
[+] Connecting to lab.local, port 389, SSL False
Traceback (most recent call last):
  File "c:\users\sale\appdata\local\programs\python\python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\EGG-INFO\scripts\findDelegation.py", line 297, in <module>
    executer.run()
  File "c:\users\sale\appdata\local\programs\python\python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\EGG-INFO\scripts\findDelegation.py", line 112, in run
    ldapConnection.login(self.__username, self.__password, self.__domain, self.__lmhash, self.__nthash)
  File "C:\Users\sale\AppData\Local\Programs\Python\Python37\lib\site-packages\impacket-0.9.21.dev1-py3.7.egg\impacket\ldap\ldap.py", line 343, in login
    response['bindResponse']['diagnosticMessage'])
impacket.ldap.ldap.LDAPSessionError: Error in bindRequest -> invalidCredentials: 8009030C: LdapErr: DSID-0C0906C1, comment: AcceptSecurityContext error, data 52e, v3839
[-] Error in bindRequest -> invalidCredentials: 8009030C: LdapErr: DSID-0C0906C1, comment: AcceptSecurityContext error, data 52e, v3839
```

### Additional context  
I can't connect to LDAP on DC(Server 2016)... I am trying with the Domain Admin credentials(username is same as password btw).
Tried with Python 3.7 and 2.7, from both Linux and Windows.. With both "pip install impacket" and manual download of the latest impacket version from github..

Could it be because the domain contains ".local" ?

**Comment by 0xdeaddood** [comment]
Hi @basketas!  
You are running the script detailing the IP address of the Domain Controller. You have to specify the target as follow: `findDelegation.py domain/username[:password]`. For this reason you are getting an `invalidCredentials` error in the second example.

Try running the script without the IP and let me know if works.

**Comment by basketas** [comment]
OK, so using FQDN and removing the IP address worked:

```
finddelegation.py -debug lab.local/sale:sale
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: c:\program files\python38\lib\site-packages\impacket
[+] Connecting to lab.local, port 389, SSL False
[+] Total of records returned 4
AccountName     AccountType  DelegationType  DelegationRightsTo
--------------  -----------  --------------  ------------------
WIN10PRO-64EN$  Computer     Unconstrained   N/A
```

However, `finddelegation.py` -debug lab/sale:sale' gave out error.. 

```
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: c:\program files\python38\lib\site-packages\impacket
[+] Connecting to lab, port 389, SSL False
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\impacket\ldap\ldap.py", line 107, in __init__
    af, socktype, proto, _, sa = socket.getaddrinfo(targetHost, self._dstPort, 0, socket.SOCK_STREAM)[0]
  File "c:\program files\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by 0xdeaddood** [comment]
Hey @basketas, this script needs to have the FQDN specified in the target. It's necessary in order to establish the LDAP connection.

**Comment by asolino** [comment]
Good to know it is working. Thanks for the clarifications @0xdeaddood. Closing
