### ISSUE TITLE
getMachineName in GetNPUsers/GetADUsers/GetUserSPNs fails on Windows 2019/NTLM Auth Disabled

### ISSUE THREAD

**Issue by Meatballs1** [SecureAuthCorp/impacket#817]
### Configuration  
Target OS:  Windows 2019 - NTLM Auth Disabled
Version: 7e505892 - Fri March 27th

### Debug Output With Command String  

KRB5CCNAME=/tmp/krb5cc_0 python3 examples/GetUserSPNs.py -k -no-pass TEST.ORG/testuser -debug
```
SMB SessionError:STATUS_NOT_SUPPORTED
```
It appears the s.login('','') to do a basic connection fails. I've worked around this by hardcoding the machine name as the return value, but could maybe use a `--target` option. Using `dc-ip` and `target-domain` dont help.

**Comment by Meatballs1** [comment]
It was late, thinking about it was more likely that this failed because NTLM auth is completely disabled in the domain :)

**Comment by asolino** [comment]
Most probably NTLM disabled @Meatballs1. Closing. Reopen if  you find anything else.

**Comment by Meatballs1** [comment]
@asolino Yes I think it was because NTLM is disabled, but it prevents authenticating with Kerberos?

**Comment by asolino** [comment]
That shouldn't be the case, you specified `-k` to begin with. Hmm.. we should look at the traffic captured. Any chance to look at it and see where it's failing at?

**Comment by Meatballs1** [comment]
Full debug output:

```
~/impacket$ python3 examples/GetADUsers.py -k -no-pass MYSTERIO.ORG/wilson.fisk:password -debug
Impacket v0.9.21.dev1+20200325.171015.69fee03f - Copyright 2020 SecureAuth Corporation
 
[+] Impacket Library Installation Path: /usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket/smbconnection.py", line 271, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket/smb3.py", line 852, in login
    if ans.isValidAnswer(STATUS_MORE_PROCESSING_REQUIRED):
  File "/usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket/smb3structs.py", line 454, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_NOT_SUPPORTED(The request is not supported.)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "examples/GetADUsers.py", line 76, in getMachineName
    s.login('', '')
  File "/usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket/smbconnection.py", line 273, in login
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_NOT_SUPPORTED(The request is not supported.)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "examples/GetADUsers.py", line 246, in <module>
    executer.run()
  File "examples/GetADUsers.py", line 124, in run
    self.__target = self.getMachineName()
  File "examples/GetADUsers.py", line 79, in getMachineName
    raise Exception('Error while anonymous logging into %s' % self.__domain)
Exception: Error while anonymous logging into MYSTERIO.ORG
Error while anonymous logging into MYSTERIO.ORG
```

**Comment by Meatballs1** [comment]
[pcap.zip](https://github.com/SecureAuthCorp/impacket/files/4471971/pcap.zip)

**Comment by Meatballs1** [comment]
Workaround:
```
    def getMachineName(self):
        return "triangle.mysterio.org"
        if self.__kdcHost is not None:
            s = SMBConnection(self.__kdcHost, self.__kdcHost)
        else:
            s = SMBConnection(self.__domain, self.__domain)
        try:
            s.login('', '')
        except Exception:
            if s.getServerName() == '':
                raise Exception('Error while anonymous logging into %s' % self.__domain)
        else:
            s.logoff()
        return s.getServerName()
```

Output:
```
~/impacket$ python3 examples/GetADUsers.py -k -no-pass MYSTERIO.ORG/wilson.fisk:football -debug
Impacket v0.9.21.dev1+20200325.171015.69fee03f - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.6/dist-packages/impacket-0.9.21.dev1+20200325.171015.69fee03f-py3.6.egg/impacket
[+] Connecting to triangle.mysterio.org, port 389, SSL False
[+] Trying to connect to KDC at MYSTERIO.ORG
[+] Trying to connect to KDC at MYSTERIO.ORG
[+] Trying to connect to KDC at MYSTERIO.ORG
[*] Querying triangle.mysterio.org for information about domain.
Name                  Email                           PasswordLastSet      LastLogon           
--------------------  ------------------------------  -------------------  -------------------
[+] Search Filter=(&(sAMAccountName=*)(mail=*)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))
```

**Comment by asolino** [comment]
Right.. thanks for digging in @Meatballs1. We try to get the DC Server name using that trick (so it doesn't need to be specified by the user) but didn't count on NTLM to be disabled. Will review that code.

**Comment by Meatballs1** [comment]
It doesn't look like this was ever resolved. Can it be re-opened?

**Comment by rmaksimov** [comment]
This PR (#838) should fix the problem
