### ISSUE TITLE
Jinja2>2.10.1 distribution not found and is required by flask

### ISSUE THREAD

**Issue by chrismetz** [SecureAuthCorp/impacket#826]
### Configuration  
impacket version:  0.9.22
Python version:  2.7
Target OS:  Kali 2020.2

### Debug Output With Command String
Traceback (most recent call last):                                                                                                                                                                               
  File "/usr/local/bin/psexec.py", line 4, in <module>                                                                                                                                                           
    __import__('pkg_resources').run_script('impacket==0.9.22.dev1+20200327.103853.7e505892', 'psexec.py')                                                                                                        
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>                                                                                                                      
    @_call_aside                                                                                                                                                                                                 
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside                                                                                                                   
    f(*args, **kwargs)                                                                                                                                                                                           
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set                                                                                                
    working_set = WorkingSet._build_master()                                                                                                                                                                     
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master                                                                                                                  
    ws.require(__requires__)                                                                                                                                                                                     
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require                                                                                                                        
    needed = self.resolve(parse_requirements(requirements))                                                                                                                                                      
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve                                                                                                                        
    raise DistributionNotFound(req, requirers)                                                                                                                                                                   
pkg_resources.DistributionNotFound: The 'Jinja2>=2.10.1' distribution was not found and is required by flask

### Additional context  
installed python-pip-whl version 20.0.2-4 as python-pip not available in kali package repository
installed python3-pip
ran pip3 install . from git repo root directory and impacket installed correctly
when running psexec.py I get the above error

**Comment by mpgn** [comment]
You are using python2.7 but yet, you install all the package with pip3 ... Try installing with pip2 first.

**Comment by chrismetz** [comment]
which package contains pip2?
I have installed the packages as above however pip and pip2 return command not found in bash

**Comment by mpgn** [comment]
Plenty of solutions here =>

https://stackoverflow.com/questions/28050223/kali-linux-debian-cant-install-pip-py
