### ISSUE TITLE
'HTTPMessage' object has no attribute 'getheader'

### ISSUE THREAD

**Issue by mpgn** [SecureAuthCorp/impacket#836]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200424.150528.c44901d1
Python version:  3.8
Target OS:  Windows

### Debug Output With Command String  

```
sudo ntlmrelayx.py -smb2support -t smb://192.168.255.131  -debug

[*] HTTPD: Received connection from 192.168.255.135, attacking target smb://192.168.255.131
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 75, in handle_one_request
    http.server.SimpleHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 143, in do_PROPFIND
    if self.headers.getheader('Authorization') is None:
AttributeError: 'HTTPMessage' object has no attribute 'getheader'

```

### Additional context  

In python3, `getheader()` should be `get()`

Fix should be something like this for example with this code https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/servers/httprelayserver.py#L143

```diff
--- a/impacket/examples/ntlmrelayx/servers/httprelayserver.py
+++ b/impacket/examples/ntlmrelayx/servers/httprelayserver.py
@@ -140,11 +140,15 @@ class HTTPRelayServer(Thread):
 
             messageType = 0
-            if self.headers.getheader('Authorization') is None:
+            if hasattr(self.headers, 'getheader'):
+                header = self.headers.getheader('Authorization')
+            else:
+                header = self.headers.get('Authorization')
+            if header is None:
                 self.do_AUTHHEAD(message='NTLM')
                 pass
             else:
-                typeX = self.headers.getheader('Authorization')
+                typeX = header
                 try:
                     _, blob = typeX.split('NTLM')
                     token = base64.b64decode(blob.strip())
```

It's not very elegant but the only solution to keep python2 and python3 version.

There are multiple files that use `getheader()` so this is not just one file to patch. If you want PR, I will submit one.

**Comment by asolino** [comment]
Fixed in https://github.com/SecureAuthCorp/impacket/pull/858
