### ISSUE TITLE
ImportError: No module named server

### ISSUE THREAD

**Issue by samuelkneppel** [SecureAuthCorp/impacket#844]
OS Version:
```
vlgngrbrdmn@kali:~$ uname -a`
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
```

Install method:
`vlgngrbrdmn@kali:~$ sudo apt install crackmapexec`

Issue:
I receive the following error when I run `crackmapexec`:
```
vlgngrbrdmn@kali:~$ crackmapexec 
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==5.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-5.0.1.dev0-py2.7.egg/cme/crackmapexec.py", line 14, in <module>
    from cme.servers.http import CMEServer
  File "/usr/local/lib/python2.7/dist-packages/gevent-20.4.0-py2.7-linux-x86_64.egg/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/crackmapexec-5.0.1.dev0-py2.7.egg/cme/servers/http.py", line 1, in <module>
    import http.server
  File "/usr/local/lib/python2.7/dist-packages/gevent-20.4.0-py2.7-linux-x86_64.egg/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named server
```

Troubleshooting steps taken so far:

- Uninstalled via `apt`, rebooted, and installed via `apt` again
- Tried manually installing but ran into some issues with setting up `pipenv`; reverted changes

Has anyone seen this error before? Any help would be much appreciated!

**Comment by samuelkneppel** [comment]
Whoops, wrong project.
