### ISSUE TITLE
OpenSSL.SSL.Error: [('SSL routines', 'state_machine', 'internal error')]

### ISSUE THREAD

**Issue by francoataffarel** [SecureAuthCorp/impacket#866]
### Configuration  
impacket version:   Impacket v0.9.21
Python version:  3.8.3
Target OS:  sql server

### Debug Output With Command String  

Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Encryption required, switching to TLS
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/bin/mssqlclient.py", line 179, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
  File "/usr/local/lib/python3.8/dist-packages/impacket/tds.py", line 917, in login
    tls.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1638, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1378, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)

OpenSSL.SSL.Error: [('SSL routines', 'state_machine', 'internal error')]
[-] [('SSL routines', 'state_machine', 'internal error')]

**Comment by LeviPesin** [comment]
Also look into https://github.com/SecureAuthCorp/impacket/issues/856. I opened this issue on pyOpenSSL: https://github.com/pyca/pyopenssl/issues/916
