### ISSUE TITLE
[Python3 Migration] TypeError in ntlm.py

### ISSUE THREAD

**Issue by Si0uL** [SecureAuthCorp/impacket#900]
### Configuration 
impacket version:  0.9.21
Python version:  3.6.9
Target OS:  Ubuntu

### Debug Output With Command String
From custom script, after using:

```
from impacket.smbconnection import SMBConnection
frmo impacket.smb import SMB_DIALECT

smbconn = SMBConnection(ip, ip, preferedDialect=SMB_DIALECT)
smbconn.login('', '')
```

Stacktrace:
```
Traceback (most recent call last):
  File "xxx", line 55, in xxx
    smb.login('' , '')
  File "/home/auditor/.local/lib/python3.6/site-packages/impacket/smbconnection.py", line 269, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash, ntlmFallback)
  File "/home/auditor/.local/lib/python3.6/site-packages/impacket/smb.py", line 3427, in login
    self.login_extended(user, password, domain, lmhash, nthash, use_ntlmv2 = False)
  File "/home/auditor/.local/lib/python3.6/site-packages/impacket/smb.py", line 3331, in login_extended
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash, use_ntlmv2 = use_ntlmv2)
  File "/home/auditor/.local/lib/python3.6/site-packages/impacket/ntlm.py", line 656, in getNTLMSSPType3
    lmhash, nthash, use_ntlmv2)
  File "/home/auditor/.local/lib/python3.6/site-packages/impacket/ntlm.py", line 864, in KXKEY
    keyExchangeKey = hmac_md5(sessionBaseKey, serverChallenge + lmChallengeResponse[:8])
TypeError: can't concat str to bytes
```

This looks like a simple python3 migration problem, caused by change of `str` type to `bytes` (similar to #691). As it only happens after using `login` with empty credentials, it looks like an initialization problem.

Fix looks trivial in first approach, and would be to initialize `lmChallengeResponse` as an empty `bytes` object instead of `str`. See: 
https://github.com/SecureAuthCorp/impacket/blob/master/impacket/ntlm.py#L719
https://github.com/SecureAuthCorp/impacket/blob/master/impacket/ntlm.py#L932

**Comment by asolino** [comment]
I can't reproduce this @Si0uL . Please be sure you don't have an older library version installed that higher precedence than `0.9.21`.

One easy way to check that is, under your script:
```
from impacket import version
from impacket.smbconnection import SMBConnection
from impacket.smb import SMB_DIALECT

print (version.BANNER)
ip='<insert-your-ip>'

smbconn = SMBConnection(ip, ip, preferredDialect=SMB_DIALECT)
smbconn.login('', '')
print('All OK!')
print(smbconn)
```
and I'm getting:
```
# python test.py 
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

All OK!
<impacket.smbconnection.SMBConnection object at 0x1064cd208>
```

Reopen this issue if problem still persists.
