### ISSUE TITLE
secretsdump.py: 'LSA hashes extraction failed: can only concatenate str (not "bytes") to str'

### ISSUE THREAD

**Issue by corsch** [SecureAuthCorp/impacket#902]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200629.145357.5d4ad6cc
Python version:  Python 3.8.3
Target OS:  KALI 2020

### Debug Output With Command String  

secretsdump.py administrator@<TARGETIP> -hashes <LMHASH>:<NTHASH> -pwd-last-set -user-status -history -debug -ts
```
python3 /usr/share/doc/python3-impacket/examples/secretsdump.py administrator@<TARGETIP> -hashes <LMHASH>:<NTHASH> -pwd-last-set -user-status -history -debug -ts
Impacket v0.9.22.dev1+20200629.145357.5d4ad6cc - Copyright 2020 SecureAuth Corporation

[2020-07-13 07:45:36] [+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[2020-07-13 07:45:38] [+] Service RemoteRegistry is already running
[2020-07-13 07:45:39] [+] Retrieving class info for JD
[2020-07-13 07:45:41] [+] Retrieving class info for Skew1
[2020-07-13 07:45:42] [+] Retrieving class info for GBG
[2020-07-13 07:45:43] [+] Retrieving class info for Data
[2020-07-13 07:45:44] [*] Target system bootKey: <BOOTKEY>
[2020-07-13 07:45:44] [+] Checking NoLMHash Policy
[2020-07-13 07:45:45] [+] LMHashes are being stored
[2020-07-13 07:45:45] [+] Saving remote SAM database
[2020-07-13 07:45:48] [*] Dumping local SAM hashes (uid:rid:lmhash:nthash)
[2020-07-13 07:45:48] [+] Calculating HashedBootKey from SAM
[2020-07-13 07:46:02] [+] NewStyle hashes is: False
Administrator:500:<LMHASH>:<NTHASH>:::
[2020-07-13 07:46:41] [+] Saving remote SECURITY database
[2020-07-13 07:46:43] [*] Dumping cached domain logon information (domain/username:hash)
[2020-07-13 07:46:50] [+] Decrypting LSA Key
[2020-07-13 07:46:52] [+] PolEKList not found, trying PolSecretEncryptionKey
[2020-07-13 07:46:54] [+] Decrypting NL$KM
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/secretsdump.py", line 183, in dump
    self.__LSASecrets.dumpCachedHashes()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/secretsdump.py", line 1414, in dumpCachedHashes
    self.__getNLKMSecret()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/secretsdump.py", line 1376, in __getNLKMSecret
    self.__NKLMKey = self.__decryptSecret(self.__LSAKey, value[1])
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/secretsdump.py", line 1314, in __decryptSecret
    plainText += Crypt1.decrypt(cipherText)
TypeError: can only concatenate str (not "bytes") to str
[2020-07-13 07:46:58] [-] LSA hashes extraction failed: can only concatenate str (not "bytes") to str
[2020-07-13 07:46:59] [+] Exiting NTDSHashes.dump() because SAMR SessionError: code: 0xc00000df - STATUS_NO_SUCH_DOMAIN - The specified domain did not exist.
[2020-07-13 07:46:59] [*] Cleaning up...
```

**Comment by asolino** [comment]
Hey @corsch 

Can you `git pull` and retest please?

**Comment by corsch** [comment]
The "Target" is a Windows Server 2003

Impacket v0.9.22.dev1+20200713.100928.1e84ad60 - Copyright 2020 SecureAuth Corporation

[2020-07-13 15:19:22] [+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[2020-07-13 15:19:25] [+] Service RemoteRegistry is already running
[2020-07-13 15:19:26] [+] Retrieving class info for JD
[2020-07-13 15:19:27] [+] Retrieving class info for Skew1
[2020-07-13 15:19:28] [+] Retrieving class info for GBG
[2020-07-13 15:19:29] [+] Retrieving class info for Data
...
[2020-07-13 15:20:25] [+] Saving remote SECURITY database
[2020-07-13 15:20:28] [*] Dumping cached domain logon information (domain/username:hash)
[2020-07-13 15:20:35] [+] Decrypting LSA Key
[2020-07-13 15:20:36] [+] PolEKList not found, trying PolSecretEncryptionKey
[2020-07-13 15:20:38] [+] Decrypting NL$KM
[2020-07-13 15:20:42] [+] Looking into NL$1
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/secretsdump.py", line 183, in dump
    self.__LSASecrets.dumpCachedHashes()
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/secretsdump.py", line 1426, in dumpCachedHashes
    plainText = self.__decryptHash(self.__NKLMKey, record['EncryptedData'], record['IV'])
  File "/usr/local/lib/python3.8/dist-packages/impacket/examples/secretsdump.py", line 1325, in __decryptHash
    hmac_md5 = HMAC.new(key,iv,digestmod=hashlib.md5)
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/HMAC.py", line 213, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/HMAC.py", line 63, in __init__
    self.digest_size = digestmod.digest_size
AttributeError: 'builtin_function_or_method' object has no attribute 'digest_size'
[2020-07-13 15:20:49] [-] LSA hashes extraction failed: 'builtin_function_or_method' object has no attribute 'digest_size'
[2020-07-13 15:20:50] [+] Exiting NTDSHashes.dump() because SAMR SessionError: code: 0xc00000df - STATUS_NO_SUCH_DOMAIN - The specified domain did not exist.
[2020-07-13 15:20:50] [*] Cleaning up...

**Comment by asolino** [comment]
That is more related with your `pycryptodomex` installation @corsch (taka a look at the traceback). Just ran it against a Windows 2003 Server Enterprise SP0 and stuff is working fine. 

Please give it a try again inside a Python `virtualenv` to force a clean download and install of all the components.

**Comment by corsch** [comment]
Sorry for the delay. I'll test this afternoon with a virtualenv and give you an update.

**Comment by corsch** [comment]
I think I'll test on a new system, as the installation won't work in a virtual environment on my machine.

Building wheels for collected packages: impacket
  Building wheel for impacket (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/impacket-trunk/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-optgo1mx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-optgo1mx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mjp0f8tb
       cwd: /tmp/pip-req-build-optgo1mx/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for impacket
  Running setup.py clean for impacket
Failed to build impacket

**Comment by corsch** [comment]
I've tried in a virtual environment without luck:

(impacket-trunk) root@kali2020:/opt/sources/impacket/examples# python3 secretsdump.py administrator@<TARGET> -hashes <LMHASH:HTLMHASH> -debug
Impacket v0.9.22.dev1+20200713.100928.1e84ad60 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /opt/impacket-trunk/lib/python3.8/site-packages/impacket
[+] Service RemoteRegistry is already running
[+] Retrieving class info for JD
[+] Retrieving class info for Skew1
[+] Retrieving class info for GBG
[+] Retrieving class info for Data
[*] Target system bootKey: <BOOTKEY>
[+] Checking NoLMHash Policy
[+] LMHashes are being stored
[+] Saving remote SAM database
[*] Dumping local SAM hashes (uid:rid:lmhash:nthash)
[+] Calculating HashedBootKey from SAM
[+] NewStyle hashes is: False
Administrator:500:<LMHASH:HTLMHASH>:::
...
[+] Saving remote SECURITY database
[*] Dumping cached domain logon information (domain/username:hash)
[+] Decrypting LSA Key
[+] PolEKList not found, trying PolSecretEncryptionKey
[+] Decrypting NL$KM
[+] Looking into NL$1
Traceback (most recent call last):
  File "secretsdump.py", line 183, in dump
    self.__LSASecrets.dumpCachedHashes()
  File "/opt/impacket-trunk/lib/python3.8/site-packages/impacket/examples/secretsdump.py", line 1426, in dumpCachedHashes
    plainText = self.__decryptHash(self.__NKLMKey, record['EncryptedData'], record['IV'])
  File "/opt/impacket-trunk/lib/python3.8/site-packages/impacket/examples/secretsdump.py", line 1325, in __decryptHash
    hmac_md5 = HMAC.new(key,iv,digestmod=hashlib.md5)
  File "/opt/impacket-trunk/lib/python3.8/site-packages/Cryptodome/Hash/HMAC.py", line 213, in new
    return HMAC(key, msg, digestmod)
  File "/opt/impacket-trunk/lib/python3.8/site-packages/Cryptodome/Hash/HMAC.py", line 63, in __init__
    self.digest_size = digestmod.digest_size
AttributeError: 'builtin_function_or_method' object has no attribute 'digest_size'
[-] LSA hashes extraction failed: 'builtin_function_or_method' object has no attribute 'digest_size'
[+] Exiting NTDSHashes.dump() because SAMR SessionError: code: 0xc00000df - STATUS_NO_SUCH_DOMAIN - The specified domain did not exist.
[*] Cleaning up...
(impacket-trunk) root@kali2020:/opt/sources/impacket/examples#

**Comment by asolino** [comment]
Thanks for the feedback @corsch .

Is there any way you can test an older Python version? (say Python 3.6). Something tells me there's something going on with `pycryptodomex` and Python 3.8.

**Comment by corsch** [comment]
Sure, I'll have a look with Python 3.6

**Comment by asolino** [comment]
Give it a try @corsch after updating with the latest PR from @0xdeaddood please.

Reopen this issue if still not working.
