### ISSUE TITLE
DPAPI Decrypt MK using System and SAM hives

### ISSUE THREAD

**Issue by darkoperator** [SecureAuthCorp/impacket#908]
### Configuration  
impacket version:  0.9.22.dev1+20200713.100928.1e84ad60
Python version:  Python 3.8.2
Target OS:  Registry Hives from Windows 10 1903, Impacket Running on Ubuntu 20.04

### Debug Output With Command String  

```
carlos@ubuntu:~/Desktop/impacket/examples$ python2 ./dpapi.py masterkey -f ./9217d96e-b282-4f6a-b382-c41d938c4e81 -security /home/carlos/Desktop/SAM -system /home/carlos/Desktop/system
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[MASTERKEYFILE]
Version     :        2 (2)
Guid        : 9217d96e-b282-4f6a-b382-c41d938c4e81
Flags       :        0 (0)
Policy      :        0 (0)
MasterKeyLen: 00000088 (136)
BackupKeyLen: 00000068 (104)
CredHistLen : 00000000 (0)
DomainKeyLen: 00000174 (372)

[*] Target system bootKey: 0x251700480d3e5cdd6b92fc762a5f3187
[*] Dumping LSA Secrets
'NoneType' object has no attribute '__getitem__'
carlos@ubuntu:~/Desktop/impacket/examples$ python3 ./dpapi.py masterkey -f ./9217d96e-b282-4f6a-b382-c41d938c4e81 -security /home/carlos/Desktop/SAM -system /home/carlos/Desktop/system
Impacket v0.9.22.dev1+20200713.100928.1e84ad60 - Copyright 2020 SecureAuth Corporation

[MASTERKEYFILE]
Version     :        2 (2)
Guid        : 9217d96e-b282-4f6a-b382-c41d938c4e81
Flags       :        0 (0)
Policy      :        0 (0)
MasterKeyLen: 00000088 (136)
BackupKeyLen: 00000068 (104)
CredHistLen : 00000000 (0)
DomainKeyLen: 00000174 (372)

[*] Target system bootKey: 0x251700480d3e5cdd6b92fc762a5f3187
[*] Dumping LSA Secrets
'NoneType' object is not subscriptable

```

**Comment by darkoperator** [comment]
debug 
```
$ python3 ./dpapi.py -debug masterkey -f /home/carlos/Desktop/S-1-5-21-3150103098-694922503-2167627182-1618/9217d96e-b282-4f6a-b382-c41d938c4e81 -security /home/carlos/Desktop/SAM -system /home/carlos/Desktop/system 
Impacket v0.9.22.dev1+20200713.100928.1e84ad60 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200713.100928.1e84ad60-py3.8.egg/impacket
[MASTERKEYFILE]
Version     :        2 (2)
Guid        : 9217d96e-b282-4f6a-b382-c41d938c4e81
Flags       :        0 (0)
Policy      :        0 (0)
MasterKeyLen: 00000088 (136)
BackupKeyLen: 00000068 (104)
CredHistLen : 00000000 (0)
DomainKeyLen: 00000174 (372)

[+] Retrieving class info for JD
[+] Unknown type 0xb'6\x00'
[+] Retrieving class info for Skew1
[+] Unknown type 0xb'0\x00'
[+] Retrieving class info for GBG
[+] Unknown type 0xb'2\x00'
[+] Retrieving class info for Data
[+] Unknown type 0xb'7\x00'
[*] Target system bootKey: 0x251700480d3e5cdd6b92fc762a5f3187
[*] Dumping LSA Secrets
Traceback (most recent call last):
  File "./dpapi.py", line 536, in <module>
    executer.run()
  File "./dpapi.py", line 135, in run
    decryptedKey = mk.decrypt(self.dpapiSystem['UserKey'])
TypeError: 'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
```

**Comment by asolino** [comment]
I think you're providing the wrong hive to the `-security` parameter. 

Still.. we should output a nicer error.

**Comment by darkoperator** [comment]
Correct 

```
$ python3 ./dpapi.py -debug masterkey -f /home/carlos/Desktop/f7b45dca-3bf7-457f-bcc6-0d746720ab19 -security /home/carlos/Desktop/security -system /home/carlos/Desktop/system
Impacket v0.9.22.dev1+20200728.212319.39ef0381 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200728.212319.39ef0381-py3.8.egg/impacket
[MASTERKEYFILE]
Version     :        2 (2)
Guid        : f7b45dca-3bf7-457f-bcc6-0d746720ab19
Flags       :        6 (6)
Policy      :        0 (0)
MasterKeyLen: 000000b0 (176)
BackupKeyLen: 00000090 (144)
CredHistLen : 00000014 (20)
DomainKeyLen: 00000000 (0)

[+] Retrieving class info for JD
[+] Unknown type 0xb'6\x00'
[+] Retrieving class info for Skew1
[+] Unknown type 0xb'0\x00'
[+] Retrieving class info for GBG
[+] Unknown type 0xb'2\x00'
[+] Retrieving class info for Data
[+] Unknown type 0xb'7\x00'
[*] Target system bootKey: 0x251700480d3e5cdd6b92fc762a5f3187
[*] Dumping LSA Secrets
[+] Decrypting LSA Key
[+] Looking into $MACHINE.ACC
[*] $MACHINE.ACC 
[+] Could not calculate machine account Kerberos keys, printing plain password (hex encoded)
[+] Looking into DefaultPassword
[+] Discarding secret DefaultPassword, NULL Data
[+] Looking into DPAPI_SYSTEM
[*] DPAPI_SYSTEM 
[+] Looking into NL$KM
[*] NL$KM 
Decrypted key with MachineKey
Decrypted key: 0x47525a542e954f3471da2304599851092639a93d7728358597ee6f0865e8f917ba64249d423584cbd7e8f5dbffa4aed07d3fe6b9cab9a8a143ac4e2fcb629f34
```
