### ISSUE TITLE
ntlmrelayx.p

### ISSUE THREAD

**Issue by zezomehdawi** [SecureAuthCorp/impacket#920]
i have faced this issue lately 
anyone can help....

root@kali:/home/kali/ ntlmrelayx.py -tf /home/kali/target.txt -smb2support
Impacket v0.9.22.dev1+20200813.221956.1c893884 - Copyright 2020 SecureAuth Corporation

[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMB loaded..
[*] Running in relay mode to hosts in targetfile
Traceback (most recent call last):
  File "/usr/local/bin/ntlmrelayx.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.9.22.dev1+20200813.221956.1c893884', 'ntlmrelayx.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200813.221956.1c893884-py3.8.egg/EGG-INFO/scripts/ntlmrelayx.py", line 385, in <module>
    c = start_servers(options, threads)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200813.221956.1c893884-py3.8.egg/EGG-INFO/scripts/ntlmrelayx.py", line 180, in start_servers
    s = server(c)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200813.221956.1c893884-py3.8.egg/impacket/examples/ntlmrelayx/servers/smbrelayserver.py", line 92, in __init__
    self.server = SMBSERVER((config.interfaceIp,smbport), config_parser = smbConfig)
  File "/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20200813.221956.1c893884-py3.8.egg/impacket/smbserver.py", line 3746, in __init__
    socketserver.TCPServer.__init__(self, server_address, handler_class)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by asolino** [comment]
You have another server listening at TCP/IP port 445. Check this with `netstat` before running `ntlmrelayx.py`.  Closing.
