### ISSUE TITLE
SMB client triggers an uncaught exception if the remote server refuses SMBv1 and closes the connection

### ISSUE THREAD

**Issue by cnotin** [SecureAuthCorp/impacket#934]
### Configuration  
impacket version:  latest from Git
Python version:  3.8
Target OS:  Windows

### Issue
The SMB client for NTLM relay will only declare SMBv1 (with `NT LM 0.12` in the "negotiate protocol request") but many modern windows devices refuse SMBv1 and simply close the connection.
This isn't very well handled:
```
[*] Servers started, waiting for connections
[*] XXX: Received connection from 192.168.42.11, attacking target smb://192.168.42.2
----------------------------------------
Exception happened during processing of request from ('192.168.42.11', 50036)
Traceback (most recent call last):
  File "C:\Tools\impacket\impacket\nmb.py", line 979, in non_polling_read
    received = self._sock.recv(bytes_left)
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
[...]
  File "C:\Tools\impacket\impacket\examples\ntlmrelayx\clients\smbrelayclient.py", line 276, in initConnection
    packet = self.session.negotiateSessionWildcard(None, self.targetHost, self.targetHost, self.targetPort, 60, self.extendedSecurity,
  File "C:\Tools\impacket\impacket\smbconnection.py", line 177, in negotiateSessionWildcard
    resp = self._nmbSession.recv_packet(timeout)
  File "C:\Tools\impacket\impacket\nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "C:\Tools\impacket\impacket\nmb.py", line 997, in __read
    data = self.read_function(4, timeout)
  File "C:\Tools\impacket\impacket\nmb.py", line 983, in non_polling_read
    raise NetBIOSError('Error occurs while reading from remote', ERRCLASS_OS, ex[0])
TypeError: 'ConnectionResetError' object is not subscriptable
----------------------------------------
[*] XXX: Received connection from 192.168.42.11, but there are no more targets left!
```

I suggest adding a catch :)

### PCAP  
![image](https://user-images.githubusercontent.com/550823/92043066-a8625b80-ed7b-11ea-877b-74e15a981171.png)

**Comment by asolino** [comment]
Hey @cnotin 

Yup that should better be handled. Thanks for pointing that out.
Now, did you try running `ntlmrelayx.py` with `-smb2support` switch? the SMB Client should extend the version negotiation (check [here](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/clients/smbrelayclient.py#L266))

**Comment by cnotin** [comment]
Wow thanks for responding quickly! And sorry for not proposing a PR but I'm working on a new relay server and I wanted to take note of this 😉
I did not try with -smb2support but that would certainly help! Thanks for the reminder!

**Comment by cnotin** [comment]
Confirmed that -smb2support helps!

**Comment by cnotin** [comment]
Here's a PR @asolino :)
