### ISSUE TITLE
HTTPRelayServer: no module named http.server with Python2

### ISSUE THREAD

**Issue by cnotin** [SecureAuthCorp/impacket#942]
### Configuration  
impacket version: latest from git
Python version: 2
Target OS: Kali

### Debug Output With Command String  
HTTPRelayServer for ntlmrelayx isn't compatible with Python2:
```python
# PYTHONPATH=. python2 ./examples/ntlmrelayx.py                                                                              
Traceback (most recent call last):
  File "./examples/ntlmrelayx.py", line 49, in <module>
    from impacket.examples.ntlmrelayx.servers import SMBRelayServer, HTTPRelayServer, WCFRelayServer
  File "/root/tools/impacket/impacket/examples/ntlmrelayx/servers/__init__.py", line 1, in <module>
    from impacket.examples.ntlmrelayx.servers.httprelayserver import HTTPRelayServer
  File "/root/tools/impacket/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 16, in <module>
    import http.server
ImportError: No module named http.server
```

**Comment by asolino** [comment]
Don't you have `future` package installed in Python2? That should take care of that and is included in [requirements.txt](https://github.com/SecureAuthCorp/impacket/blob/master/requirements.txt#L1)

**Comment by cnotin** [comment]
Oops I was doing a very quick test, let me check!

**Comment by cnotin** [comment]
Indeed sorry, please ignore ;)
