### ISSUE TITLE
schtask fails in tsch on Windows 10 (1909 and 1803) 

### ISSUE THREAD

**Issue by andrewiodice** [SecureAuthCorp/impacket#958]
I'm having trouble with impacket accessing schtasks on Windows 10. 
This appears to be a Windows issue and not necessarily tsch. 
I'm using impacket-0.9.21 on python3.6 from Windows 10 (2004).

The MS-TSCH function is failing with rpc_s_access_denied on Windows 10 (1909 and 1803) 
but works on Windows 10 (2004) and Windows 8.1 and Windows 7.
The user has admin privileges and the firewall has been updated to allow access.

I’ve updated test_tsch.py to call windows 8.1 and windows 10 locally see line 1071 in test_tsch.py
The following exception occurs when calling windows 10.

Traceback (most recent call last):
  File "C:/development/testcode/impacket-0.9.21/tests/SMB_RPC/test_tsch.py", line 1091, in <module>
    t.test_hSchRpcCreateFolder_hSchRpcEnumFolders_hSchRpcDelete()
  File "C:/development/testcode/impacket-0.9.21/tests/SMB_RPC/test_tsch.py", line 452, in test_hSchRpcCreateFolder_hSchRpcEnumFolders_hSchRpcDelete
    resp = tsch.hSchRpcCreateFolder(dce, '\\Beto')
  File "C:\development\testcode\impacket-0.9.21\impacket\dcerpc\v5\tsch.py", line 687, in hSchRpcCreateFolder
    return dce.request(schRpcCreateFolder)
  File "C:\development\testcode\impacket-0.9.21\impacket\dcerpc\v5\rpcrt.py", line 856, in request
    answer = self.recv()
  File "C:\development\testcode\impacket-0.9.21\impacket\dcerpc\v5\rpcrt.py", line 1320, in recv
    raise DCERPCException(rpc_status_codes[status_code])
impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

[test_tsch.py.txt](https://github.com/SecureAuthCorp/impacket/files/5275749/test_tsch.py.txt)

**Comment by mohemiv** [comment]
Hello @andrewiodice,

Please test the code in this PR: https://github.com/SecureAuthCorp/impacket/pull/916

**Comment by asolino** [comment]
Closing this one as https://github.com/SecureAuthCorp/impacket/pull/916 got merged.
